"""Run the five Task 1 identity-gate sensitivity rehearsals."""

from __future__ import annotations

import argparse
import csv
import hashlib
import sys
import tempfile
from pathlib import Path

if __package__ in (None, ""):
    sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from Scripts.phase192 import identity_contracts


def drop_first_data_row(source: Path, target: Path) -> None:
    """Phase192 drop first data row."""
    lines = source.read_text(encoding="utf-8").splitlines(keepends=True)
    if len(lines) < 2:
        raise ValueError(f"identity surface has no data rows: {source}")
    target.write_text("".join([lines[0], *lines[2:]]), encoding="utf-8")


def generated_byte_mutation(manifest: Path, root: Path) -> int:
    """Phase192 generated byte mutation."""
    with manifest.open(encoding="utf-8", newline="") as handle:
        row = next(csv.DictReader(handle, delimiter="\t"))
    source = root / row["path"]
    original = source.read_bytes()
    mutated = bytes([original[0] ^ 1]) + original[1:]
    if hashlib.sha256(mutated).hexdigest().upper() == row["sha256"]:
        return 0
    return 1


def main(argv: list[str] | None = None) -> int:
    """Phase192 main."""
    parser = argparse.ArgumentParser()
    parser.add_argument("--identity", type=Path, default=Path("build/phase192/baseline/identity"))
    parser.add_argument("--generated", type=Path, default=Path("build/phase192/baseline/generated-manifest.tsv"))
    parser.add_argument("--root", type=Path, default=Path("."))
    parser.add_argument("--report", type=Path, required=True)
    args = parser.parse_args(argv)
    targets = [
        ("managed-public-member", "managed-api-surface.tsv"),
        ("python-export", "python-symbols.tsv"),
        ("cpp-symbol", "cpp-symbol-surface.tsv"),
        ("test-name", "csharp-test-names.tsv"),
    ]
    results: list[str] = []
    with tempfile.TemporaryDirectory(prefix="phase192-sensitivity-") as temp:
        temp_root = Path(temp)
        for label, filename in targets:
            mutated = temp_root / filename
            drop_first_data_row(args.identity / filename, mutated)
            exit_code = identity_contracts.compare_tsv(args.identity / filename, mutated)
            if exit_code != 1:
                raise AssertionError(f"{label} mutation was not RED")
            results.append(f"MUTATION={label} RESULT=RED EXIT=1")
    generated_exit = generated_byte_mutation(args.generated, args.root)
    if generated_exit != 1:
        raise AssertionError("generated byte mutation was not RED")
    results.append("MUTATION=generated-line RESULT=RED EXIT=1")
    args.report.parent.mkdir(parents=True, exist_ok=True)
    args.report.write_text("\n".join(results) + "\nSENSITIVITY_PROOF=5/5_KILLED\n", encoding="utf-8")
    print("SENSITIVITY_PROOF=5/5_KILLED")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
