// Copyright (c) 2026 Jianbin Liu and Unity2Foxglove contributors.
// SPDX-License-Identifier: Apache-2.0
//
// Module: Editor/FoxRun
// Purpose: Writes generated runtime FoxRun schema info from canonical manifest data.

using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading;

namespace Unity.FoxgloveSDK.Editor
{
    public static class FoxRunSchemaInfoWriter
    {
        public const string SchemaInfoFileName = "FoxRunSchemaInfo.g.cs";
        public const string SchemaInfoMetaFileName = "FoxRunSchemaInfo.g.cs.meta";
        // Stable Unity GUID for the generated schema-info asset. Do not randomize:
        // downstream package imports and evidence diffs rely on this path staying stable.
        private const string StableSchemaInfoMetaGuid = "b1e4f0edc9dd4a989f26082ba9b5e113";
        private const int ReplaceAttempts = 3;
        private const int ReplaceRetryDelayMilliseconds = 50;
        private static readonly UTF8Encoding Utf8NoBom = new UTF8Encoding(false);

        public static FoxRunSchemaInfoVerification WriteGeneratedInfoFiles(
            string outputDirectory,
            FoxRunCanonicalManifest manifest)
        {
            if (string.IsNullOrEmpty(outputDirectory))
                throw new ArgumentException("Output directory is required.", nameof(outputDirectory));
            if (manifest == null)
                throw new ArgumentNullException(nameof(manifest));

            var source = GenerateSource(manifest);
            Directory.CreateDirectory(outputDirectory);

            var sourcePath = Path.Combine(outputDirectory, SchemaInfoFileName);
            WriteIfChanged(sourcePath, source);
            EnsureMetaFile(Path.Combine(outputDirectory, SchemaInfoMetaFileName));

            var verification = VerifyGeneratedInfo(manifest, source);
            if (!verification.IsValid)
                throw new InvalidOperationException("Generated FoxRun schema info failed verification: " + string.Join("; ", verification.Errors));
            return verification;
        }

        public static string GenerateSource(FoxRunCanonicalManifest manifest)
        {
            if (manifest == null)
                throw new ArgumentNullException(nameof(manifest));

            var types = manifest.Sections.FoxRun.Types;
            var contractCount = types.Sum(type => type.Contracts.Count);
            var fieldCount = types.Sum(type => type.Contracts.Sum(contract => contract.Fields.Count));

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("// Copyright (c) 2026 Jianbin Liu and Unity2Foxglove contributors.");
            sb.AppendLine("// SPDX-License-Identifier: Apache-2.0");
            sb.AppendLine("// Generated FoxRun schema evidence. Do not edit by hand.");
            sb.AppendLine("namespace Unity.FoxgloveSDK.Generated");
            sb.AppendLine("{");
            sb.AppendLine("    using Unity.FoxgloveSDK.Components;");
            sb.AppendLine();
            sb.AppendLine("    public static class FoxRunSchemaInfo");
            sb.AppendLine("    {");
            sb.AppendLine("        public const int ManifestVersion = " + manifest.ManifestVersion.ToString(CultureInfo.InvariantCulture) + ";");
            sb.AppendLine("        public const string PackageName = " + StringLiteral(manifest.Package) + ";");
            sb.AppendLine("        public const string GeneratorName = " + StringLiteral(manifest.Generator.Name) + ";");
            sb.AppendLine("        public const int GeneratorMajorVersion = " + manifest.Generator.MajorVersion.ToString(CultureInfo.InvariantCulture) + ";");
            sb.AppendLine("        public const string GlobalManifestHash = " + StringLiteral(manifest.GlobalManifestHash) + ";");
            sb.AppendLine("        public const string FoxRunManifestHash = " + StringLiteral(manifest.Sections.FoxRun.ManifestHash) + ";");
            sb.AppendLine("        public const int TypeCount = " + types.Count.ToString(CultureInfo.InvariantCulture) + ";");
            sb.AppendLine("        public const int ContractCount = " + contractCount.ToString(CultureInfo.InvariantCulture) + ";");
            sb.AppendLine("        public const int FieldCount = " + fieldCount.ToString(CultureInfo.InvariantCulture) + ";");
            sb.AppendLine();
            sb.AppendLine("        public static readonly FoxRunSchemaTypeInfo[] Types =");
            WriteTypesArray(sb, types, 3);
            sb.AppendLine(";");
            sb.AppendLine();
            sb.AppendLine("        [UnityEngine.RuntimeInitializeOnLoadMethod(UnityEngine.RuntimeInitializeLoadType.BeforeSceneLoad)]");
            sb.AppendLine("        private static void Register()");
            sb.AppendLine("        {");
            sb.AppendLine("            FoxRunSchemaInfoRegistry.RegisterGenerated(");
            sb.AppendLine("                new FoxRunSchemaManifestInfo(");
            sb.AppendLine("                    ManifestVersion,");
            sb.AppendLine("                    PackageName,");
            sb.AppendLine("                    GeneratorName,");
            sb.AppendLine("                    GeneratorMajorVersion,");
            sb.AppendLine("                    GlobalManifestHash,");
            sb.AppendLine("                    FoxRunManifestHash,");
            sb.AppendLine("                    Types));");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        public static FoxRunSchemaInfoVerification VerifyGeneratedInfo(
            FoxRunCanonicalManifest manifest,
            string generatedSource)
        {
            if (manifest == null)
                throw new ArgumentNullException(nameof(manifest));

            generatedSource = generatedSource ?? string.Empty;
            var expectedTypeCount = manifest.Sections.FoxRun.Types.Count;
            var expectedContractCount = manifest.Sections.FoxRun.Types.Sum(type => type.Contracts.Count);
            var expectedFieldCount = manifest.Sections.FoxRun.Types.Sum(type => type.Contracts.Sum(contract => contract.Fields.Count));

            var result = new FoxRunSchemaInfoVerification(
                manifest.GlobalManifestHash,
                ExtractStringConstant(generatedSource, "GlobalManifestHash"),
                manifest.Sections.FoxRun.ManifestHash,
                ExtractStringConstant(generatedSource, "FoxRunManifestHash"),
                expectedTypeCount,
                ExtractIntConstant(generatedSource, "TypeCount"),
                expectedContractCount,
                ExtractIntConstant(generatedSource, "ContractCount"),
                expectedFieldCount,
                ExtractIntConstant(generatedSource, "FieldCount"));

            if (!string.Equals(result.ExpectedGlobalManifestHash, result.ActualGlobalManifestHash, StringComparison.Ordinal))
                result.AddError("GlobalManifestHash mismatch.");
            if (!string.Equals(result.ExpectedFoxRunManifestHash, result.ActualFoxRunManifestHash, StringComparison.Ordinal))
                result.AddError("FoxRunManifestHash mismatch.");
            if (result.ExpectedTypeCount != result.ActualTypeCount)
                result.AddError("TypeCount mismatch.");
            if (result.ExpectedContractCount != result.ActualContractCount)
                result.AddError("ContractCount mismatch.");
            if (result.ExpectedFieldCount != result.ActualFieldCount)
                result.AddError("FieldCount mismatch.");

            return result;
        }

        private static void WriteTypesArray(StringBuilder sb, IReadOnlyList<FoxRunManifestType> types, int indentLevel)
        {
            var indent = Indent(indentLevel);
            var inner = Indent(indentLevel + 1);
            sb.AppendLine(indent + "new FoxRunSchemaTypeInfo[]");
            sb.AppendLine(indent + "{");
            foreach (var type in types)
            {
                sb.AppendLine(inner + "new FoxRunSchemaTypeInfo(");
                sb.AppendLine(inner + "    " + StringLiteral(type.DeclaringType) + ",");
                WriteContractsArray(sb, type.Contracts, indentLevel + 2);
                sb.AppendLine(inner + "),");
            }
            sb.Append(indent + "}");
        }

        private static void WriteContractsArray(StringBuilder sb, IReadOnlyList<FoxRunManifestContract> contracts, int indentLevel)
        {
            var indent = Indent(indentLevel);
            var inner = Indent(indentLevel + 1);
            sb.AppendLine(indent + "new FoxRunSchemaContractInfo[]");
            sb.AppendLine(indent + "{");
            foreach (var contract in contracts)
            {
                sb.AppendLine(inner + "new FoxRunSchemaContractInfo(");
                sb.AppendLine(inner + "    " + StringLiteral(contract.DeclaringType) + ",");
                sb.AppendLine(inner + "    " + StringLiteral(contract.Topic) + ",");
                sb.AppendLine(inner + "    " + StringLiteral(contract.SchemaName) + ",");
                sb.AppendLine(inner + "    " + StringLiteral(contract.Encoding) + ",");
                sb.AppendLine(inner + "    " + StringLiteral(contract.ContractHash) + ",");
                sb.AppendLine(inner + "    " + StringLiteral(contract.BindingHash) + ",");
                sb.AppendLine(inner + "    " + StringLiteral(contract.PolicyHash) + ",");
                sb.AppendLine(inner + "    " + StringLiteral(contract.Policy.Mode) + ",");
                sb.AppendLine(inner + "    " + FloatLiteral(contract.Policy.RateHz) + ",");
                sb.AppendLine(inner + "    " + FloatLiteral(contract.Policy.ChangeEpsilon) + ",");
                sb.AppendLine(inner + "    " + FloatLiteral(contract.Policy.ForceIntervalSeconds) + ",");
                WriteFieldsArray(sb, contract.Fields, indentLevel + 2);
                sb.AppendLine(inner + "),");
            }
            sb.AppendLine(indent + "}");
        }

        private static void WriteFieldsArray(StringBuilder sb, IReadOnlyList<FoxRunManifestField> fields, int indentLevel)
        {
            var indent = Indent(indentLevel);
            var inner = Indent(indentLevel + 1);
            sb.AppendLine(indent + "new FoxRunSchemaFieldInfo[]");
            sb.AppendLine(indent + "{");
            foreach (var field in fields)
            {
                sb.AppendLine(inner + "new FoxRunSchemaFieldInfo(");
                sb.AppendLine(inner + "    " + StringLiteral(field.JsonName) + ",");
                sb.AppendLine(inner + "    " + StringLiteral(field.MemberName) + ",");
                sb.AppendLine(inner + "    " + StringLiteral(field.MemberKind) + ",");
                sb.AppendLine(inner + "    " + StringLiteral(field.Type) + ",");
                sb.AppendLine(inner + "    " + BoolLiteral(field.Nullable) + ",");
                sb.AppendLine(inner + "    " + BoolLiteral(field.Array) + "),");
            }
            sb.AppendLine(indent + "}");
        }

        private static void EnsureMetaFile(string metaPath)
        {
            if (File.Exists(metaPath))
                return;

            WriteIfChanged(
                metaPath,
                "fileFormatVersion: 2\n" +
                "guid: " + StableSchemaInfoMetaGuid + "\n");
        }

        private static void WriteIfChanged(string path, string content)
        {
            var bytes = Utf8NoBom.GetBytes(content);
            if (File.Exists(path) && File.ReadAllBytes(path).SequenceEqual(bytes))
                return;

            var tempPath = path + ".tmp-" + Guid.NewGuid().ToString("N");
            try
            {
                File.WriteAllBytes(tempPath, bytes);
                ReplaceFile(tempPath, path);
            }
            finally
            {
                if (File.Exists(tempPath))
                    File.Delete(tempPath);
            }
        }

        private static void ReplaceFile(string tempPath, string path)
        {
            if (!File.Exists(path))
            {
                File.Move(tempPath, path);
                return;
            }

            Exception replaceException = null;
            for (var attempt = 0; attempt < ReplaceAttempts; attempt++)
            {
                try
                {
                    ClearReadOnly(path);
                    File.Replace(tempPath, path, null);
                    return;
                }
                catch (PlatformNotSupportedException ex)
                {
                    replaceException = ex;
                    break;
                }
                catch (IOException ex)
                {
                    replaceException = ex;
                    DelayBeforeRetry(attempt);
                }
                catch (UnauthorizedAccessException ex)
                {
                    replaceException = ex;
                    DelayBeforeRetry(attempt);
                }
            }

            CopyTempOverDestination(tempPath, path, replaceException);
        }

        private static void CopyTempOverDestination(string tempPath, string path, Exception originalException)
        {
            Exception copyException = null;
            for (var attempt = 0; attempt < ReplaceAttempts; attempt++)
            {
                try
                {
                    ClearReadOnly(path);
                    File.Copy(tempPath, path, overwrite: true);
                    return;
                }
                catch (IOException ex)
                {
                    copyException = ex;
                    DelayBeforeRetry(attempt);
                }
                catch (UnauthorizedAccessException ex)
                {
                    copyException = ex;
                    DelayBeforeRetry(attempt);
                }
            }

            throw new IOException(
                "Failed to replace generated FoxRun schema info artifact '" + path + "'.",
                copyException ?? originalException);
        }

        private static void ClearReadOnly(string path)
        {
            if (!File.Exists(path))
                return;

            var attributes = File.GetAttributes(path);
            if ((attributes & FileAttributes.ReadOnly) != 0)
                File.SetAttributes(path, attributes & ~FileAttributes.ReadOnly);
        }

        private static void DelayBeforeRetry(int attempt)
        {
            // Build/Play-Mode hooks run on Unity's main thread; keep the retry
            // bounded and tiny so transient antivirus/file-indexer locks can clear
            // without hiding a real write failure.
            if (attempt + 1 < ReplaceAttempts)
                Thread.Sleep(ReplaceRetryDelayMilliseconds);
        }

        private static string StringLiteral(string value)
        {
            value = value ?? string.Empty;
            var sb = new StringBuilder(value.Length + 2);
            sb.Append('"');
            foreach (var c in value)
            {
                switch (c)
                {
                    case '"': sb.Append("\\\""); break;
                    case '\\': sb.Append("\\\\"); break;
                    case '\b': sb.Append("\\b"); break;
                    case '\f': sb.Append("\\f"); break;
                    case '\n': sb.Append("\\n"); break;
                    case '\r': sb.Append("\\r"); break;
                    case '\t': sb.Append("\\t"); break;
                    default:
                        if (c < 0x20)
                            sb.Append("\\u").Append(((int)c).ToString("x4", CultureInfo.InvariantCulture));
                        else
                            sb.Append(c);
                        break;
                }
            }
            sb.Append('"');
            return sb.ToString();
        }

        private static string FloatLiteral(float value)
        {
            if (float.IsNaN(value) || float.IsInfinity(value))
                return "0f";
            // Match canonical manifest formatting so generated source is stable across runtimes.
            return value.ToString("G9", CultureInfo.InvariantCulture) + "f";
        }

        private static string BoolLiteral(bool value)
        {
            return value ? "true" : "false";
        }

        private static string Indent(int level)
        {
            return new string(' ', level * 4);
        }

        private static string ExtractStringConstant(string source, string name)
        {
            var marker = "const string " + name + " = ";
            var start = source.IndexOf(marker, StringComparison.Ordinal);
            if (start < 0)
                return string.Empty;

            start = source.IndexOf('"', start + marker.Length);
            if (start < 0)
                return string.Empty;

            var sb = new StringBuilder();
            for (var i = start + 1; i < source.Length; i++)
            {
                var c = source[i];
                if (c == '"')
                    return sb.ToString();

                if (c != '\\')
                {
                    sb.Append(c);
                    continue;
                }

                if (++i >= source.Length)
                    return string.Empty;

                var escaped = source[i];
                switch (escaped)
                {
                    case '"': sb.Append('"'); break;
                    case '\\': sb.Append('\\'); break;
                    case 'b': sb.Append('\b'); break;
                    case 'f': sb.Append('\f'); break;
                    case 'n': sb.Append('\n'); break;
                    case 'r': sb.Append('\r'); break;
                    case 't': sb.Append('\t'); break;
                    case 'u':
                        if (i + 4 >= source.Length)
                            return string.Empty;
                        var hex = source.Substring(i + 1, 4);
                        if (!int.TryParse(hex, NumberStyles.HexNumber, CultureInfo.InvariantCulture, out var codePoint))
                            return string.Empty;
                        sb.Append((char)codePoint);
                        i += 4;
                        break;
                    default:
                        sb.Append(escaped);
                        break;
                }
            }

            return string.Empty;
        }

        private static int ExtractIntConstant(string source, string name)
        {
            var marker = "const int " + name + " = ";
            var start = source.IndexOf(marker, StringComparison.Ordinal);
            if (start < 0)
                return -1;

            start += marker.Length;
            var end = source.IndexOf(';', start);
            if (end < 0)
                return -1;

            return int.TryParse(source.Substring(start, end - start).Trim(), NumberStyles.Integer, CultureInfo.InvariantCulture, out var value)
                ? value
                : -1;
        }
    }

    public sealed class FoxRunSchemaInfoVerification
    {
        private readonly List<string> _errors = new List<string>();

        public string ExpectedGlobalManifestHash { get; }
        public string ActualGlobalManifestHash { get; }
        public string ExpectedFoxRunManifestHash { get; }
        public string ActualFoxRunManifestHash { get; }
        public int ExpectedTypeCount { get; }
        public int ActualTypeCount { get; }
        public int ExpectedContractCount { get; }
        public int ActualContractCount { get; }
        public int ExpectedFieldCount { get; }
        public int ActualFieldCount { get; }
        public IReadOnlyList<string> Errors => _errors.AsReadOnly();
        public bool IsValid => _errors.Count == 0;

        public FoxRunSchemaInfoVerification(
            string expectedGlobalManifestHash,
            string actualGlobalManifestHash,
            string expectedFoxRunManifestHash,
            string actualFoxRunManifestHash,
            int expectedTypeCount,
            int actualTypeCount,
            int expectedContractCount,
            int actualContractCount,
            int expectedFieldCount,
            int actualFieldCount)
        {
            ExpectedGlobalManifestHash = expectedGlobalManifestHash ?? string.Empty;
            ActualGlobalManifestHash = actualGlobalManifestHash ?? string.Empty;
            ExpectedFoxRunManifestHash = expectedFoxRunManifestHash ?? string.Empty;
            ActualFoxRunManifestHash = actualFoxRunManifestHash ?? string.Empty;
            ExpectedTypeCount = expectedTypeCount;
            ActualTypeCount = actualTypeCount;
            ExpectedContractCount = expectedContractCount;
            ActualContractCount = actualContractCount;
            ExpectedFieldCount = expectedFieldCount;
            ActualFieldCount = actualFieldCount;
        }

        public void AddError(string message)
        {
            if (!string.IsNullOrEmpty(message))
                _errors.Add(message);
        }
    }
}
