// Copyright (c) 2026 Jianbin Liu and Unity2Foxglove contributors.
// SPDX-License-Identifier: Apache-2.0
//
// Module: Editor/FoxRun
// Purpose: Writes generated runtime FoxRun schema info from canonical manifest data.

using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Text;
using System.Threading;
using Unity.FoxgloveSDK.Components;

namespace Unity.FoxgloveSDK.Editor
{
    public static class FoxRunSchemaInfoWriter
    {
        public const string SchemaInfoFileName = "FoxRunSchemaInfo.g.cs";
        public const string SchemaInfoMetaFileName = "FoxRunSchemaInfo.g.cs.meta";
        // Stable Unity GUID for the generated schema-info asset. Do not randomize:
        // downstream package imports and evidence diffs rely on this path staying stable.
        private const string StableSchemaInfoMetaGuid = "b1e4f0edc9dd4a989f26082ba9b5e113";
        private const int ReplaceAttempts = 3;
        private const int ReplaceRetryDelayMilliseconds = 50;
        private static readonly UTF8Encoding Utf8NoBom = new UTF8Encoding(false);
        private static readonly string[] Indents =
        {
            "",
            "    ",
            "        ",
            "            ",
            "                ",
            "                    ",
            "                        "
        };

        public static FoxRunSchemaInfoVerification WriteGeneratedInfoFiles(
            string outputDirectory,
            FoxRunCanonicalManifest manifest)
        {
            return WriteGeneratedInfoFilesWithResult(outputDirectory, manifest).Verification;
        }

        public static FoxRunSchemaInfoWriteResult WriteGeneratedInfoFilesWithResult(
            string outputDirectory,
            FoxRunCanonicalManifest manifest)
        {
            if (string.IsNullOrEmpty(outputDirectory))
                throw new ArgumentException("Output directory is required.", nameof(outputDirectory));
            if (manifest == null)
                throw new ArgumentNullException(nameof(manifest));

            var source = GenerateSource(manifest);
            var verification = VerifyGeneratedInfo(manifest, source);
            if (!verification.IsValid)
                throw new InvalidOperationException("Generated FoxRun schema info failed verification: " + string.Join("; ", verification.Errors));

            Directory.CreateDirectory(outputDirectory);

            var sourcePath = Path.Combine(outputDirectory, SchemaInfoFileName);
            var sourceChanged = WriteIfChanged(sourcePath, source);
            var metaChanged = EnsureMetaFile(Path.Combine(outputDirectory, SchemaInfoMetaFileName));
            return new FoxRunSchemaInfoWriteResult(verification, sourceChanged, metaChanged);
        }

        public static string GenerateSource(FoxRunCanonicalManifest manifest)
        {
            if (manifest == null)
                throw new ArgumentNullException(nameof(manifest));

            var types = manifest.Sections.FoxRun.Types;
            var counts = CountManifest(manifest);

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("// Copyright (c) 2026 Jianbin Liu and Unity2Foxglove contributors.");
            sb.AppendLine("// SPDX-License-Identifier: Apache-2.0");
            sb.AppendLine("// Generated FoxRun schema evidence. Do not edit by hand.");
            sb.AppendLine("namespace Unity.FoxgloveSDK.Generated");
            sb.AppendLine("{");
            sb.AppendLine("    using Unity.FoxgloveSDK.Components;");
            sb.AppendLine();
            sb.AppendLine("    public static class FoxRunSchemaInfo");
            sb.AppendLine("    {");
            sb.AppendLine("        public const int ManifestVersion = " + manifest.ManifestVersion.ToString(CultureInfo.InvariantCulture) + ";");
            sb.Append("        public const string PackageName = ");
            AppendStringLiteral(sb, manifest.Package);
            sb.AppendLine(";");
            sb.Append("        public const string GeneratorName = ");
            AppendStringLiteral(sb, manifest.Generator.Name);
            sb.AppendLine(";");
            sb.AppendLine("        public const int GeneratorMajorVersion = " + manifest.Generator.MajorVersion.ToString(CultureInfo.InvariantCulture) + ";");
            sb.Append("        public const string GlobalManifestHash = ");
            AppendStringLiteral(sb, manifest.GlobalManifestHash);
            sb.AppendLine(";");
            sb.Append("        public const string FoxRunManifestHash = ");
            AppendStringLiteral(sb, manifest.Sections.FoxRun.ManifestHash);
            sb.AppendLine(";");
            sb.Append("        public const string SubscriptionManifestHash = ");
            AppendStringLiteral(sb, manifest.Sections.Subscriptions.ManifestHash);
            sb.AppendLine(";");
            sb.AppendLine("        public const int TypeCount = " + counts.TypeCount.ToString(CultureInfo.InvariantCulture) + ";");
            sb.AppendLine("        public const int ContractCount = " + counts.ContractCount.ToString(CultureInfo.InvariantCulture) + ";");
            sb.AppendLine("        public const int FieldCount = " + counts.FieldCount.ToString(CultureInfo.InvariantCulture) + ";");
            sb.AppendLine("        public const int SubscriptionBindingCount = " + manifest.Sections.Subscriptions.Bindings.Count.ToString(CultureInfo.InvariantCulture) + ";");
            sb.AppendLine();
            sb.AppendLine("        public static readonly FoxRunSchemaTypeInfo[] Types =");
            WriteTypesArray(sb, types, 3);
            sb.AppendLine(";");
            sb.AppendLine();
            sb.AppendLine("        public static readonly FoxRunSchemaSubscriptionBindingInfo[] SubscriptionBindings =");
            WriteSubscriptionBindingsArray(sb, manifest.Sections.Subscriptions.Bindings, 3);
            sb.AppendLine(";");
            sb.AppendLine();
            sb.AppendLine("        [UnityEngine.RuntimeInitializeOnLoadMethod(UnityEngine.RuntimeInitializeLoadType.BeforeSceneLoad)]");
            sb.AppendLine("        private static void Register()");
            sb.AppendLine("        {");
            sb.AppendLine("            FoxRunSchemaInfoRegistry.RegisterGenerated(");
            sb.AppendLine("                new FoxRunSchemaManifestInfo(");
            sb.AppendLine("                    ManifestVersion,");
            sb.AppendLine("                    PackageName,");
            sb.AppendLine("                    GeneratorName,");
            sb.AppendLine("                    GeneratorMajorVersion,");
            sb.AppendLine("                    GlobalManifestHash,");
            sb.AppendLine("                    FoxRunManifestHash,");
            sb.AppendLine("                    Types,");
            sb.AppendLine("                    SubscriptionManifestHash,");
            sb.AppendLine("                    SubscriptionBindings));");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        public static FoxRunSchemaInfoVerification VerifyGeneratedInfo(
            FoxRunCanonicalManifest manifest,
            string generatedSource)
        {
            if (manifest == null)
                throw new ArgumentNullException(nameof(manifest));

            generatedSource = generatedSource ?? string.Empty;
            var counts = CountManifest(manifest);

            var result = new FoxRunSchemaInfoVerification(
                manifest.GlobalManifestHash,
                ExtractStringConstant(generatedSource, "GlobalManifestHash"),
                manifest.Sections.FoxRun.ManifestHash,
                ExtractStringConstant(generatedSource, "FoxRunManifestHash"),
                counts.TypeCount,
                ExtractIntConstant(generatedSource, "TypeCount"),
                counts.ContractCount,
                ExtractIntConstant(generatedSource, "ContractCount"),
                counts.FieldCount,
                ExtractIntConstant(generatedSource, "FieldCount"));

            if (!string.Equals(result.ExpectedGlobalManifestHash, result.ActualGlobalManifestHash, StringComparison.Ordinal))
                result.AddError("GlobalManifestHash mismatch.");
            if (!string.Equals(result.ExpectedFoxRunManifestHash, result.ActualFoxRunManifestHash, StringComparison.Ordinal))
                result.AddError("FoxRunManifestHash mismatch.");
            if (!string.Equals(
                    manifest.Sections.Subscriptions.ManifestHash,
                    ExtractStringConstant(generatedSource, "SubscriptionManifestHash"),
                    StringComparison.Ordinal))
            {
                result.AddError("SubscriptionManifestHash mismatch.");
            }
            if (result.ExpectedTypeCount != result.ActualTypeCount)
                result.AddError("TypeCount mismatch.");
            if (result.ExpectedContractCount != result.ActualContractCount)
                result.AddError("ContractCount mismatch.");
            if (result.ExpectedFieldCount != result.ActualFieldCount)
                result.AddError("FieldCount mismatch.");
            if (manifest.Sections.Subscriptions.Bindings.Count
                != ExtractIntConstant(generatedSource, "SubscriptionBindingCount"))
            {
                result.AddError("SubscriptionBindingCount mismatch.");
            }
            return result;
        }

        private static void WriteTypesArray(StringBuilder sb, IReadOnlyList<FoxRunManifestType> types, int indentLevel)
        {
            var indent = Indent(indentLevel);
            var inner = Indent(indentLevel + 1);
            sb.AppendLine(indent + "new FoxRunSchemaTypeInfo[]");
            sb.AppendLine(indent + "{");
            foreach (var type in types)
            {
                sb.AppendLine(inner + "new FoxRunSchemaTypeInfo(");
                AppendIndentedStringLiteralLine(sb, inner, type.DeclaringType, ",");
                WriteContractsArray(sb, type.Contracts, indentLevel + 2);
                sb.AppendLine(inner + "),");
            }
            sb.Append(indent + "}");
        }

        private static void WriteContractsArray(StringBuilder sb, IReadOnlyList<FoxRunManifestContract> contracts, int indentLevel)
        {
            var indent = Indent(indentLevel);
            var inner = Indent(indentLevel + 1);
            sb.AppendLine(indent + "new FoxRunSchemaContractInfo[]");
            sb.AppendLine(indent + "{");
            foreach (var contract in contracts)
            {
                sb.AppendLine(inner + "new FoxRunSchemaContractInfo(");
                AppendIndentedStringLiteralLine(sb, inner, contract.DeclaringType, ",");
                AppendIndentedStringLiteralLine(sb, inner, contract.Topic, ",");
                AppendIndentedStringLiteralLine(sb, inner, contract.SchemaName, ",");
                AppendIndentedStringLiteralLine(sb, inner, contract.Encoding, ",");
                AppendIndentedStringLiteralLine(sb, inner, contract.ContractHash, ",");
                AppendIndentedStringLiteralLine(sb, inner, contract.BindingHash, ",");
                AppendIndentedStringLiteralLine(sb, inner, contract.PolicyHash, ",");
                AppendIndentedStringLiteralLine(sb, inner, contract.Policy.Mode, ",");
                sb.AppendLine(inner + "    " + FloatLiteral(contract.Policy.Hz) + ",");
                sb.AppendLine(inner + "    " + FloatLiteral(contract.Policy.Tolerance) + ",");
                WriteFieldsArray(sb, contract.Fields, indentLevel + 2, trailingComma: true);
                AppendIndentedStringLiteralLine(sb, inner, contract.Flow, ",");
                AppendProtobufDescriptorSet(sb, inner, contract, trailingComma: true);
                AppendIndentedStringLiteralLine(sb, inner, contract.LogicalSchemaName, ",");
                sb.AppendLine(inner + "    " + BoolLiteral(contract.PublishAvailable) + ",");
                sb.AppendLine(inner + "    " + BoolLiteral(contract.SubscribeAvailable) + ",");
                AppendIndentedStringLiteralLine(sb, inner, contract.UnavailableDiagnosticId, ",");
                AppendIndentedStringLiteralLine(sb, inner, contract.UnavailableReason, ",");
                AppendIndentedStringLiteralLine(
                    sb,
                    inner,
                    contract.PublishUnavailableDiagnosticId,
                    ",");
                AppendIndentedStringLiteralLine(sb, inner, contract.PublishUnavailableReason, ",");
                AppendIndentedStringLiteralLine(
                    sb,
                    inner,
                    contract.SubscribeUnavailableDiagnosticId,
                    ",");
                AppendIndentedStringLiteralLine(sb, inner, contract.SubscribeUnavailableReason, ",");
                WriteStringArrayOrNull(
                    sb,
                    contract.PublishTransportIds,
                    indentLevel + 2,
                    trailingComma: true);
                if (contract.SubscribeTransportId == null)
                    sb.AppendLine(inner + "    null");
                else
                    AppendIndentedStringLiteralLine(
                        sb,
                        inner,
                        contract.SubscribeTransportId,
                        "");
                sb.AppendLine(inner + "),");
            }
            sb.AppendLine(indent + "}");
        }

        private static void WriteSubscriptionBindingsArray(
            StringBuilder sb,
            IReadOnlyList<FoxRunManifestSubscriptionBinding> bindings,
            int indentLevel)
        {
            var indent = Indent(indentLevel);
            var inner = Indent(indentLevel + 1);
            sb.AppendLine(indent + "new FoxRunSchemaSubscriptionBindingInfo[]");
            sb.AppendLine(indent + "{");
            foreach (var binding in bindings)
            {
                sb.AppendLine(inner + "new FoxRunSchemaSubscriptionBindingInfo(");
                AppendIndentedStringLiteralLine(sb, inner, binding.DeclaringType, ",");
                AppendIndentedStringLiteralLine(sb, inner, binding.MemberName, ",");
                AppendIndentedStringLiteralLine(sb, inner, binding.Topic, ",");
                AppendIndentedStringLiteralLine(sb, inner, binding.Flow, ",");
                WriteStringArrayOrNull(
                    sb,
                    binding.PublishTransportIds,
                    indentLevel + 2,
                    trailingComma: true);
                if (binding.SubscribeTransportId == null)
                    sb.AppendLine(inner + "    null,");
                else
                    AppendIndentedStringLiteralLine(
                        sb,
                        inner,
                        binding.SubscribeTransportId,
                        ",");
                AppendIndentedStringLiteralLine(sb, inner, binding.Reliability, ",");
                AppendIndentedStringLiteralLine(sb, inner, binding.Durability, ",");
                AppendIndentedStringLiteralLine(sb, inner, binding.History, ",");
                sb.AppendLine(inner + "    " + binding.Depth.ToString(CultureInfo.InvariantCulture) + ",");
                sb.AppendLine(inner + "    " + BoolLiteral(binding.SupportsWebSocket) + ",");
                sb.AppendLine(inner + "    " + BoolLiteral(binding.IsStream));
                sb.AppendLine(inner + "),");
            }
            sb.Append(indent + "}");
        }

        private static void WriteFieldsArray(
            StringBuilder sb,
            IReadOnlyList<FoxRunManifestField> fields,
            int indentLevel,
            bool trailingComma = false)
        {
            var indent = Indent(indentLevel);
            var inner = Indent(indentLevel + 1);
            sb.AppendLine(indent + "new FoxRunSchemaFieldInfo[]");
            sb.AppendLine(indent + "{");
            foreach (var field in fields)
            {
                sb.AppendLine(inner + "new FoxRunSchemaFieldInfo(");
                AppendIndentedStringLiteralLine(sb, inner, field.JsonName, ",");
                AppendIndentedStringLiteralLine(sb, inner, field.MemberName, ",");
                AppendIndentedStringLiteralLine(sb, inner, field.MemberKind, ",");
                AppendIndentedStringLiteralLine(sb, inner, field.Type, ",");
                sb.AppendLine(inner + "    " + BoolLiteral(field.Nullable) + ",");
                sb.AppendLine(inner + "    " + BoolLiteral(field.Array) + ",");
                sb.AppendLine(inner + "    " + BoolLiteral(field.Aggregate) + ",");
                sb.AppendLine(inner + "    " + (field.ProtobufMetadata?.FieldNumber ?? 0).ToString(CultureInfo.InvariantCulture) + ",");
                AppendTypeShapeInfo(sb, field.TypeShape, indentLevel + 2, trailingComma: true);
                AppendNormalizedScheduleInfo(sb, field.NormalizedSchedule, indentLevel + 2);
                sb.AppendLine(inner + "),");
            }
            sb.AppendLine(indent + (trailingComma ? "}," : "}"));
        }

        private static void AppendProtobufDescriptorSet(
            StringBuilder sb,
            string indent,
            FoxRunManifestContract contract,
            bool trailingComma = false)
        {
            if (!string.Equals(contract.Encoding, FoxRunGenerationDescriptorConstants.ProtobufEncoding, StringComparison.Ordinal))
            {
                sb.AppendLine(indent + "    null" + (trailingComma ? "," : string.Empty));
                return;
            }

            var descriptor = FoxRunProtobufContractBuilder.Build(ToProtobufContractInput(contract)).FileDescriptorSet;
            sb.Append(indent + "    global::System.Convert.FromBase64String(");
            AppendStringLiteral(sb, Convert.ToBase64String(descriptor));
            sb.AppendLine(")" + (trailingComma ? "," : string.Empty));
        }

        private static void AppendTypeShapeInfo(
            StringBuilder sb,
            FoxRunTypeShape shape,
            int indentLevel,
            bool trailingComma = false)
        {
            var indent = Indent(indentLevel);
            var inner = Indent(indentLevel + 1);
            if (shape == null)
            {
                sb.AppendLine(indent + "null" + (trailingComma ? "," : string.Empty));
                return;
            }

            sb.AppendLine(indent + "new FoxRunTypeShapeInfo(");
            sb.AppendLine(inner + "FoxRunTypeShapeInfoKind." + shape.Kind + ",");
            AppendIndentedStringLiteralLine(sb, indent, shape.TypeName, ",");
            AppendIndentedStringLiteralLine(sb, indent, shape.CanonicalType, ",");
            sb.AppendLine(inner + BoolLiteral(shape.Nullable) + ",");
            sb.AppendLine(inner + "FoxRunCollectionInfoKind." + shape.CollectionKind + ",");
            AppendTypeShapeInfo(sb, shape.ElementShape, indentLevel + 1, trailingComma: true);
            AppendTypeShapeFields(sb, shape.Fields, indentLevel + 1, trailingComma: true);
            AppendTypeShapeEnumValues(sb, shape.EnumValues, indentLevel + 1, trailingComma: true);
            sb.AppendLine(inner + BoolLiteral(shape.CanConstruct) + ",");
            sb.AppendLine(inner + BoolLiteral(shape.IsValueType));
            sb.AppendLine(indent + ")" + (trailingComma ? "," : string.Empty));
        }

        private static void AppendTypeShapeFields(
            StringBuilder sb,
            IReadOnlyList<FoxRunTypeField> fields,
            int indentLevel,
            bool trailingComma = false)
        {
            var indent = Indent(indentLevel);
            var inner = Indent(indentLevel + 1);
            sb.AppendLine(indent + "new FoxRunTypeFieldInfo[]");
            sb.AppendLine(indent + "{");
            foreach (var field in fields ?? Array.Empty<FoxRunTypeField>())
            {
                sb.AppendLine(inner + "new FoxRunTypeFieldInfo(");
                AppendIndentedStringLiteralLine(sb, inner, field.JsonName, ",");
                AppendIndentedStringLiteralLine(sb, inner, field.MemberName, ",");
                AppendTypeShapeInfo(sb, field.TypeShape, indentLevel + 2, trailingComma: true);
                sb.AppendLine(inner + "    " + BoolLiteral(field.Repeated) + ",");
                sb.AppendLine(inner + "    FoxRunCollectionInfoKind." + field.RepeatedCollectionKind + ",");
                sb.AppendLine(inner + "    " + BoolLiteral(field.CanAssign) + ",");
                sb.AppendLine(inner + "    " + BoolLiteral(field.IsNullable));
                sb.AppendLine(inner + "),");
            }
            sb.AppendLine(indent + "}" + (trailingComma ? "," : string.Empty));
        }

        private static void AppendTypeShapeEnumValues(
            StringBuilder sb,
            IReadOnlyList<FoxRunEnumValue> values,
            int indentLevel,
            bool trailingComma = false)
        {
            var indent = Indent(indentLevel);
            var inner = Indent(indentLevel + 1);
            sb.AppendLine(indent + "new FoxRunEnumValueInfo[]");
            sb.AppendLine(indent + "{");
            foreach (var value in values ?? Array.Empty<FoxRunEnumValue>())
            {
                sb.Append(inner + "new FoxRunEnumValueInfo(");
                AppendStringLiteral(sb, value.Name);
                sb.Append(", ")
                    .Append(value.Number.ToString(CultureInfo.InvariantCulture))
                    .AppendLine("),");
            }
            sb.AppendLine(indent + "}" + (trailingComma ? "," : string.Empty));
        }

        private static void AppendNormalizedScheduleInfo(
            StringBuilder sb,
            FoxRunNormalizedScheduleTuple schedule,
            int indentLevel)
        {
            var indent = Indent(indentLevel);
            var inner = Indent(indentLevel + 1);
            if (schedule == null)
            {
                sb.AppendLine(indent + "null");
                return;
            }

            sb.AppendLine(indent + "new FoxRunNormalizedScheduleInfo(");
            sb.AppendLine(inner + schedule.Policy.ToString(CultureInfo.InvariantCulture) + ",");
            sb.AppendLine(inner + BoolLiteral(schedule.HasExplicitHz) + ",");
            sb.AppendLine(inner + FloatLiteral(schedule.Hz) + ",");
            sb.AppendLine(inner + FloatLiteral(schedule.Tolerance) + ",");
            AppendIndentedStringLiteralLine(sb, indent, schedule.OnlyIf, ",");
            sb.AppendLine(inner + ((int)schedule.ConditionMemberKind).ToString(CultureInfo.InvariantCulture));
            sb.AppendLine(indent + ")");
        }

        private static FoxRunProtobufContractInput ToProtobufContractInput(FoxRunManifestContract contract)
        {
            var fields = new List<FoxRunProtobufFieldInput>();
            foreach (var field in contract.Fields)
            {
                fields.Add(new FoxRunProtobufFieldInput(
                    field.JsonName,
                    field.MemberName,
                    field.Type,
                    field.Array,
                    0,
                    field.TypeShape,
                    field.ProtobufMetadata));
            }

            return new FoxRunProtobufContractInput(
                contract.DeclaringType,
                contract.Topic,
                contract.SchemaName,
                fields);
        }

        private static bool EnsureMetaFile(string metaPath)
        {
            if (File.Exists(metaPath))
                return false;

            return WriteIfChanged(
                metaPath,
                "fileFormatVersion: 2\n" +
                "guid: " + StableSchemaInfoMetaGuid + "\n");
        }

        private static bool WriteIfChanged(string path, string content)
        {
            var bytes = Utf8NoBom.GetBytes(content ?? string.Empty);
            var existing = new FileInfo(path);
            if (existing.Exists && existing.Length == bytes.Length && FileContentEquals(path, bytes))
                return false;

            var tempPath = path + ".tmp-" + Guid.NewGuid().ToString("N");
            try
            {
                File.WriteAllBytes(tempPath, bytes);
                ReplaceFile(tempPath, path);
                return true;
            }
            finally
            {
                TryDeleteTempFile(tempPath);
            }
        }

        private static bool FileContentEquals(string path, byte[] bytes)
        {
            var buffer = new byte[8192];
            using (var stream = File.OpenRead(path))
            {
                for (var offset = 0; offset < bytes.Length;)
                {
                    var expected = Math.Min(buffer.Length, bytes.Length - offset);
                    var read = stream.Read(buffer, 0, expected);
                    if (read == 0)
                        return false;
                    for (var i = 0; i < read; i++)
                    {
                        if (buffer[i] != bytes[offset + i])
                            return false;
                    }
                    offset += read;
                }

                return stream.ReadByte() == -1;
            }
        }

        private static void ReplaceFile(string tempPath, string path)
        {
            if (!File.Exists(path))
            {
                File.Move(tempPath, path);
                return;
            }

            Exception replaceException = null;
            for (var attempt = 0; attempt < ReplaceAttempts; attempt++)
            {
                try
                {
                    ClearReadOnly(path);
                    File.Replace(tempPath, path, null);
                    return;
                }
                catch (PlatformNotSupportedException ex)
                {
                    replaceException = ex;
                    break;
                }
                catch (IOException ex)
                {
                    replaceException = ex;
                    DelayBeforeRetry(attempt);
                }
                catch (UnauthorizedAccessException ex)
                {
                    replaceException = ex;
                    DelayBeforeRetry(attempt);
                }
            }

            CopyTempOverDestination(tempPath, path, replaceException);
        }

        private static void CopyTempOverDestination(string tempPath, string path, Exception originalException)
        {
            Exception copyException = null;
            for (var attempt = 0; attempt < ReplaceAttempts; attempt++)
            {
                try
                {
                    ClearReadOnly(path);
                    File.Copy(tempPath, path, overwrite: true);
                    return;
                }
                catch (IOException ex)
                {
                    copyException = ex;
                    DelayBeforeRetry(attempt);
                }
                catch (UnauthorizedAccessException ex)
                {
                    copyException = ex;
                    DelayBeforeRetry(attempt);
                }
            }

            throw new IOException(
                "Failed to replace generated FoxRun schema info artifact '" + path + "'.",
                copyException ?? originalException);
        }

        private static void ClearReadOnly(string path)
        {
            if (!File.Exists(path))
                return;

            var attributes = File.GetAttributes(path);
            if ((attributes & FileAttributes.ReadOnly) != 0)
                File.SetAttributes(path, attributes & ~FileAttributes.ReadOnly);
        }

        private static void DelayBeforeRetry(int attempt)
        {
            // Build/Play-Mode hooks run on Unity's main thread. With two
            // generated files, the worst case is four 50 ms sleeps (200 ms).
            if (attempt + 1 < ReplaceAttempts)
                Thread.Sleep(ReplaceRetryDelayMilliseconds);
        }

        private static void TryDeleteTempFile(string tempPath)
        {
            try
            {
                if (File.Exists(tempPath))
                    File.Delete(tempPath);
            }
            catch (IOException)
            {
            }
            catch (UnauthorizedAccessException)
            {
            }
        }

        private static void AppendIndentedStringLiteralLine(StringBuilder sb, string innerIndent, string value, string suffix)
        {
            sb.Append(innerIndent).Append("    ");
            AppendStringLiteral(sb, value);
            sb.AppendLine(suffix);
        }

        private static void WriteStringArrayOrNull(
            StringBuilder sb,
            IReadOnlyList<string> values,
            int indentLevel,
            bool trailingComma)
        {
            var indent = Indent(indentLevel);
            if (values == null)
            {
                sb.AppendLine(indent + "null" + (trailingComma ? "," : string.Empty));
                return;
            }

            sb.AppendLine(indent + "new string[]");
            sb.AppendLine(indent + "{");
            foreach (var value in values)
                AppendIndentedStringLiteralLine(sb, indent, value, ",");
            sb.AppendLine(indent + "}" + (trailingComma ? "," : string.Empty));
        }

        private static void AppendStringLiteral(StringBuilder sb, string value)
        {
            value = value ?? string.Empty;
            sb.Append('"');
            foreach (var c in value)
            {
                switch (c)
                {
                    case '"': sb.Append("\\\""); break;
                    case '\\': sb.Append("\\\\"); break;
                    case '\b': sb.Append("\\b"); break;
                    case '\f': sb.Append("\\f"); break;
                    case '\n': sb.Append("\\n"); break;
                    case '\r': sb.Append("\\r"); break;
                    case '\t': sb.Append("\\t"); break;
                    default:
                        if (c < 0x20)
                            sb.Append("\\u").Append(((int)c).ToString("x4", CultureInfo.InvariantCulture));
                        else
                            sb.Append(c);
                        break;
                }
            }
            sb.Append('"');
        }

        private static string FloatLiteral(float value)
        {
            if (float.IsNaN(value) || float.IsInfinity(value))
                throw new ArgumentOutOfRangeException(nameof(value), value, "FoxRun policy float values must be finite.");
            // Match canonical manifest formatting so generated source is stable across runtimes.
            return value.ToString("G9", CultureInfo.InvariantCulture) + "f";
        }

        private static string BoolLiteral(bool value)
        {
            return value ? "true" : "false";
        }

        private static string Indent(int level)
        {
            return level >= 0 && level < Indents.Length
                ? Indents[level]
                : new string(' ', level * 4);
        }

        private static ManifestCounts CountManifest(FoxRunCanonicalManifest manifest)
        {
            var types = manifest.Sections.FoxRun.Types;
            var contractCount = 0;
            var fieldCount = 0;
            foreach (var type in types)
            {
                contractCount += type.Contracts.Count;
                foreach (var contract in type.Contracts)
                    fieldCount += contract.Fields.Count;
            }

            return new ManifestCounts(types.Count, contractCount, fieldCount);
        }

        private readonly struct ManifestCounts
        {
            public readonly int TypeCount;
            public readonly int ContractCount;
            public readonly int FieldCount;

            public ManifestCounts(int typeCount, int contractCount, int fieldCount)
            {
                TypeCount = typeCount;
                ContractCount = contractCount;
                FieldCount = fieldCount;
            }
        }

        private static string ExtractStringConstant(string source, string name)
        {
            var marker = "const string " + name + " = ";
            var start = source.IndexOf(marker, StringComparison.Ordinal);
            if (start < 0)
                return string.Empty;

            start = source.IndexOf('"', start + marker.Length);
            if (start < 0)
                return string.Empty;

            var sb = new StringBuilder();
            for (var i = start + 1; i < source.Length; i++)
            {
                var c = source[i];
                if (c == '"')
                    return sb.ToString();

                if (c != '\\')
                {
                    sb.Append(c);
                    continue;
                }

                if (++i >= source.Length)
                    return string.Empty;

                var escaped = source[i];
                switch (escaped)
                {
                    case '"': sb.Append('"'); break;
                    case '\\': sb.Append('\\'); break;
                    case 'b': sb.Append('\b'); break;
                    case 'f': sb.Append('\f'); break;
                    case 'n': sb.Append('\n'); break;
                    case 'r': sb.Append('\r'); break;
                    case 't': sb.Append('\t'); break;
                    case 'u':
                        if (i + 4 >= source.Length)
                            return string.Empty;
                        var hex = source.Substring(i + 1, 4);
                        if (!int.TryParse(hex, NumberStyles.HexNumber, CultureInfo.InvariantCulture, out var codePoint))
                            return string.Empty;
                        sb.Append((char)codePoint);
                        i += 4;
                        break;
                    default:
                        sb.Append(escaped);
                        break;
                }
            }

            return string.Empty;
        }

        private static int ExtractIntConstant(string source, string name)
        {
            var marker = "const int " + name + " = ";
            var start = source.IndexOf(marker, StringComparison.Ordinal);
            if (start < 0)
                return -1;

            start += marker.Length;
            var end = source.IndexOf(';', start);
            if (end < 0)
                return -1;

            return int.TryParse(source.Substring(start, end - start).Trim(), NumberStyles.Integer, CultureInfo.InvariantCulture, out var value)
                ? value
                : -1;
        }
    }

    public sealed class FoxRunSchemaInfoWriteResult
    {
        public FoxRunSchemaInfoVerification Verification { get; }
        public bool SourceChanged { get; }
        public bool MetaChanged { get; }
        public bool AnyChanged => SourceChanged || MetaChanged;

        public FoxRunSchemaInfoWriteResult(
            FoxRunSchemaInfoVerification verification,
            bool sourceChanged,
            bool metaChanged)
        {
            Verification = verification ?? throw new ArgumentNullException(nameof(verification));
            SourceChanged = sourceChanged;
            MetaChanged = metaChanged;
        }
    }

    public sealed class FoxRunSchemaInfoVerification
    {
        private readonly List<string> _errors = new List<string>();

        public string ExpectedGlobalManifestHash { get; }
        public string ActualGlobalManifestHash { get; }
        public string ExpectedFoxRunManifestHash { get; }
        public string ActualFoxRunManifestHash { get; }
        public int ExpectedTypeCount { get; }
        public int ActualTypeCount { get; }
        public int ExpectedContractCount { get; }
        public int ActualContractCount { get; }
        public int ExpectedFieldCount { get; }
        public int ActualFieldCount { get; }
        public IReadOnlyList<string> Errors => _errors.AsReadOnly();
        public bool IsValid => _errors.Count == 0;

        public FoxRunSchemaInfoVerification(
            string expectedGlobalManifestHash,
            string actualGlobalManifestHash,
            string expectedFoxRunManifestHash,
            string actualFoxRunManifestHash,
            int expectedTypeCount,
            int actualTypeCount,
            int expectedContractCount,
            int actualContractCount,
            int expectedFieldCount,
            int actualFieldCount)
        {
            ExpectedGlobalManifestHash = expectedGlobalManifestHash ?? string.Empty;
            ActualGlobalManifestHash = actualGlobalManifestHash ?? string.Empty;
            ExpectedFoxRunManifestHash = expectedFoxRunManifestHash ?? string.Empty;
            ActualFoxRunManifestHash = actualFoxRunManifestHash ?? string.Empty;
            ExpectedTypeCount = expectedTypeCount;
            ActualTypeCount = actualTypeCount;
            ExpectedContractCount = expectedContractCount;
            ActualContractCount = actualContractCount;
            ExpectedFieldCount = expectedFieldCount;
            ActualFieldCount = actualFieldCount;
        }

        public void AddError(string message)
        {
            if (!string.IsNullOrEmpty(message))
                _errors.Add(message);
        }
    }
}
