// Copyright (c) 2026 Jianbin Liu and Unity2Foxglove contributors.
// SPDX-License-Identifier: Apache-2.0
//
// Module: Editor/FoxRun
// Purpose: Scans assemblies for [FoxRun] attributed fields and generates
// IFoxgloveLogSource implementation .cs files for FoxgloveLogHub.

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using UnityEngine;

namespace Unity.FoxgloveSDK.Editor
{
    /// <summary>
    /// Generates real .g.cs files for [FoxRun] annotated classes.
    /// Used by IPreprocessBuildWithReport to produce IL2CPP-compatible source files.
    /// Shares code generation logic with FoxgloveLogSourceGenerator (Roslyn ISG).
    /// </summary>
    public static partial class FoxrunCodeGenerator
    {
        private static readonly UTF8Encoding Utf8NoBom = new UTF8Encoding(false);
        private const int ReplaceAttempts = 3;
        private const int ReplaceRetryDelayMilliseconds = 50;

        public sealed class FoxRunManifestRefreshResult
        {
            public FoxRunCanonicalManifest Manifest { get; }
            public FoxRunSchemaInfoWriteResult SchemaInfo { get; }
            public bool SchemaInfoChanged => SchemaInfo.AnyChanged;

            public FoxRunManifestRefreshResult(
                FoxRunCanonicalManifest manifest,
                FoxRunSchemaInfoWriteResult schemaInfo)
            {
                // Refresh results are immutable and never expose null manifest or schema evidence.
                Manifest = manifest ?? throw new ArgumentNullException(nameof(manifest));
                SchemaInfo = schemaInfo ?? throw new ArgumentNullException(nameof(schemaInfo));
            }
        }

        /// <summary>
        /// Collect the types that GenerateSourceFiles would process, without writing files.
        /// Returns a list of (assemblyName, namespace, className) tuples for IL2CPP preservation.
        /// </summary>
        public static List<(string AsmName, string Ns, string ClassName)> CollectFoxRunTypes()
        {
            var types = new List<(string, string, string)>();
            foreach (var asm in AppDomain.CurrentDomain.GetAssemblies())
            {
                try
                {
                    foreach (var type in asm.GetTypes())
                    {
                        if (!type.IsClass || type.IsAbstract) continue;
                        if (!AssumePartialWasEnforcedBySourceGenerator(type)) continue;
                        if (!typeof(MonoBehaviour).IsAssignableFrom(type)) continue;
                        var members = ScanType(type);
                        if (members.Count == 0) continue;
                        types.Add((asm.GetName().Name, type.Namespace ?? "", type.Name));
                    }
                }
                catch (ReflectionTypeLoadException ex)
                {
                    throw new InvalidOperationException(
                        $"Failed to scan assembly '{asm.GetName().Name}' for [FoxRun] types.", ex);
                }
            }
            return types;
        }

        /// <summary>
        /// Generate an IL2CPP link.xml snippet that preserves FoxRun user types
        /// discovered by CollectFoxRunTypes. Returns the XML string.
        /// </summary>
        public static string EmitLinkXml(List<(string AsmName, string Ns, string ClassName)> types)
        {
            var sb = new StringBuilder();
            sb.AppendLine("<?xml version=\"1.0\" encoding=\"utf-8\"?>");
            sb.AppendLine("<!-- Generated by FoxrunBuildPreprocess - do not edit by hand. -->");
            sb.AppendLine("<linker>");
            foreach (var group in types
                         .GroupBy(t => t.AsmName, StringComparer.Ordinal)
                         .OrderBy(group => group.Key, StringComparer.Ordinal))
            {
                sb.AppendLine($"  <assembly fullname=\"{group.Key}\">");
                var seen = new HashSet<string>(StringComparer.Ordinal);
                foreach (var type in group.OrderBy(t => string.IsNullOrEmpty(t.Ns) ? t.ClassName : $"{t.Ns}.{t.ClassName}", StringComparer.Ordinal))
                {
                    var full = string.IsNullOrEmpty(type.Ns) ? type.ClassName : $"{type.Ns}.{type.ClassName}";
                    if (!seen.Add(full)) continue;
                    sb.AppendLine($"    <type fullname=\"{full}\" preserve=\"all\" />");
                }
                sb.AppendLine($"  </assembly>");
            }
            sb.AppendLine("</linker>");
            return sb.ToString();
        }

        /// <summary>
        /// Scan all loaded assemblies for [FoxRun] fields/properties on partial classes,
        /// and generate _FoxRun.g.cs files under Assets/Scripts/Generated/.
        /// Returns the list of generated file paths.
        /// Files are only written if content differs from existing file (prevents recompile loop).
        /// </summary>
        public static List<string> GenerateSourceFiles()
        {
            return GenerateSourceFiles(out _);
        }

        public static List<string> GenerateSourceFiles(out FoxRunCanonicalManifest manifest)
        {
            return GenerateSourceFiles(out manifest, out _);
        }

        public static List<string> GenerateSourceFiles(
            out FoxRunCanonicalManifest manifest,
            out List<(string AsmName, string Ns, string ClassName)> foxRunTypes)
        {
            var result = new List<string>();
            var editorScan = ScanFoxRunMembersAndServices(ignoreReflectionTypeLoadExceptions: true);
            var scan = editorScan.FoxRun;
            var serviceScan = editorScan.Services;
            foxRunTypes = editorScan.FoxRunTypes;
            var byClass = scan.ByClass;
            var model = LowerReflectionMembers(scan.ReflectionMembers);
            ValidateGenerationModel(model);
            var outputDirectory = Path.Combine(Application.dataPath, "Scripts/Generated");

            if (byClass.Count > 0 || serviceScan.ByClass.Count > 0)
            {
                Directory.CreateDirectory(outputDirectory);

                foreach (var type in model.Types)
                {
                    var kv = (Key: (Ns: type.Namespace, ClassName: type.ClassName), Value: type);
                    var source = EmitSourceFile(kv.Value);
                    var fileName = FoxgloveSourceEmitter.GeneratedSourceName(kv.Key.Ns, kv.Key.ClassName);
                    var absolutePath = Path.Combine(outputDirectory, fileName);
                    var sourceBytes = Utf8NoBom.GetBytes(source);

                    if (WriteSourceFileIfChanged(absolutePath, sourceBytes))
                    {
                        Debug.Log($"[FoxrunCodeGenerator] Generated {fileName}");
                    }

                    result.Add(fileName);
                }

                foreach (var kv in serviceScan.ByClass
                             .OrderBy(item => string.IsNullOrEmpty(item.Key.Ns) ? item.Key.ClassName : item.Key.Ns + "." + item.Key.ClassName, StringComparer.Ordinal))
                {
                    var source = EmitServiceSourceFile(kv.Key.Ns, kv.Key.ClassName, kv.Value);
                    var fileName = FoxServiceSourceEmitter.GeneratedSourceName(kv.Key.Ns, kv.Key.ClassName);
                    var absolutePath = Path.Combine(outputDirectory, fileName);
                    var sourceBytes = Utf8NoBom.GetBytes(source);

                    if (WriteSourceFileIfChanged(absolutePath, sourceBytes))
                    {
                        Debug.Log($"[FoxrunCodeGenerator] Generated {fileName}");
                    }

                    result.Add(fileName);
                }
            }

            var deleted = FoxRunGeneratedSourceReconciler.ReconcileGeneratedSourceFiles(outputDirectory, result);
            if (deleted.Count > 0)
                Debug.Log("[FoxrunCodeGenerator] Removed stale generated file(s): " + string.Join(", ", deleted));

            manifest = WriteManifestFiles(scan.ManifestMembers);
            WriteSchemaInfoFiles(manifest);
            WriteDescriptorFile(model);

            return result;
        }

        /// <summary>
        /// Refresh canonical FoxRun manifest artifacts, generated runtime
        /// schema info, and generation descriptor evidence without writing
        /// physical Player publisher fallback files.
        /// </summary>
        public static FoxRunCanonicalManifest GenerateManifestFilesOnly()
        {
            return GenerateManifestFilesOnlyWithResult().Manifest;
        }

        public static FoxRunManifestRefreshResult GenerateManifestFilesOnlyWithResult()
        {
            return GenerateManifestAndSchemaInfoFilesOnlyWithResult();
        }

        /// <summary>
        /// Refresh canonical FoxRun manifest artifacts and generated runtime
        /// schema info under the configured schema evidence root. This is used by Editor
        /// Play Mode so local contract evidence is current without writing
        /// physical _FoxRun.g.cs Player fallback source files.
        /// </summary>
        public static FoxRunCanonicalManifest GenerateManifestAndSchemaInfoFilesOnly()
        {
            return GenerateManifestAndSchemaInfoFilesOnlyWithResult().Manifest;
        }

        public static FoxRunManifestRefreshResult GenerateManifestAndSchemaInfoFilesOnlyWithResult()
        {
            var scan = ScanFoxRunMembers(ignoreReflectionTypeLoadExceptions: true);
            var model = LowerReflectionMembers(scan.ReflectionMembers);
            ValidateGenerationModel(model);
            var manifest = WriteManifestFiles(scan.ManifestMembers);
            var schemaInfo = WriteSchemaInfoFiles(manifest);
            WriteDescriptorFile(model);
            return new FoxRunManifestRefreshResult(manifest, schemaInfo);
        }

        public static IReadOnlyList<FoxRunManifestMember> CollectManifestMembers()
        {
            return ScanFoxRunMembers(ignoreReflectionTypeLoadExceptions: false).ManifestMembers;
        }

        public static FoxRunSchemaInfoVerification VerifyGeneratedSchemaInfoFiles()
        {
            var scan = ScanFoxRunMembers(ignoreReflectionTypeLoadExceptions: true);
            var manifest = FoxRunManifestBuilder.Build(scan.ManifestMembers);
            return VerifyGeneratedSchemaInfoFiles(manifest);
        }

        public static FoxRunSchemaInfoVerification VerifyGeneratedSchemaInfoFiles(FoxRunCanonicalManifest manifest)
        {
            if (manifest == null)
                throw new ArgumentNullException(nameof(manifest));

            var sourcePath = Path.Combine(GetManifestOutputDirectory(), FoxRunSchemaInfoWriter.SchemaInfoFileName);
            if (!File.Exists(sourcePath))
                throw new InvalidOperationException("Missing generated FoxRun schema info: " + sourcePath);

            var verification = FoxRunSchemaInfoWriter.VerifyGeneratedInfo(manifest, File.ReadAllText(sourcePath));
            if (!verification.IsValid)
                throw new InvalidOperationException(string.Join("; ", verification.Errors));
            return verification;
        }

        private static FoxRunCanonicalManifest WriteManifestFiles(IReadOnlyList<FoxRunManifestMember> members)
        {
            return FoxrunManifestWriter.WriteManifestFiles(
                GetManifestOutputDirectory(),
                members);
        }

        private static FoxRunSchemaInfoWriteResult WriteSchemaInfoFiles(FoxRunCanonicalManifest manifest)
        {
            return FoxRunSchemaInfoWriter.WriteGeneratedInfoFilesWithResult(GetManifestOutputDirectory(), manifest);
        }

        private static void WriteDescriptorFile(FoxRunGenerationModel model)
        {
            var outputDirectory = GetManifestOutputDirectory();
            Directory.CreateDirectory(outputDirectory);
            var path = Path.Combine(outputDirectory, FoxRunGenerationDescriptorConstants.DescriptorFileName);
            WriteTextFileIfChanged(path, FoxRunGenerationDescriptorJsonWriter.Write(model));
        }

        private static FoxRunGenerationModel LowerReflectionMembers(IReadOnlyList<FoxRunReflectionGenerationMember> members)
        {
            return FoxRunReflectionGenerationModelLowerer.Lower(members);
        }

        private static void ValidateGenerationModel(FoxRunGenerationModel model)
        {
            var diagnostics = FoxRunGenerationModelValidator.Validate(model);
            var errors = new List<string>();
            foreach (var diagnostic in diagnostics)
            {
                if (string.Equals(diagnostic.Severity, "Error", StringComparison.Ordinal))
                    errors.Add(diagnostic.Id + ": " + diagnostic.Target + ": " + diagnostic.Message);
                else if (string.Equals(diagnostic.Severity, "Warning", StringComparison.Ordinal))
                    Debug.LogWarning("[FoxrunCodeGenerator] " + diagnostic.Id + ": " + diagnostic.Target + ": " + diagnostic.Message);
            }

            if (errors.Count > 0)
                throw new InvalidOperationException(string.Join("; ", errors));
        }

        private static string GetManifestOutputDirectory()
        {
            return Unity2FoxgloveSchemaEvidencePaths.ResolveFoxRunOutputDirectory();
        }

        /// <summary>
        /// Generate a complete .g.cs source file string for a single class.
        /// Delegates to <c>FoxgloveSourceEmitter.EmitClass</c> for output
        /// consistency with the Roslyn ISG path.
        /// </summary>
        public static string EmitSourceFile(MemberData[] members)
        {
            if (members == null)
                throw new ArgumentNullException(nameof(members));
            if (members.Length == 0)
                throw new ArgumentException("At least one FoxRun member is required to emit a source file.", nameof(members));

            var reflectionMembers = new FoxRunReflectionGenerationMember[members.Length];
            for (var i = 0; i < members.Length; i++)
                reflectionMembers[i] = members[i].ToReflectionMember();

            var model = LowerReflectionMembers(reflectionMembers);
            ValidateGenerationModel(model);
            if (model.Types.Count != 1)
                throw new ArgumentException("Members must describe exactly one FoxRun declaring type.", nameof(members));

            return EmitSourceFile(model.Types[0]);
        }

        public static string EmitSourceFile(FoxRunGenerationType type)
        {
            var core = FoxgloveSourceEmitter.EmitClass(type);

            // Wrap with a Player-only guard so Editor compilation uses the Roslyn
            // generated in-memory source and Player builds use the physical file.
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("// Copyright (c) 2026 Jianbin Liu and Unity2Foxglove contributors.");
            sb.AppendLine("// SPDX-License-Identifier: Apache-2.0");
            sb.AppendLine("// " + FoxRunGeneratedSourceReconciler.GeneratedSourceSentinel);
            sb.AppendLine("// In the Unity Editor, the Roslyn analyzer already generates this partial type in memory.");
            sb.AppendLine("#if !UNITY_EDITOR");
            sb.Append(core);
            sb.AppendLine("#endif");
            return sb.ToString();
        }

        public static string EmitServiceSourceFile(
            string ns,
            string className,
            IReadOnlyList<FoxServiceSourceEmitter.ServiceMethod> methods)
        {
            if (methods == null || methods.Count == 0)
                throw new ArgumentException("At least one FoxService method is required to emit a source file.", nameof(methods));

            var core = FoxServiceSourceEmitter.EmitClass(ns, className, methods);
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("// Copyright (c) 2026 Jianbin Liu and Unity2Foxglove contributors.");
            sb.AppendLine("// SPDX-License-Identifier: Apache-2.0");
            sb.AppendLine("// " + FoxRunGeneratedSourceReconciler.GeneratedSourceSentinel);
            sb.AppendLine("// In the Unity Editor, the Roslyn analyzer already generates this partial type in memory.");
            sb.AppendLine("#if !UNITY_EDITOR");
            sb.Append(core);
            sb.AppendLine("#endif");
            return sb.ToString();
        }

        private static bool WriteSourceFileIfChanged(string path, byte[] bytes)
        {
            if (File.Exists(path))
            {
                var existing = new FileInfo(path);
                if (existing.Length == bytes.Length && FileContentEquals(path, bytes))
                    return false;
            }

            WriteBytesWithTempReplace(path, bytes);
            return true;
        }

        private static void WriteTextFileIfChanged(string path, string text)
        {
            WriteSourceFileIfChanged(path, Utf8NoBom.GetBytes(text ?? string.Empty));
        }

        private static bool FileContentEquals(string path, byte[] bytes)
        {
            var buffer = new byte[8192];
            using (var stream = File.OpenRead(path))
            {
                for (var offset = 0; offset < bytes.Length;)
                {
                    var expected = Math.Min(buffer.Length, bytes.Length - offset);
                    var read = stream.Read(buffer, 0, expected);
                    if (read == 0)
                        return false;
                    for (var i = 0; i < read; i++)
                    {
                        if (buffer[i] != bytes[offset + i])
                            return false;
                    }
                    offset += read;
                }

                return stream.ReadByte() == -1;
            }
        }

        private static void WriteBytesWithTempReplace(string path, byte[] bytes)
        {
            var directory = Path.GetDirectoryName(path);
            if (!string.IsNullOrEmpty(directory))
                Directory.CreateDirectory(directory);
            var tempPath = path + ".tmp";
            File.WriteAllBytes(tempPath, bytes ?? Array.Empty<byte>());

            for (var attempt = 1; ; attempt++)
            {
                try
                {
                    if (File.Exists(path))
                        File.Replace(tempPath, path, null);
                    else
                        File.Move(tempPath, path);
                    return;
                }
                catch when (attempt < ReplaceAttempts)
                {
                    Debug.LogWarning(
                        "[FoxrunCodeGenerator] Retrying generated file replace for "
                        + path
                        + " after transient IO failure.");
                    System.Threading.Thread.Sleep(ReplaceRetryDelayMilliseconds);
                }
                catch
                {
                    TryDeleteTempFile(tempPath);
                    throw;
                }
            }
        }

        private static void TryDeleteTempFile(string path)
        {
            try
            {
                if (File.Exists(path))
                    File.Delete(path);
            }
            catch
            {
                // Preserve the original write failure.
            }
        }
    }
}
