// Copyright (c) 2026 Jianbin Liu and Unity2Foxglove contributors.
// SPDX-License-Identifier: Apache-2.0
//
// Module: Editor/FoxRun
// Purpose: Scans assemblies for [FoxRun] attributed fields and generates
// IFoxgloveLogSource implementation .cs files for FoxgloveLogHub.

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Text;
using Unity.FoxgloveSDK.Components;
using UnityEngine;

namespace Unity.FoxgloveSDK.Editor
{
    /// <summary>
    /// Generates real .g.cs files for [FoxRun] annotated classes.
    /// Used by IPreprocessBuildWithReport to produce IL2CPP-compatible source files.
    /// Shares code generation logic with FoxgloveLogSourceGenerator (Roslyn ISG).
    /// </summary>
    public static class FoxrunCodeGenerator
    {
        private static readonly UTF8Encoding Utf8NoBom = new UTF8Encoding(false);
        private const int ReplaceAttempts = 3;
        private const int ReplaceRetryDelayMilliseconds = 50;

        /// <summary>
        /// Collect the types that GenerateSourceFiles would process, without writing files.
        /// Returns a list of (assemblyName, namespace, className) tuples for IL2CPP preservation.
        /// </summary>
        public static List<(string AsmName, string Ns, string ClassName)> CollectFoxRunTypes()
        {
            var types = new List<(string, string, string)>();
            foreach (var asm in AppDomain.CurrentDomain.GetAssemblies())
            {
                try
                {
                    foreach (var type in asm.GetTypes())
                    {
                        if (!type.IsClass || type.IsAbstract) continue;
                        if (!IsPartial(type)) continue;
                        if (!typeof(MonoBehaviour).IsAssignableFrom(type)) continue;
                        var members = ScanType(type);
                        if (members.Count == 0) continue;
                        types.Add((asm.GetName().Name, type.Namespace ?? "", type.Name));
                    }
                }
                catch (ReflectionTypeLoadException ex)
                {
                    throw new InvalidOperationException(
                        $"Failed to scan assembly '{asm.GetName().Name}' for [FoxRun] types.", ex);
                }
            }
            return types;
        }

        /// <summary>
        /// Generate an IL2CPP link.xml snippet that preserves FoxRun user types
        /// discovered by CollectFoxRunTypes. Returns the XML string.
        /// </summary>
        public static string EmitLinkXml(List<(string AsmName, string Ns, string ClassName)> types)
        {
            var sb = new StringBuilder();
            sb.AppendLine("<?xml version=\"1.0\" encoding=\"utf-8\"?>");
            sb.AppendLine("<!-- Generated by FoxrunBuildPreprocess - do not edit by hand. -->");
            sb.AppendLine("<linker>");
            foreach (var group in types
                         .GroupBy(t => t.AsmName, StringComparer.Ordinal)
                         .OrderBy(group => group.Key, StringComparer.Ordinal))
            {
                sb.AppendLine($"  <assembly fullname=\"{group.Key}\">");
                var seen = new HashSet<string>(StringComparer.Ordinal);
                foreach (var type in group.OrderBy(t => string.IsNullOrEmpty(t.Ns) ? t.ClassName : $"{t.Ns}.{t.ClassName}", StringComparer.Ordinal))
                {
                    var full = string.IsNullOrEmpty(type.Ns) ? type.ClassName : $"{type.Ns}.{type.ClassName}";
                    if (!seen.Add(full)) continue;
                    sb.AppendLine($"    <type fullname=\"{full}\" preserve=\"all\" />");
                }
                sb.AppendLine($"  </assembly>");
            }
            sb.AppendLine("</linker>");
            return sb.ToString();
        }

        /// <summary>
        /// Scan all loaded assemblies for [FoxRun] fields/properties on partial classes,
        /// and generate _FoxRun.g.cs files under Assets/Scripts/Generated/.
        /// Returns the list of generated file paths.
        /// Files are only written if content differs from existing file (prevents recompile loop).
        /// </summary>
        public static List<string> GenerateSourceFiles()
        {
            return GenerateSourceFiles(out _);
        }

        public static List<string> GenerateSourceFiles(out FoxRunCanonicalManifest manifest)
        {
            var result = new List<string>();
            var scan = ScanFoxRunMembers(ignoreReflectionTypeLoadExceptions: true);
            var serviceScan = ScanFoxServiceMethods(ignoreReflectionTypeLoadExceptions: true);
            var byClass = scan.ByClass;
            var model = LowerReflectionMembers(scan.ReflectionMembers);
            ValidateGenerationModel(model);
            var outputDirectory = Path.Combine(Application.dataPath, "Scripts/Generated");

            if (byClass.Count > 0 || serviceScan.ByClass.Count > 0)
            {
                Directory.CreateDirectory(outputDirectory);

                foreach (var type in model.Types)
                {
                    var kv = (Key: (Ns: type.Namespace, ClassName: type.ClassName), Value: type);
                    var source = EmitSourceFile(kv.Value);
                    var fileName = FoxgloveSourceEmitter.GeneratedSourceName(kv.Key.Ns, kv.Key.ClassName);
                    var absolutePath = Path.Combine(outputDirectory, fileName);
                    var sourceBytes = Utf8NoBom.GetBytes(source);

                    if (WriteSourceFileIfChanged(absolutePath, sourceBytes))
                    {
                        Debug.Log($"[FoxrunCodeGenerator] Generated {fileName}");
                    }

                    result.Add(fileName);
                }

                foreach (var kv in serviceScan.ByClass
                             .OrderBy(item => string.IsNullOrEmpty(item.Key.Ns) ? item.Key.ClassName : item.Key.Ns + "." + item.Key.ClassName, StringComparer.Ordinal))
                {
                    var source = EmitServiceSourceFile(kv.Key.Ns, kv.Key.ClassName, kv.Value);
                    var fileName = FoxServiceSourceEmitter.GeneratedSourceName(kv.Key.Ns, kv.Key.ClassName);
                    var absolutePath = Path.Combine(outputDirectory, fileName);
                    var sourceBytes = Utf8NoBom.GetBytes(source);

                    if (WriteSourceFileIfChanged(absolutePath, sourceBytes))
                    {
                        Debug.Log($"[FoxrunCodeGenerator] Generated {fileName}");
                    }

                    result.Add(fileName);
                }
            }

            var deleted = FoxRunGeneratedSourceReconciler.ReconcileGeneratedSourceFiles(outputDirectory, result);
            if (deleted.Count > 0)
                Debug.Log("[FoxrunCodeGenerator] Removed stale generated file(s): " + string.Join(", ", deleted));

            manifest = WriteManifestFiles(scan.ManifestMembers);
            WriteSchemaInfoFiles(manifest);
            WriteDescriptorFile(model);

            return result;
        }

        /// <summary>
        /// Refresh canonical FoxRun manifest artifacts, generated runtime
        /// schema info, and generation descriptor evidence without writing
        /// physical Player publisher fallback files.
        /// </summary>
        public static FoxRunCanonicalManifest GenerateManifestFilesOnly()
        {
            return GenerateManifestAndSchemaInfoFilesOnly();
        }

        /// <summary>
        /// Refresh canonical FoxRun manifest artifacts and generated runtime
        /// schema info under the configured schema evidence root. This is used by Editor
        /// Play Mode so local contract evidence is current without writing
        /// physical _FoxRun.g.cs Player fallback source files.
        /// </summary>
        public static FoxRunCanonicalManifest GenerateManifestAndSchemaInfoFilesOnly()
        {
            var scan = ScanFoxRunMembers(ignoreReflectionTypeLoadExceptions: true);
            var model = LowerReflectionMembers(scan.ReflectionMembers);
            ValidateGenerationModel(model);
            var manifest = WriteManifestFiles(scan.ManifestMembers);
            WriteSchemaInfoFiles(manifest);
            WriteDescriptorFile(model);
            return manifest;
        }

        public static IReadOnlyList<FoxRunManifestMember> CollectManifestMembers()
        {
            return ScanFoxRunMembers(ignoreReflectionTypeLoadExceptions: false).ManifestMembers;
        }

        public static FoxRunSchemaInfoVerification VerifyGeneratedSchemaInfoFiles()
        {
            var scan = ScanFoxRunMembers(ignoreReflectionTypeLoadExceptions: true);
            var manifest = FoxRunManifestBuilder.Build(scan.ManifestMembers);
            return VerifyGeneratedSchemaInfoFiles(manifest);
        }

        public static FoxRunSchemaInfoVerification VerifyGeneratedSchemaInfoFiles(FoxRunCanonicalManifest manifest)
        {
            if (manifest == null)
                throw new ArgumentNullException(nameof(manifest));

            var sourcePath = Path.Combine(GetManifestOutputDirectory(), FoxRunSchemaInfoWriter.SchemaInfoFileName);
            if (!File.Exists(sourcePath))
                throw new InvalidOperationException("Missing generated FoxRun schema info: " + sourcePath);

            var verification = FoxRunSchemaInfoWriter.VerifyGeneratedInfo(manifest, File.ReadAllText(sourcePath));
            if (!verification.IsValid)
                throw new InvalidOperationException(string.Join("; ", verification.Errors));
            return verification;
        }

        private static FoxRunCanonicalManifest WriteManifestFiles(IReadOnlyList<FoxRunManifestMember> members)
        {
            return FoxrunManifestWriter.WriteManifestFiles(
                GetManifestOutputDirectory(),
                members);
        }

        private static FoxRunSchemaInfoVerification WriteSchemaInfoFiles(FoxRunCanonicalManifest manifest)
        {
            return FoxRunSchemaInfoWriter.WriteGeneratedInfoFiles(GetManifestOutputDirectory(), manifest);
        }

        private static void WriteDescriptorFile(FoxRunGenerationModel model)
        {
            var outputDirectory = GetManifestOutputDirectory();
            Directory.CreateDirectory(outputDirectory);
            var path = Path.Combine(outputDirectory, FoxRunGenerationDescriptorConstants.DescriptorFileName);
            WriteTextFileIfChanged(path, FoxRunGenerationDescriptorJsonWriter.Write(model));
        }

        private static FoxRunGenerationModel LowerReflectionMembers(IReadOnlyList<FoxRunReflectionGenerationMember> members)
        {
            return FoxRunReflectionGenerationModelLowerer.Lower(members);
        }

        private static void ValidateGenerationModel(FoxRunGenerationModel model)
        {
            var diagnostics = FoxRunGenerationModelValidator.Validate(model);
            var errors = new List<string>();
            foreach (var diagnostic in diagnostics)
            {
                if (string.Equals(diagnostic.Severity, "Error", StringComparison.Ordinal))
                    errors.Add(diagnostic.Id + ": " + diagnostic.Target + ": " + diagnostic.Message);
                else if (string.Equals(diagnostic.Severity, "Warning", StringComparison.Ordinal))
                    Debug.LogWarning("[FoxrunCodeGenerator] " + diagnostic.Id + ": " + diagnostic.Target + ": " + diagnostic.Message);
            }

            if (errors.Count > 0)
                throw new InvalidOperationException(string.Join("; ", errors));
        }

        private static string GetManifestOutputDirectory()
        {
            return Unity2FoxgloveSchemaEvidencePaths.ResolveFoxRunOutputDirectory();
        }

        private static FoxRunScanResult ScanFoxRunMembers(bool ignoreReflectionTypeLoadExceptions)
        {
            var byClass = new Dictionary<(string Ns, string ClassName), List<MemberData>>();
            var manifestMembers = new List<FoxRunManifestMember>();
            var reflectionMembers = new List<FoxRunReflectionGenerationMember>();

            foreach (var asm in AppDomain.CurrentDomain.GetAssemblies())
            {
                try
                {
                    foreach (var type in asm.GetTypes())
                    {
                        if (!type.IsClass || type.IsAbstract) continue;
                        if (!IsPartial(type)) continue;
                        if (!typeof(MonoBehaviour).IsAssignableFrom(type)) continue;

                        var members = ScanType(type);
                        if (members.Count == 0) continue;

                        var ns = type.Namespace ?? "";
                        var key = (ns, type.Name);
                        if (!byClass.TryGetValue(key, out var list))
                            byClass[key] = list = new List<MemberData>();

                        foreach (var member in members)
                        {
                            list.Add(member);
                            manifestMembers.Add(member.ToManifestMember());
                            reflectionMembers.Add(member.ToReflectionMember());
                        }
                    }
                }
                catch (ReflectionTypeLoadException ex)
                {
                    if (!ignoreReflectionTypeLoadExceptions)
                        throw;
                    WarnSkippedAssembly(asm, ex);
                    // Source fallback generation is best-effort because the Roslyn
                    // path already reports authoring errors in the Editor. The
                    // link.xml scan is fail-fast and catches preservation risk.
                }
            }

            return new FoxRunScanResult(byClass, manifestMembers, reflectionMembers);
        }

        /// <summary>
        /// Checks whether a type was declared <c>partial</c>.
        /// <para>Runtime detection is not possible because the CLR erases partial
        /// metadata. The build pipeline assumes every <c>MonoBehaviour</c> with
        /// <c>[FoxRun]</c> members was declared partial; the Roslyn ISG enforces this
        /// at Editor compile time via FOXRUN001.</para>
        /// </summary>
        static bool IsPartial(Type type)
        {
            // Partial classes in C# have no runtime metadata at the type level.
            // We detect by checking if the generated members (via ISG) would create
            // a partial extension. For the build step, we assume any MonoBehaviour
            // with [FoxRun] members was declared partial in source.
            // If the class was NOT partial, ISG would have emitted FOXRUN001 at Editor compile time,
            // so this is a safe assumption for Player builds.
            return true;
        }

        /// <summary>
        /// Reflects over all instance fields and properties (public and non-public,
        /// declared only) on the given type and collects <c>[FoxRun]</c> attributed
        /// members as <c>MemberData</c> entries.
        /// </summary>
        static List<MemberData> ScanType(Type type)
        {
            var result = new List<MemberData>();
            var flags = BindingFlags.Instance | BindingFlags.NonPublic | BindingFlags.Public | BindingFlags.DeclaredOnly;
            var ns = type.Namespace ?? "";
            var cn = type.Name;

            foreach (var fi in type.GetFields(flags))
            {
                var attrs = fi.GetCustomAttributes<FoxRunAttribute>();
                foreach (var a in attrs)
                {
                    result.Add(new MemberData(
                        fi.Name, fi.FieldType, "field", ns, cn, a.Topic, a.RateHz, a.SchemaName ?? "",
                        (int)a.PublishMode, a.ChangeEpsilon, a.ForceIntervalSeconds, fi.MetadataToken, "",
                        a.When, a.Unless));
                }
            }
            foreach (var pi in type.GetProperties(flags))
            {
                var attrs = pi.GetCustomAttributes<FoxRunAttribute>();
                foreach (var a in attrs)
                {
                    result.Add(new MemberData(
                        pi.Name, pi.PropertyType, "property", ns, cn, a.Topic, a.RateHz, a.SchemaName ?? "",
                        (int)a.PublishMode, a.ChangeEpsilon, a.ForceIntervalSeconds, pi.MetadataToken, "",
                        a.When, a.Unless));
                }
            }
            return result;
        }

        private static FoxServiceScanResult ScanFoxServiceMethods(bool ignoreReflectionTypeLoadExceptions)
        {
            var entries = new List<FoxServiceScanEntry>();

            foreach (var asm in AppDomain.CurrentDomain.GetAssemblies())
            {
                try
                {
                    foreach (var type in asm.GetTypes())
                    {
                        if (!type.IsClass || type.IsAbstract) continue;
                        if (!IsPartial(type)) continue;
                        if (!typeof(MonoBehaviour).IsAssignableFrom(type)) continue;

                        var methods = ScanServiceType(type);
                        if (methods.Count == 0) continue;

                        var ns = type.Namespace ?? "";
                        var key = (ns, type.Name);
                        var owner = string.IsNullOrEmpty(ns) ? type.Name : ns + "." + type.Name;

                        foreach (var method in methods)
                            entries.Add(new FoxServiceScanEntry(key, owner, method));
                    }
                }
                catch (ReflectionTypeLoadException ex)
                {
                    if (!ignoreReflectionTypeLoadExceptions)
                        throw;
                    WarnSkippedAssembly(asm, ex);
                }
            }

            var duplicateNames = new HashSet<string>(StringComparer.Ordinal);
            foreach (var group in entries.GroupBy(entry => entry.Method.ServiceName, StringComparer.Ordinal))
            {
                if (group.Count() <= 1)
                    continue;

                duplicateNames.Add(group.Key);
                var owners = string.Join(", ", group.Select(entry => entry.Owner).Distinct(StringComparer.Ordinal).OrderBy(value => value, StringComparer.Ordinal).ToArray());
                Debug.LogError("[FoxrunCodeGenerator] FOXSERVICE005: duplicate service name '" + group.Key + "' on " + owners + "; skipping duplicate generated service wrappers.");
            }

            var byClass = new Dictionary<(string Ns, string ClassName), List<FoxServiceSourceEmitter.ServiceMethod>>();
            foreach (var entry in entries
                         .Where(entry => !duplicateNames.Contains(entry.Method.ServiceName))
                         .OrderBy(entry => entry.Method.ServiceName, StringComparer.Ordinal))
            {
                if (!byClass.TryGetValue(entry.Key, out var list))
                    byClass[entry.Key] = list = new List<FoxServiceSourceEmitter.ServiceMethod>();
                list.Add(entry.Method);
            }

            return new FoxServiceScanResult(byClass);
        }

        private static List<FoxServiceSourceEmitter.ServiceMethod> ScanServiceType(Type type)
        {
            var result = new List<FoxServiceSourceEmitter.ServiceMethod>();
            var seenNames = new HashSet<string>(StringComparer.Ordinal);
            var flags = BindingFlags.Instance | BindingFlags.NonPublic | BindingFlags.Public | BindingFlags.DeclaredOnly;
            var ns = type.Namespace ?? "";
            var className = type.Name;

            foreach (var method in type.GetMethods(flags))
            {
                if (method.IsSpecialName)
                    continue;

                var attrs = method.GetCustomAttributes<FoxServiceAttribute>();
                foreach (var attr in attrs)
                {
                    var target = (string.IsNullOrEmpty(ns) ? className : ns + "." + className) + "." + method.Name;
                    ValidateServiceMethod(target, method, attr, seenNames);

                    var parameters = method.GetParameters();
                    var hasRequest = parameters.Length == 1;
                    var requestType = hasRequest ? parameters[0].ParameterType : null;
                    var responseType = method.ReturnType;
                    var hasResponse = responseType != typeof(void);
                    var serviceType = string.IsNullOrWhiteSpace(attr.Type)
                        ? target
                        : attr.Type;
                    var requestSchemaName = string.IsNullOrWhiteSpace(attr.RequestSchemaName)
                        ? (hasRequest ? SchemaNameFromType(requestType) : serviceType + ".Request")
                        : attr.RequestSchemaName;
                    var responseSchemaName = string.IsNullOrWhiteSpace(attr.ResponseSchemaName)
                        ? (hasResponse ? SchemaNameFromType(responseType) : serviceType + ".Response")
                        : attr.ResponseSchemaName;
                    var requestSchema = FoxServiceSchemaEmitter.Emit(FoxServiceSchemaReflectionBuilder.Build(requestType, FoxServiceDtoRules.RequestSide));
                    var responseSchema = FoxServiceSchemaEmitter.Emit(FoxServiceSchemaReflectionBuilder.Build(hasResponse ? responseType : null, FoxServiceDtoRules.ResponseSide));

                    if (string.IsNullOrWhiteSpace(attr.Type)
                        || string.IsNullOrWhiteSpace(attr.RequestSchemaName)
                        || string.IsNullOrWhiteSpace(attr.ResponseSchemaName))
                        Debug.LogWarning("[FoxrunCodeGenerator] FOXSERVICE006: " + target + ": missing service type or schema metadata; generated defaults will be used.");

                    result.Add(new FoxServiceSourceEmitter.ServiceMethod(
                        method.Name,
                        attr.Name,
                        serviceType,
                        attr.Description,
                        requestSchemaName,
                        responseSchemaName,
                        requestSchema,
                        responseSchema,
                        hasRequest ? FoxRunEmissionTypeNameFormatter.FromReflectionType(requestType) : string.Empty,
                        hasResponse ? FoxRunEmissionTypeNameFormatter.FromReflectionType(responseType) : string.Empty,
                        hasRequest,
                        hasResponse));
                }
            }

            return result;
        }

        private static void ValidateServiceMethod(
            string target,
            MethodInfo method,
            FoxServiceAttribute attr,
            HashSet<string> seenNames)
        {
            if (attr == null || string.IsNullOrWhiteSpace(attr.Name) || !attr.Name.StartsWith("/", StringComparison.Ordinal))
                throw new InvalidOperationException("FOXSERVICE001: " + target + ": service name must be an absolute Foxglove service path.");

            if (!seenNames.Add(attr.Name))
                throw new InvalidOperationException("FOXSERVICE005: " + target + ": duplicate service name '" + attr.Name + "' within source.");

            var parameters = method.GetParameters();
            if (method.IsStatic
                || method.IsGenericMethod
                || method.GetCustomAttribute<AsyncStateMachineAttribute>() != null
                || parameters.Length > 1
                || parameters.Any(parameter => parameter.ParameterType.IsByRef || parameter.IsOut || parameter.IsDefined(typeof(ParamArrayAttribute), false))
                || IsUnsupportedServiceType(method.ReturnType)
                || parameters.Any(parameter => IsUnsupportedServiceType(parameter.ParameterType)))
                throw new InvalidOperationException("FOXSERVICE002: " + target + ": service methods must be non-static, synchronous, non-generic, and accept zero or one serializable DTO parameter.");

            if (parameters.Length == 1)
                ValidateServiceDtoType(target, attr.Name, parameters[0].ParameterType, FoxServiceDtoRules.RequestSide, "Request");

            if (method.ReturnType != typeof(void))
                ValidateServiceDtoType(target, attr.Name, method.ReturnType, FoxServiceDtoRules.ResponseSide, "Response");
        }

        private static bool IsUnsupportedServiceType(Type type)
        {
            if (type == null || type == typeof(void))
                return false;

            if (type.IsPointer || type.IsByRef || type.IsGenericParameter)
                return true;

            if (type.FullName == "System.Threading.Tasks.Task"
                || (type.FullName != null && type.FullName.StartsWith("System.Threading.Tasks.Task`", StringComparison.Ordinal)))
                return true;

            if (type.IsGenericType && type.GetGenericArguments().Any(argument => argument.IsGenericParameter))
                return true;

            return IsByRefLike(type);
        }

        private static string SchemaNameFromType(Type type)
            => type == null
                ? string.Empty
                : (type.FullName ?? type.Name).Replace('+', '.');

        private static bool IsByRefLike(Type type)
        {
            var property = typeof(Type).GetProperty("IsByRefLike", BindingFlags.Instance | BindingFlags.Public);
            return property != null
                   && property.PropertyType == typeof(bool)
                   && type != null
                   && (bool)property.GetValue(type);
        }

        private static void ValidateServiceDtoType(string target, string serviceName, Type type, string side, string rootPath)
        {
            var dtoSide = side == FoxServiceDtoRules.RequestSide ? FoxServiceDtoSide.Request : FoxServiceDtoSide.Response;
            foreach (var diagnostic in FoxServiceDtoReflectionValidator.Validate(type, dtoSide, serviceName))
            {
                var message = diagnostic.Id + ": " + target + ": " + diagnostic.FormatTarget(serviceName);
                if (diagnostic.IsWarning)
                    Debug.LogWarning("[FoxrunCodeGenerator] " + message);
                else
                    throw new InvalidOperationException(message);
            }
        }

        /// <summary>
        /// Generate a complete .g.cs source file string for a single class.
        /// Delegates to <c>FoxgloveSourceEmitter.EmitClass</c> for output
        /// consistency with the Roslyn ISG path.
        /// </summary>
        public static string EmitSourceFile(MemberData[] members)
        {
            if (members == null)
                throw new ArgumentNullException(nameof(members));
            if (members.Length == 0)
                throw new ArgumentException("At least one FoxRun member is required to emit a source file.", nameof(members));

            var reflectionMembers = new FoxRunReflectionGenerationMember[members.Length];
            for (var i = 0; i < members.Length; i++)
                reflectionMembers[i] = members[i].ToReflectionMember();

            var model = LowerReflectionMembers(reflectionMembers);
            ValidateGenerationModel(model);
            if (model.Types.Count != 1)
                throw new ArgumentException("Members must describe exactly one FoxRun declaring type.", nameof(members));

            return EmitSourceFile(model.Types[0]);
        }

        public static string EmitSourceFile(FoxRunGenerationType type)
        {
            var core = FoxgloveSourceEmitter.EmitClass(type);

            // Wrap with a Player-only guard so Editor compilation uses the Roslyn
            // generated in-memory source and Player builds use the physical file.
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("// Copyright (c) 2026 Jianbin Liu and Unity2Foxglove contributors.");
            sb.AppendLine("// SPDX-License-Identifier: Apache-2.0");
            sb.AppendLine("// " + FoxRunGeneratedSourceReconciler.GeneratedSourceSentinel);
            sb.AppendLine("// In the Unity Editor, the Roslyn analyzer already generates this partial type in memory.");
            sb.AppendLine("#if !UNITY_EDITOR");
            sb.Append(core);
            sb.AppendLine("#endif");
            return sb.ToString();
        }

        public static string EmitServiceSourceFile(
            string ns,
            string className,
            IReadOnlyList<FoxServiceSourceEmitter.ServiceMethod> methods)
        {
            if (methods == null || methods.Count == 0)
                throw new ArgumentException("At least one FoxService method is required to emit a source file.", nameof(methods));

            var core = FoxServiceSourceEmitter.EmitClass(ns, className, methods);
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("// Copyright (c) 2026 Jianbin Liu and Unity2Foxglove contributors.");
            sb.AppendLine("// SPDX-License-Identifier: Apache-2.0");
            sb.AppendLine("// " + FoxRunGeneratedSourceReconciler.GeneratedSourceSentinel);
            sb.AppendLine("// In the Unity Editor, the Roslyn analyzer already generates this partial type in memory.");
            sb.AppendLine("#if !UNITY_EDITOR");
            sb.Append(core);
            sb.AppendLine("#endif");
            return sb.ToString();
        }

        /// <summary>
        /// Immutable data record for one <c>[FoxRun]</c>-attributed member, used
        /// during reflection-based scanning and source file generation.
        /// </summary>
        public sealed class MemberData
        {
            /// <summary>Field or property name.</summary>
            public readonly string MemberName;
            /// <summary>Field or property kind.</summary>
            public readonly string MemberKind;
            /// <summary>Field or property type as full-qualified string.</summary>
            public readonly string RawTypeName;
            public readonly string EmissionTypeName;
            /// <summary>Whether the source CLR type is a value type.</summary>
            public readonly bool IsValueType;
            /// <summary>Whether the source CLR type is a supported array/list shape.</summary>
            public readonly bool IsArray;
            /// <summary>Element type for supported array/list source CLR types.</summary>
            public readonly string ElementTypeName;
            /// <summary>Topic string from the attribute.</summary>
            public readonly string Topic;
            /// <summary>Optional schema name.</summary>
            public readonly string SchemaName;
            /// <summary>Containing class name.</summary>
            public readonly string ClassName;
            /// <summary>Containing namespace (empty for global).</summary>
            public readonly string Ns;
            /// <summary>Publishing rate in Hz.</summary>
            public readonly float RateHz;
            /// <summary>Publish mode as int enum value.</summary>
            public readonly int PublishMode;
            /// <summary>Change epsilon.</summary>
            public readonly float ChangeEpsilon;
            /// <summary>Heartbeat interval seconds.</summary>
            public readonly float ForceIntervalSeconds;
            public readonly int RawMemberOrder;
            public readonly string ConditionalSymbols;
            public readonly string When;
            public readonly string Unless;

            /// <summary>
            /// Constructs a <c>MemberData</c> from a reflection <c>Type</c> and
            /// namespace/class context.
            /// </summary>
            public MemberData(string name, Type type, string memberKind, string ns, string cn, string topic, float rate, string schema,
                int publishMode = 0, float changeEpsilon = 0f, float forceIntervalSeconds = 0f, int rawMemberOrder = -1, string conditionalSymbols = "", string when = "", string unless = "")
            {
                MemberName = name;
                MemberKind = memberKind;
                RawTypeName = type.FullName ?? type.Name;
                EmissionTypeName = FoxRunEmissionTypeNameFormatter.FromReflectionType(type);
                IsValueType = type.IsValueType;
                IsArray = TryGetArrayElementType(type, out var elementType);
                ElementTypeName = elementType == null ? "" : elementType.FullName ?? elementType.Name;
                Ns = ns;
                ClassName = cn;
                Topic = topic;
                RateHz = rate;
                SchemaName = schema;
                PublishMode = publishMode;
                ChangeEpsilon = changeEpsilon;
                ForceIntervalSeconds = forceIntervalSeconds;
                RawMemberOrder = rawMemberOrder;
                ConditionalSymbols = conditionalSymbols ?? "";
                When = when ?? "";
                Unless = unless ?? "";
            }

            /// <summary>
            /// Constructs a <c>MemberData</c> with a raw type string and no
            /// namespace/class context (used in tests or diagnostics).
            /// </summary>
            public MemberData(string name, string rawType, string topic, float rate, string schema,
                int publishMode = 0, float changeEpsilon = 0f, float forceIntervalSeconds = 0f, int rawMemberOrder = -1, string conditionalSymbols = "", string when = "", string unless = "")
            {
                MemberName = name;
                MemberKind = "field";
                RawTypeName = rawType;
                EmissionTypeName = FoxRunEmissionTypeNameFormatter.NormalizeCSharpTypeName(rawType);
                IsValueType = false;
                IsArray = false;
                ElementTypeName = "";
                Topic = topic;
                RateHz = rate;
                SchemaName = schema;
                Ns = "";
                ClassName = "";
                PublishMode = publishMode;
                ChangeEpsilon = changeEpsilon;
                ForceIntervalSeconds = forceIntervalSeconds;
                RawMemberOrder = rawMemberOrder;
                ConditionalSymbols = conditionalSymbols ?? "";
                When = when ?? "";
                Unless = unless ?? "";
            }

            public FoxRunManifestMember ToManifestMember()
            {
                return new FoxRunManifestMember(
                    Ns,
                ClassName,
                MemberName,
                MemberKind,
                RawTypeName,
                IsValueType,
                IsArray,
                ElementTypeName,
                Topic,
                    RateHz,
                    SchemaName,
                    PublishMode,
                    ChangeEpsilon,
                    ForceIntervalSeconds);
            }

            public FoxRunReflectionGenerationMember ToReflectionMember()
            {
                return new FoxRunReflectionGenerationMember(
                    Ns,
                    ClassName,
                    MemberName,
                    MemberKind,
                    RawTypeName,
                    EmissionTypeName,
                    IsValueType,
                    IsArray,
                    ElementTypeName,
                    Topic,
                    SchemaName,
                    RateHz,
                    PublishMode,
                    ChangeEpsilon,
                    ForceIntervalSeconds,
                    RawMemberOrder,
                    ConditionalSymbols,
                    When,
                    Unless);
            }
        }

        private sealed class FoxRunScanResult
        {
            public readonly Dictionary<(string Ns, string ClassName), List<MemberData>> ByClass;
            public readonly List<FoxRunManifestMember> ManifestMembers;
            public readonly List<FoxRunReflectionGenerationMember> ReflectionMembers;

            public FoxRunScanResult(
                Dictionary<(string Ns, string ClassName), List<MemberData>> byClass,
                List<FoxRunManifestMember> manifestMembers,
                List<FoxRunReflectionGenerationMember> reflectionMembers)
            {
                ByClass = byClass;
                ManifestMembers = manifestMembers;
                ReflectionMembers = reflectionMembers;
            }
        }

        private sealed class FoxServiceScanResult
        {
            public readonly Dictionary<(string Ns, string ClassName), List<FoxServiceSourceEmitter.ServiceMethod>> ByClass;

            public FoxServiceScanResult(Dictionary<(string Ns, string ClassName), List<FoxServiceSourceEmitter.ServiceMethod>> byClass)
            {
                ByClass = byClass;
            }
        }

        private sealed class FoxServiceScanEntry
        {
            public readonly (string Ns, string ClassName) Key;
            public readonly string Owner;
            public readonly FoxServiceSourceEmitter.ServiceMethod Method;

            public FoxServiceScanEntry((string Ns, string ClassName) key, string owner, FoxServiceSourceEmitter.ServiceMethod method)
            {
                Key = key;
                Owner = owner ?? string.Empty;
                Method = method;
            }
        }

        private static bool TryGetArrayElementType(Type type, out Type elementType)
        {
            if (type.IsArray && type.GetArrayRank() == 1)
            {
                elementType = type.GetElementType();
                return elementType != null;
            }

            if (type.IsGenericType)
            {
                var definition = type.GetGenericTypeDefinition();
                if (definition == typeof(List<>) || definition == typeof(IReadOnlyList<>) || definition == typeof(IList<>))
                {
                    elementType = type.GetGenericArguments()[0];
                    return true;
                }
            }

            elementType = null;
            return false;
        }

        private static void WarnSkippedAssembly(Assembly asm, ReflectionTypeLoadException ex)
        {
            var assemblyName = asm == null ? "<unknown>" : asm.GetName().Name;
            Debug.LogWarning(
                "[FoxrunCodeGenerator] Skipped assembly '" + assemblyName + "' while scanning [FoxRun] members because type loading failed. " +
                LoaderExceptionSummary(ex));
        }

        private static string LoaderExceptionSummary(ReflectionTypeLoadException ex)
        {
            if (ex == null || ex.LoaderExceptions == null || ex.LoaderExceptions.Length == 0)
                return "No LoaderExceptions were provided.";

            var messages = ex.LoaderExceptions
                .Where(loader => loader != null)
                .Select(loader => loader.GetType().Name + ": " + loader.Message)
                .Take(3)
                .ToList();
            if (messages.Count == 0)
                return "LoaderExceptions contained no exception details.";

            if (ex.LoaderExceptions.Length > messages.Count)
                messages.Add("... " + (ex.LoaderExceptions.Length - messages.Count).ToString() + " more");
            return "LoaderExceptions: " + string.Join(" | ", messages);
        }

        private static bool WriteSourceFileIfChanged(string path, byte[] bytes)
        {
            if (File.Exists(path) && File.ReadAllBytes(path).SequenceEqual(bytes))
                return false;

            WriteBytesWithTempReplace(path, bytes);
            return true;
        }

        private static void WriteTextFileIfChanged(string path, string text)
        {
            WriteSourceFileIfChanged(path, Utf8NoBom.GetBytes(text ?? string.Empty));
        }

        private static void WriteBytesWithTempReplace(string path, byte[] bytes)
        {
            var directory = Path.GetDirectoryName(path);
            if (!string.IsNullOrEmpty(directory))
                Directory.CreateDirectory(directory);
            var tempPath = path + ".tmp";
            File.WriteAllBytes(tempPath, bytes ?? Array.Empty<byte>());

            for (var attempt = 1; ; attempt++)
            {
                try
                {
                    if (File.Exists(path))
                        File.Replace(tempPath, path, null);
                    else
                        File.Move(tempPath, path);
                    return;
                }
                catch when (attempt < ReplaceAttempts)
                {
                    System.Threading.Thread.Sleep(ReplaceRetryDelayMilliseconds);
                }
                catch
                {
                    TryDeleteTempFile(tempPath);
                    throw;
                }
            }
        }

        private static void TryDeleteTempFile(string path)
        {
            try
            {
                if (File.Exists(path))
                    File.Delete(path);
            }
            catch
            {
                // Preserve the original write failure.
            }
        }
    }
}
