// Copyright (c) 2026 Jianbin Liu and Unity2Foxglove contributors.
// SPDX-License-Identifier: Apache-2.0
//
// Module: Editor/FoxRun
// Purpose: Scans assemblies for [FoxRun] attributed fields and generates
// IFoxgloveLogSource implementation .cs files for FoxgloveLogHub.

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using Unity.FoxgloveSDK.Components;
using UnityEngine;

namespace Unity.FoxgloveSDK.Editor
{
    /// <summary>
    /// Generates real .g.cs files for [FoxRun] annotated classes.
    /// Used by IPreprocessBuildWithReport to produce IL2CPP-compatible source files.
    /// Shares code generation logic with FoxgloveLogSourceGenerator (Roslyn ISG).
    /// </summary>
    public static class FoxrunCodeGenerator
    {
        const string OutputDir = "Assets/Scripts/Generated/";
        private static readonly UTF8Encoding Utf8NoBom = new UTF8Encoding(false);

        /// <summary>
        /// Collect the types that GenerateSourceFiles would process, without writing files.
        /// Returns a list of (assemblyName, namespace, className) tuples for IL2CPP preservation.
        /// </summary>
        public static List<(string AsmName, string Ns, string ClassName)> CollectFoxRunTypes()
        {
            var types = new List<(string, string, string)>();
            foreach (var asm in AppDomain.CurrentDomain.GetAssemblies())
            {
                try
                {
                    foreach (var type in asm.GetTypes())
                    {
                        if (!type.IsClass || type.IsAbstract) continue;
                        if (!IsPartial(type)) continue;
                        if (!typeof(MonoBehaviour).IsAssignableFrom(type)) continue;
                        var members = ScanType(type);
                        if (members.Count == 0) continue;
                        types.Add((asm.GetName().Name, type.Namespace ?? "", type.Name));
                    }
                }
                catch (ReflectionTypeLoadException ex)
                {
                    throw new InvalidOperationException(
                        $"Failed to scan assembly '{asm.GetName().Name}' for [FoxRun] types.", ex);
                }
            }
            return types;
        }

        /// <summary>
        /// Generate an IL2CPP link.xml snippet that preserves FoxRun user types
        /// discovered by CollectFoxRunTypes. Returns the XML string.
        /// </summary>
        public static string EmitLinkXml(List<(string AsmName, string Ns, string ClassName)> types)
        {
            var sb = new StringBuilder();
            sb.AppendLine("<?xml version=\"1.0\" encoding=\"utf-8\"?>");
            sb.AppendLine("<!-- Generated by FoxrunBuildPreprocess - do not edit by hand. -->");
            sb.AppendLine("<linker>");
            var seen = new HashSet<string>();
            foreach (var (asm, ns, cn) in types)
            {
                var full = string.IsNullOrEmpty(ns) ? cn : $"{ns}.{cn}";
                if (!seen.Add($"{asm}:{full}")) continue;
                sb.AppendLine($"  <assembly fullname=\"{asm}\">");
                sb.AppendLine($"    <type fullname=\"{full}\" preserve=\"all\" />");
                sb.AppendLine($"  </assembly>");
            }
            sb.AppendLine("</linker>");
            return sb.ToString();
        }

        /// <summary>
        /// Scan all loaded assemblies for [FoxRun] fields/properties on partial classes,
        /// and generate _FoxRun.g.cs files under Assets/Scripts/Generated/.
        /// Returns the list of generated file paths.
        /// Files are only written if content differs from existing file (prevents recompile loop).
        /// </summary>
        public static List<string> GenerateSourceFiles()
        {
            var result = new List<string>();
            var scan = ScanFoxRunMembers(ignoreReflectionTypeLoadExceptions: true);
            var byClass = scan.ByClass;
            var model = FoxRunReflectionGenerationModelLowerer.Lower(scan.ReflectionMembers);

            if (byClass.Count > 0)
            {
                Directory.CreateDirectory(Path.Combine(Application.dataPath, "Scripts/Generated"));

                foreach (var type in model.Types)
                {
                    var kv = (Key: (Ns: type.Namespace, ClassName: type.ClassName), Value: type);
                    var source = EmitSourceFile(kv.Value);
                    var fileName = FoxgloveSourceEmitter.GeneratedSourceName(kv.Key.Ns, kv.Key.ClassName);
                    var absolutePath = Path.Combine(Application.dataPath, "Scripts/Generated", fileName);
                    var sourceBytes = Utf8NoBom.GetBytes(source);

                    bool shouldWrite = true;
                    if (File.Exists(absolutePath))
                    {
                        var existing = File.ReadAllBytes(absolutePath);
                        if (existing.SequenceEqual(sourceBytes))
                            shouldWrite = false;
                    }

                    if (shouldWrite)
                    {
                        File.WriteAllBytes(absolutePath, sourceBytes);
                        Debug.Log($"[FoxrunCodeGenerator] Generated {fileName}");
                    }

                    result.Add(fileName);
                }
            }

            var manifest = WriteManifestFiles(scan.ManifestMembers);
            WriteSchemaInfoFiles(manifest);
            WriteDescriptorFile(model);

            return result;
        }

        /// <summary>
        /// Refresh canonical FoxRun manifest artifacts and generated runtime
        /// schema info without writing physical Player publisher fallback files.
        /// </summary>
        public static FoxRunCanonicalManifest GenerateManifestFilesOnly()
        {
            return GenerateManifestAndSchemaInfoFilesOnly();
        }

        /// <summary>
        /// Refresh canonical FoxRun manifest artifacts and generated runtime
        /// schema info under the configured schema evidence root. This is used by Editor
        /// Play Mode so local contract evidence is current without writing
        /// physical _FoxRun.g.cs Player fallback source files.
        /// </summary>
        public static FoxRunCanonicalManifest GenerateManifestAndSchemaInfoFilesOnly()
        {
            var scan = ScanFoxRunMembers(ignoreReflectionTypeLoadExceptions: true);
            var model = FoxRunReflectionGenerationModelLowerer.Lower(scan.ReflectionMembers);
            var manifest = WriteManifestFiles(scan.ManifestMembers);
            WriteSchemaInfoFiles(manifest);
            WriteDescriptorFile(model);
            return manifest;
        }

        public static IReadOnlyList<FoxRunManifestMember> CollectManifestMembers()
        {
            return ScanFoxRunMembers(ignoreReflectionTypeLoadExceptions: false).ManifestMembers;
        }

        public static FoxRunSchemaInfoVerification VerifyGeneratedSchemaInfoFiles()
        {
            var scan = ScanFoxRunMembers(ignoreReflectionTypeLoadExceptions: true);
            var manifest = FoxRunManifestBuilder.Build(scan.ManifestMembers);
            var sourcePath = Path.Combine(GetManifestOutputDirectory(), FoxRunSchemaInfoWriter.SchemaInfoFileName);
            if (!File.Exists(sourcePath))
                throw new InvalidOperationException("Missing generated FoxRun schema info: " + sourcePath);

            var verification = FoxRunSchemaInfoWriter.VerifyGeneratedInfo(manifest, File.ReadAllText(sourcePath));
            if (!verification.IsValid)
                throw new InvalidOperationException(string.Join("; ", verification.Errors));
            return verification;
        }

        private static FoxRunCanonicalManifest WriteManifestFiles(IReadOnlyList<FoxRunManifestMember> members)
        {
            return FoxrunManifestWriter.WriteManifestFiles(
                GetManifestOutputDirectory(),
                members);
        }

        private static FoxRunSchemaInfoVerification WriteSchemaInfoFiles(FoxRunCanonicalManifest manifest)
        {
            return FoxRunSchemaInfoWriter.WriteGeneratedInfoFiles(GetManifestOutputDirectory(), manifest);
        }

        private static void WriteDescriptorFile(FoxRunGenerationModel model)
        {
            var outputDirectory = GetManifestOutputDirectory();
            Directory.CreateDirectory(outputDirectory);
            var path = Path.Combine(outputDirectory, FoxRunGenerationDescriptorConstants.DescriptorFileName);
            File.WriteAllText(path, FoxRunGenerationDescriptorJsonWriter.Write(model), Utf8NoBom);
        }

        private static string GetManifestOutputDirectory()
        {
            return Unity2FoxgloveSchemaEvidencePaths.ResolveFoxRunOutputDirectory();
        }

        private static FoxRunScanResult ScanFoxRunMembers(bool ignoreReflectionTypeLoadExceptions)
        {
            var byClass = new Dictionary<(string Ns, string ClassName), List<MemberData>>();
            var manifestMembers = new List<FoxRunManifestMember>();
            var reflectionMembers = new List<FoxRunReflectionGenerationMember>();

            foreach (var asm in AppDomain.CurrentDomain.GetAssemblies())
            {
                try
                {
                    foreach (var type in asm.GetTypes())
                    {
                        if (!type.IsClass || type.IsAbstract) continue;
                        if (!IsPartial(type)) continue;
                        if (!typeof(MonoBehaviour).IsAssignableFrom(type)) continue;

                        var members = ScanType(type);
                        if (members.Count == 0) continue;

                        var ns = type.Namespace ?? "";
                        var key = (ns, type.Name);
                        if (!byClass.TryGetValue(key, out var list))
                            byClass[key] = list = new List<MemberData>();
                        list.AddRange(members);
                        manifestMembers.AddRange(members.Select(member => member.ToManifestMember()));
                        reflectionMembers.AddRange(members.Select(member => member.ToReflectionMember()));
                    }
                }
                catch (ReflectionTypeLoadException)
                {
                    if (!ignoreReflectionTypeLoadExceptions)
                        throw;
                    // Source fallback generation is best-effort because the Roslyn
                    // path already reports authoring errors in the Editor. The
                    // link.xml scan is fail-fast and catches preservation risk.
                }
            }

            return new FoxRunScanResult(byClass, manifestMembers, reflectionMembers);
        }

        /// <summary>
        /// Checks whether a type was declared <c>partial</c>.
        /// <para>Runtime detection is not possible because the CLR erases partial
        /// metadata. The build pipeline assumes every <c>MonoBehaviour</c> with
        /// <c>[FoxRun]</c> members was declared partial; the Roslyn ISG enforces this
        /// at Editor compile time via FOXRUN001.</para>
        /// </summary>
        static bool IsPartial(Type type)
        {
            // Partial classes in C# have no runtime metadata at the type level.
            // We detect by checking if the generated members (via ISG) would create
            // a partial extension. For the build step, we assume any MonoBehaviour
            // with [FoxRun] members was declared partial in source.
            // If the class was NOT partial, ISG would have emitted FOXRUN001 at Editor compile time,
            // so this is a safe assumption for Player builds.
            return true;
        }

        /// <summary>
        /// Reflects over all instance fields and properties (public and non-public,
        /// declared only) on the given type and collects <c>[FoxRun]</c> attributed
        /// members as <c>MemberData</c> entries.
        /// </summary>
        static List<MemberData> ScanType(Type type)
        {
            var result = new List<MemberData>();
            var flags = BindingFlags.Instance | BindingFlags.NonPublic | BindingFlags.Public | BindingFlags.DeclaredOnly;
            var ns = type.Namespace ?? "";
            var cn = type.Name;

            foreach (var fi in type.GetFields(flags))
            {
                var attrs = fi.GetCustomAttributes<FoxRunAttribute>();
                foreach (var a in attrs)
                {
                    result.Add(new MemberData(
                        fi.Name, fi.FieldType, "field", ns, cn, a.Topic, a.RateHz, a.SchemaName ?? "",
                        (int)a.PublishMode, a.ChangeEpsilon, a.ForceIntervalSeconds, fi.MetadataToken));
                }
            }
            foreach (var pi in type.GetProperties(flags))
            {
                var attrs = pi.GetCustomAttributes<FoxRunAttribute>();
                foreach (var a in attrs)
                {
                    result.Add(new MemberData(
                        pi.Name, pi.PropertyType, "property", ns, cn, a.Topic, a.RateHz, a.SchemaName ?? "",
                        (int)a.PublishMode, a.ChangeEpsilon, a.ForceIntervalSeconds, pi.MetadataToken));
                }
            }
            return result;
        }

        /// <summary>
        /// Generate a complete .g.cs source file string for a single class.
        /// Delegates to <c>FoxgloveSourceEmitter.EmitClass</c> for output
        /// consistency with the Roslyn ISG path.
        /// </summary>
        public static string EmitSourceFile(MemberData[] members)
        {
            var model = FoxRunReflectionGenerationModelLowerer.Lower(members.Select(member => member.ToReflectionMember()).ToList());
            return EmitSourceFile(model.Types[0]);
        }

        public static string EmitSourceFile(FoxRunGenerationType type)
        {
            var core = FoxgloveSourceEmitter.EmitClass(type);

            // Wrap with a Player-only guard so Editor compilation uses the Roslyn
            // generated in-memory source and Player builds use the physical file.
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("// Copyright (c) 2026 Jianbin Liu and Unity2Foxglove contributors.");
            sb.AppendLine("// SPDX-License-Identifier: Apache-2.0");
            sb.AppendLine("// Generated as a physical fallback for Player/IL2CPP builds.");
            sb.AppendLine("// In the Unity Editor, the Roslyn analyzer already generates this partial type in memory.");
            sb.AppendLine("#if !UNITY_EDITOR");
            sb.Append(core);
            sb.AppendLine("#endif");
            return sb.ToString();
        }

        /// <summary>
        /// Immutable data record for one <c>[FoxRun]</c>-attributed member, used
        /// during reflection-based scanning and source file generation.
        /// </summary>
        public sealed class MemberData
        {
            /// <summary>Field or property name.</summary>
            public readonly string MemberName;
            /// <summary>Field or property kind.</summary>
            public readonly string MemberKind;
            /// <summary>Field or property type as full-qualified string.</summary>
            public readonly string RawTypeName;
            /// <summary>Whether the source CLR type is a value type.</summary>
            public readonly bool IsValueType;
            /// <summary>Whether the source CLR type is a supported array/list shape.</summary>
            public readonly bool IsArray;
            /// <summary>Element type for supported array/list source CLR types.</summary>
            public readonly string ElementTypeName;
            /// <summary>Topic string from the attribute.</summary>
            public readonly string Topic;
            /// <summary>Optional schema name.</summary>
            public readonly string SchemaName;
            /// <summary>Containing class name.</summary>
            public readonly string ClassName;
            /// <summary>Containing namespace (empty for global).</summary>
            public readonly string Ns;
            /// <summary>Publishing rate in Hz.</summary>
            public readonly float RateHz;
            /// <summary>Publish mode as int enum value.</summary>
            public readonly int PublishMode;
            /// <summary>Change epsilon.</summary>
            public readonly float ChangeEpsilon;
            /// <summary>Heartbeat interval seconds.</summary>
            public readonly float ForceIntervalSeconds;
            public readonly int RawMemberOrder;
            public readonly string ConditionalSymbols;

            /// <summary>
            /// Constructs a <c>MemberData</c> from a reflection <c>Type</c> and
            /// namespace/class context.
            /// </summary>
            public MemberData(string name, Type type, string memberKind, string ns, string cn, string topic, float rate, string schema,
                int publishMode = 0, float changeEpsilon = 0f, float forceIntervalSeconds = 0f, int rawMemberOrder = -1, string conditionalSymbols = "")
            {
                MemberName = name;
                MemberKind = memberKind;
                RawTypeName = type.FullName ?? type.Name;
                IsValueType = type.IsValueType;
                IsArray = TryGetArrayElementType(type, out var elementType);
                ElementTypeName = elementType == null ? "" : elementType.FullName ?? elementType.Name;
                Ns = ns;
                ClassName = cn;
                Topic = topic;
                RateHz = rate;
                SchemaName = schema;
                PublishMode = publishMode;
                ChangeEpsilon = changeEpsilon;
                ForceIntervalSeconds = forceIntervalSeconds;
                RawMemberOrder = rawMemberOrder;
                ConditionalSymbols = conditionalSymbols ?? "";
            }

            /// <summary>
            /// Constructs a <c>MemberData</c> with a raw type string and no
            /// namespace/class context (used in tests or diagnostics).
            /// </summary>
            public MemberData(string name, string rawType, string topic, float rate, string schema,
                int publishMode = 0, float changeEpsilon = 0f, float forceIntervalSeconds = 0f, int rawMemberOrder = -1, string conditionalSymbols = "")
            {
                MemberName = name;
                MemberKind = "field";
                RawTypeName = rawType;
                IsValueType = false;
                IsArray = false;
                ElementTypeName = "";
                Topic = topic;
                RateHz = rate;
                SchemaName = schema;
                Ns = "";
                ClassName = "";
                PublishMode = publishMode;
                ChangeEpsilon = changeEpsilon;
                ForceIntervalSeconds = forceIntervalSeconds;
                RawMemberOrder = rawMemberOrder;
                ConditionalSymbols = conditionalSymbols ?? "";
            }

            public FoxRunManifestMember ToManifestMember()
            {
                return new FoxRunManifestMember(
                    Ns,
                    ClassName,
                    MemberName,
                    MemberKind,
                    RawTypeName,
                    IsValueType,
                    IsArray,
                    ElementTypeName,
                    Topic,
                    RateHz,
                    SchemaName,
                    PublishMode,
                    ChangeEpsilon,
                    ForceIntervalSeconds);
            }

            public FoxRunReflectionGenerationMember ToReflectionMember()
            {
                return new FoxRunReflectionGenerationMember(
                    Ns,
                    ClassName,
                    MemberName,
                    MemberKind,
                    RawTypeName,
                    IsValueType,
                    IsArray,
                    ElementTypeName,
                    Topic,
                    SchemaName,
                    RateHz,
                    PublishMode,
                    ChangeEpsilon,
                    ForceIntervalSeconds,
                    RawMemberOrder,
                    ConditionalSymbols);
            }
        }

        private sealed class FoxRunScanResult
        {
            public readonly Dictionary<(string Ns, string ClassName), List<MemberData>> ByClass;
            public readonly List<FoxRunManifestMember> ManifestMembers;
            public readonly List<FoxRunReflectionGenerationMember> ReflectionMembers;

            public FoxRunScanResult(
                Dictionary<(string Ns, string ClassName), List<MemberData>> byClass,
                List<FoxRunManifestMember> manifestMembers,
                List<FoxRunReflectionGenerationMember> reflectionMembers)
            {
                ByClass = byClass;
                ManifestMembers = manifestMembers;
                ReflectionMembers = reflectionMembers;
            }
        }

        private static bool TryGetArrayElementType(Type type, out Type elementType)
        {
            if (type.IsArray && type.GetArrayRank() == 1)
            {
                elementType = type.GetElementType();
                return elementType != null;
            }

            if (type.IsGenericType)
            {
                var definition = type.GetGenericTypeDefinition();
                if (definition == typeof(List<>) || definition == typeof(IReadOnlyList<>))
                {
                    elementType = type.GetGenericArguments()[0];
                    return true;
                }
            }

            elementType = null;
            return false;
        }
    }
}
