// Copyright (c) 2026 Jianbin Liu and Unity2Foxglove contributors.
// SPDX-License-Identifier: Apache-2.0
//
// Module: Tests/Runtime
// Purpose: Phase 140-68 regression coverage for FoxRun shared emitter model optimizations.

using System;
using System.IO;
using Unity.FoxgloveSDK.Editor;

namespace Unity.FoxgloveSDK.Tests
{
    /// <summary>
    /// Validation type for Phase140_68Validation.
    /// </summary>
    public static class Phase140_68Validation
    {
        private static int _passed;

        /// <summary>
        /// Validation method for Validate.
        /// </summary>
        public static void Validate()
        {
            Console.WriteLine();
            Console.WriteLine("=== Phase 140-68: FoxRun Shared Emitter Model Optimization ===");
            _passed = 0;

            VerifyNativeContainerPrefixesAreHoisted();
            VerifyTypeNormalizationAvoidsRedundantWork();
            VerifyDescriptorComparerAvoidsExtraSetAndListCopies();
            VerifyGeneratedSourceReconcilerAvoidsWholeFileRead();
            VerifyDescriptorWriterPresizesOutput();
            VerifyOutputEquivalence();
            VerifyRegistration();

            Console.WriteLine($"Phase 140-68: {_passed} checks passed.");
        }

        private static void VerifyNativeContainerPrefixesAreHoisted()
        {
            var source = Read("Packages/dev.unity2foxglove.sdk/Editor/Shared/FoxRunDescriptor/FoxRunGenerationModelValidator.cs");
            Check(source.Contains("private static readonly string[] UnityNativeContainerPrefixes", StringComparison.Ordinal)
                  && source.Contains("foreach (var prefix in UnityNativeContainerPrefixes)", StringComparison.Ordinal)
                  && !SourceMethodContains(source, "private static bool IsUnityNativeContainerTypeName", "new[]"),
                "140-68A-1: native container prefix table is hoisted out of the per-member validator path");
        }

        private static void VerifyTypeNormalizationAvoidsRedundantWork()
        {
            var model = Read("Packages/dev.unity2foxglove.sdk/Editor/Shared/FoxRunDescriptor/FoxRunGenerationModel.cs");
            Check(SourceMethodContains(model, "private string SelectCanonicalSourceType()", "return ElementTypeName;")
                  && !SourceMethodContains(model, "private string SelectCanonicalSourceType()", "NormalizeCSharpTypeName(ElementTypeName)"),
                "140-68B-1: array canonical source type reuses the already-normalized element type");

            var formatter = Read("Packages/dev.unity2foxglove.sdk/Editor/Shared/FoxRunDescriptor/FoxRunEmissionTypeNameFormatter.cs");
            Check(formatter.Contains("IndexOf(\"global::\", StringComparison.Ordinal)", StringComparison.Ordinal)
                  && formatter.Contains("IndexOf('+')", StringComparison.Ordinal),
                "140-68B-2: C# type normalization guards uncommon replacement work");
        }

        private static void VerifyDescriptorComparerAvoidsExtraSetAndListCopies()
        {
            var source = Read("Packages/dev.unity2foxglove.sdk/Editor/Shared/FoxRunDescriptor/FoxRunGenerationDescriptorComparer.cs");
            Check(source.Contains("CompareSortedMemberKeys", StringComparison.Ordinal)
                  && !source.Contains(".Except(", StringComparison.Ordinal)
                  && !source.Contains(".Intersect(", StringComparison.Ordinal),
                "140-68C-1: descriptor comparer walks sorted member keys without LINQ set passes");
            Check(source.Contains("AsReadOnly()", StringComparison.Ordinal)
                  && source.Contains("copyInputs", StringComparison.Ordinal)
                  && source.Contains("copyInputs: false", StringComparison.Ordinal),
                "140-68C-2: descriptor comparer result can wrap owned difference lists without recopying");
        }

        private static void VerifyGeneratedSourceReconcilerAvoidsWholeFileRead()
        {
            var source = Read("Packages/dev.unity2foxglove.sdk/Editor/Shared/FoxRunDescriptor/FoxRunGeneratedSourceReconciler.cs");
            Check(source.Contains("StreamReader", StringComparison.Ordinal)
                  && source.Contains("ReadLine()", StringComparison.Ordinal)
                  && !source.Contains("File.ReadAllText(path)", StringComparison.Ordinal),
                "140-68D-1: generated source ownership check streams sentinels instead of reading whole files");

            var temp = Path.Combine(Path.GetTempPath(), "u2f_phase140_68_" + Guid.NewGuid().ToString("N") + ".g.cs");
            try
            {
                File.WriteAllText(temp, "// <auto-generated/>\n// Generated as a physical fallback for Player/IL2CPP builds.\npublic class A {}\n");
                Check(FoxRunGeneratedSourceReconciler.IsOwnedGeneratedSourceFile(temp),
                    "140-68D-2: generated source ownership still recognizes header sentinels");
                File.WriteAllText(temp, "public class B {}\n");
                Check(!FoxRunGeneratedSourceReconciler.IsOwnedGeneratedSourceFile(temp),
                    "140-68D-3: generated source ownership still rejects non-owned files");
            }
            finally
            {
                if (File.Exists(temp))
                    File.Delete(temp);
            }
        }

        private static void VerifyDescriptorWriterPresizesOutput()
        {
            var source = Read("Packages/dev.unity2foxglove.sdk/Editor/Shared/FoxRunDescriptor/FoxRunGenerationDescriptorJsonWriter.cs");
            Check(source.Contains("EstimateCapacity(model)", StringComparison.Ordinal)
                  && source.Contains("new StringBuilder(EstimateCapacity(model))", StringComparison.Ordinal),
                "140-68E-1: descriptor JSON writer pre-sizes its StringBuilder from model shape");
        }

        private static void VerifyOutputEquivalence()
        {
            var model = new FoxRunGenerationModel(new[]
            {
                new FoxRunGenerationType(
                    "Demo",
                    "Car",
                    new[]
                    {
                        new FoxRunGenerationMember(
                            "Demo",
                            "Car",
                            "speed",
                            "field",
                            "System.Single",
                            "float",
                            "float",
                            true,
                            false,
                            "",
                            "/vehicle/speed",
                            30f,
                            "unity2foxglove.Float32",
                            3,
                            0.001f,
                            1f,
                            "reflection",
                            7,
                            "UNITY_EDITOR"),
                        new FoxRunGenerationMember(
                            "Demo",
                            "Car",
                            "samples",
                            "property",
                            "System.Single[]",
                            "float[]",
                            "",
                            false,
                            true,
                            "global::System.Single",
                            "/vehicle/samples",
                            0f,
                            "unity2foxglove.Float32",
                            3,
                            0f,
                            0f,
                            "roslyn",
                            8,
                            "")
                    })
            });

            var json = FoxRunGenerationDescriptorJsonWriter.Write(model);
            Check(json.Contains("\"descriptorVersion\":1", StringComparison.Ordinal)
                  && json.Contains("\"elementTypeName\":\"float\"", StringComparison.Ordinal)
                  && json.Contains("\"topic\":\"/vehicle/samples\"", StringComparison.Ordinal),
                "140-68F-1: descriptor JSON output keeps expected canonical fields after optimization");

            var comparison = FoxRunGenerationDescriptorComparer.Compare(model, model);
            Check(comparison.IsSemanticEqual && comparison.IsProvenanceEqual,
                "140-68F-2: optimized descriptor comparison preserves equal-model semantics");
        }

        private static void VerifyRegistration()
        {
            var project = Read("Packages/dev.unity2foxglove.sdk/Tests/Runtime/FoxgloveSdk.Tests.csproj");
            Check(project.Contains("Phase140_68Validation.cs", StringComparison.Ordinal),
                "140-68G-1: test project compiles Phase140_68Validation");
            var registry = Read("Packages/dev.unity2foxglove.sdk/Tests/Runtime/PhaseValidationRegistry.cs");
            Check(registry.Contains("\"--phase140-68\"", StringComparison.Ordinal)
                  && registry.Contains("Phase140_68Validation.Validate", StringComparison.Ordinal),
                "140-68G-2: validation registry exposes --phase140-68");
        }

        private static string Read(string relativePath)
            => File.ReadAllText(Path.Combine(RepoRoot(), relativePath));

        private static string RepoRoot()
        {
            var directory = AppContext.BaseDirectory;
            while (!string.IsNullOrEmpty(directory))
            {
                if (Directory.Exists(Path.Combine(directory, ".git")))
                    return directory;
                directory = Directory.GetParent(directory)?.FullName;
            }
            throw new DirectoryNotFoundException("Could not locate repository root.");
        }

        private static bool SourceMethodContains(string source, string signature, string text)
        {
            var start = source.IndexOf(signature, StringComparison.Ordinal);
            if (start < 0)
                return false;
            var next = source.IndexOf("\n        }", start + signature.Length, StringComparison.Ordinal);
            if (next < 0)
                next = source.Length;
            return source.Substring(start, next - start).Contains(text, StringComparison.Ordinal);
        }

        private static void Check(bool condition, string label)
        {
            if (!condition)
                throw new InvalidOperationException("[FAIL] " + label);
            Console.WriteLine("[PASS] " + label);
            _passed++;
        }
    }
}
