// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: foxglove/Grid.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Foxglove {

  /// <summary>Holder for reflection information generated from foxglove/Grid.proto</summary>
  public static partial class GridReflection {

    #region Descriptor
    /// <summary>File descriptor for foxglove/Grid.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GridReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChNmb3hnbG92ZS9HcmlkLnByb3RvEghmb3hnbG92ZRohZm94Z2xvdmUvUGFj",
            "a2VkRWxlbWVudEZpZWxkLnByb3RvGhNmb3hnbG92ZS9Qb3NlLnByb3RvGhZm",
            "b3hnbG92ZS9WZWN0b3IyLnByb3RvGh9nb29nbGUvcHJvdG9idWYvdGltZXN0",
            "YW1wLnByb3RvIoYCCgRHcmlkEi0KCXRpbWVzdGFtcBgBIAEoCzIaLmdvb2ds",
            "ZS5wcm90b2J1Zi5UaW1lc3RhbXASEAoIZnJhbWVfaWQYAiABKAkSHAoEcG9z",
            "ZRgDIAEoCzIOLmZveGdsb3ZlLlBvc2USFAoMY29sdW1uX2NvdW50GAQgASgH",
            "EiQKCWNlbGxfc2l6ZRgFIAEoCzIRLmZveGdsb3ZlLlZlY3RvcjISEgoKcm93",
            "X3N0cmlkZRgGIAEoBxITCgtjZWxsX3N0cmlkZRgHIAEoBxIsCgZmaWVsZHMY",
            "CCADKAsyHC5mb3hnbG92ZS5QYWNrZWRFbGVtZW50RmllbGQSDAoEZGF0YRgJ",
            "IAEoDGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Foxglove.PackedElementFieldReflection.Descriptor, global::Foxglove.PoseReflection.Descriptor, global::Foxglove.Vector2Reflection.Descriptor, global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Foxglove.Grid), global::Foxglove.Grid.Parser, new[]{ "Timestamp", "FrameId", "Pose", "ColumnCount", "CellSize", "RowStride", "CellStride", "Fields", "Data" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// A 2D grid of data
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Grid : pb::IMessage<Grid>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Grid> _parser = new pb::MessageParser<Grid>(() => new Grid());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Grid> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Foxglove.GridReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Grid() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Grid(Grid other) : this() {
      timestamp_ = other.timestamp_ != null ? other.timestamp_.Clone() : null;
      frameId_ = other.frameId_;
      pose_ = other.pose_ != null ? other.pose_.Clone() : null;
      columnCount_ = other.columnCount_;
      cellSize_ = other.cellSize_ != null ? other.cellSize_.Clone() : null;
      rowStride_ = other.rowStride_;
      cellStride_ = other.cellStride_;
      fields_ = other.fields_.Clone();
      data_ = other.data_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Grid Clone() {
      return new Grid(this);
    }

    /// <summary>Field number for the "timestamp" field.</summary>
    public const int TimestampFieldNumber = 1;
    private global::Google.Protobuf.WellKnownTypes.Timestamp timestamp_;
    /// <summary>
    /// Timestamp of grid
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp Timestamp {
      get { return timestamp_; }
      set {
        timestamp_ = value;
      }
    }

    /// <summary>Field number for the "frame_id" field.</summary>
    public const int FrameIdFieldNumber = 2;
    private string frameId_ = "";
    /// <summary>
    /// Frame of reference
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string FrameId {
      get { return frameId_; }
      set {
        frameId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "pose" field.</summary>
    public const int PoseFieldNumber = 3;
    private global::Foxglove.Pose pose_;
    /// <summary>
    /// Origin of grid's corner relative to frame of reference; grid is positioned in the x-y plane relative to this origin
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Foxglove.Pose Pose {
      get { return pose_; }
      set {
        pose_ = value;
      }
    }

    /// <summary>Field number for the "column_count" field.</summary>
    public const int ColumnCountFieldNumber = 4;
    private uint columnCount_;
    /// <summary>
    /// Number of grid columns
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint ColumnCount {
      get { return columnCount_; }
      set {
        columnCount_ = value;
      }
    }

    /// <summary>Field number for the "cell_size" field.</summary>
    public const int CellSizeFieldNumber = 5;
    private global::Foxglove.Vector2 cellSize_;
    /// <summary>
    /// Size of single grid cell along x and y axes, relative to `pose`
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Foxglove.Vector2 CellSize {
      get { return cellSize_; }
      set {
        cellSize_ = value;
      }
    }

    /// <summary>Field number for the "row_stride" field.</summary>
    public const int RowStrideFieldNumber = 6;
    private uint rowStride_;
    /// <summary>
    /// Number of bytes between rows in `data`
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint RowStride {
      get { return rowStride_; }
      set {
        rowStride_ = value;
      }
    }

    /// <summary>Field number for the "cell_stride" field.</summary>
    public const int CellStrideFieldNumber = 7;
    private uint cellStride_;
    /// <summary>
    /// Number of bytes between cells within a row in `data`
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint CellStride {
      get { return cellStride_; }
      set {
        cellStride_ = value;
      }
    }

    /// <summary>Field number for the "fields" field.</summary>
    public const int FieldsFieldNumber = 8;
    private static readonly pb::FieldCodec<global::Foxglove.PackedElementField> _repeated_fields_codec
        = pb::FieldCodec.ForMessage(66, global::Foxglove.PackedElementField.Parser);
    private readonly pbc::RepeatedField<global::Foxglove.PackedElementField> fields_ = new pbc::RepeatedField<global::Foxglove.PackedElementField>();
    /// <summary>
    /// Fields in `data`. `red`, `green`, `blue`, and `alpha` are optional for customizing the grid's color.
    /// To enable RGB color visualization in the [3D panel](https://docs.foxglove.dev/docs/visualization/panels/3d#rgba-separate-fields-color-mode), include **all four** of these fields in your `fields` array:
    /// 
    /// - `red` - Red channel value
    /// - `green` - Green channel value
    /// - `blue` - Blue channel value
    /// - `alpha` - Alpha/transparency channel value
    /// 
    /// **note:** All four fields must be present with these exact names for RGB visualization to work. The order of fields doesn't matter, but the names must match exactly.
    /// 
    /// Recommended type: `UINT8` (0-255 range) for standard 8-bit color channels.
    /// 
    /// Example field definitions:
    /// 
    /// **RGB color only:**
    /// 
    /// ```javascript
    /// fields: [
    ///  { name: "red", offset: 0, type: NumericType.UINT8 },
    ///  { name: "green", offset: 1, type: NumericType.UINT8 },
    ///  { name: "blue", offset: 2, type: NumericType.UINT8 },
    ///  { name: "alpha", offset: 3, type: NumericType.UINT8 },
    /// ];
    /// ```
    /// 
    /// **RGB color with elevation (for 3D terrain visualization):**
    /// 
    /// ```javascript
    /// fields: [
    ///  { name: "red", offset: 0, type: NumericType.UINT8 },
    ///  { name: "green", offset: 1, type: NumericType.UINT8 },
    ///  { name: "blue", offset: 2, type: NumericType.UINT8 },
    ///  { name: "alpha", offset: 3, type: NumericType.UINT8 },
    ///  { name: "elevation", offset: 4, type: NumericType.FLOAT32 },
    /// ];
    /// ```
    /// 
    /// When these fields are present, the 3D panel will offer additional "Color Mode" options including "RGBA (separate fields)" to visualize the RGB data directly. For elevation visualization, set the "Elevation field" to your elevation layer name.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Foxglove.PackedElementField> Fields {
      get { return fields_; }
    }

    /// <summary>Field number for the "data" field.</summary>
    public const int DataFieldNumber = 9;
    private pb::ByteString data_ = pb::ByteString.Empty;
    /// <summary>
    /// Grid cell data, interpreted using `fields`, in row-major (y-major) order.
    /// For the data element starting at byte offset i, the coordinates of its corner closest to the origin will be:
    /// 
    /// - y = i / row_stride * cell_size.y
    /// - x = (i % row_stride) / cell_stride * cell_size.x
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString Data {
      get { return data_; }
      set {
        data_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Grid);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Grid other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Timestamp, other.Timestamp)) return false;
      if (FrameId != other.FrameId) return false;
      if (!object.Equals(Pose, other.Pose)) return false;
      if (ColumnCount != other.ColumnCount) return false;
      if (!object.Equals(CellSize, other.CellSize)) return false;
      if (RowStride != other.RowStride) return false;
      if (CellStride != other.CellStride) return false;
      if(!fields_.Equals(other.fields_)) return false;
      if (Data != other.Data) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (timestamp_ != null) hash ^= Timestamp.GetHashCode();
      if (FrameId.Length != 0) hash ^= FrameId.GetHashCode();
      if (pose_ != null) hash ^= Pose.GetHashCode();
      if (ColumnCount != 0) hash ^= ColumnCount.GetHashCode();
      if (cellSize_ != null) hash ^= CellSize.GetHashCode();
      if (RowStride != 0) hash ^= RowStride.GetHashCode();
      if (CellStride != 0) hash ^= CellStride.GetHashCode();
      hash ^= fields_.GetHashCode();
      if (Data.Length != 0) hash ^= Data.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (timestamp_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Timestamp);
      }
      if (FrameId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(FrameId);
      }
      if (pose_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Pose);
      }
      if (ColumnCount != 0) {
        output.WriteRawTag(37);
        output.WriteFixed32(ColumnCount);
      }
      if (cellSize_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(CellSize);
      }
      if (RowStride != 0) {
        output.WriteRawTag(53);
        output.WriteFixed32(RowStride);
      }
      if (CellStride != 0) {
        output.WriteRawTag(61);
        output.WriteFixed32(CellStride);
      }
      fields_.WriteTo(output, _repeated_fields_codec);
      if (Data.Length != 0) {
        output.WriteRawTag(74);
        output.WriteBytes(Data);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (timestamp_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Timestamp);
      }
      if (FrameId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(FrameId);
      }
      if (pose_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Pose);
      }
      if (ColumnCount != 0) {
        output.WriteRawTag(37);
        output.WriteFixed32(ColumnCount);
      }
      if (cellSize_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(CellSize);
      }
      if (RowStride != 0) {
        output.WriteRawTag(53);
        output.WriteFixed32(RowStride);
      }
      if (CellStride != 0) {
        output.WriteRawTag(61);
        output.WriteFixed32(CellStride);
      }
      fields_.WriteTo(ref output, _repeated_fields_codec);
      if (Data.Length != 0) {
        output.WriteRawTag(74);
        output.WriteBytes(Data);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (timestamp_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Timestamp);
      }
      if (FrameId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(FrameId);
      }
      if (pose_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Pose);
      }
      if (ColumnCount != 0) {
        size += 1 + 4;
      }
      if (cellSize_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(CellSize);
      }
      if (RowStride != 0) {
        size += 1 + 4;
      }
      if (CellStride != 0) {
        size += 1 + 4;
      }
      size += fields_.CalculateSize(_repeated_fields_codec);
      if (Data.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Data);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Grid other) {
      if (other == null) {
        return;
      }
      if (other.timestamp_ != null) {
        if (timestamp_ == null) {
          Timestamp = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        Timestamp.MergeFrom(other.Timestamp);
      }
      if (other.FrameId.Length != 0) {
        FrameId = other.FrameId;
      }
      if (other.pose_ != null) {
        if (pose_ == null) {
          Pose = new global::Foxglove.Pose();
        }
        Pose.MergeFrom(other.Pose);
      }
      if (other.ColumnCount != 0) {
        ColumnCount = other.ColumnCount;
      }
      if (other.cellSize_ != null) {
        if (cellSize_ == null) {
          CellSize = new global::Foxglove.Vector2();
        }
        CellSize.MergeFrom(other.CellSize);
      }
      if (other.RowStride != 0) {
        RowStride = other.RowStride;
      }
      if (other.CellStride != 0) {
        CellStride = other.CellStride;
      }
      fields_.Add(other.fields_);
      if (other.Data.Length != 0) {
        Data = other.Data;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (timestamp_ == null) {
              Timestamp = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(Timestamp);
            break;
          }
          case 18: {
            FrameId = input.ReadString();
            break;
          }
          case 26: {
            if (pose_ == null) {
              Pose = new global::Foxglove.Pose();
            }
            input.ReadMessage(Pose);
            break;
          }
          case 37: {
            ColumnCount = input.ReadFixed32();
            break;
          }
          case 42: {
            if (cellSize_ == null) {
              CellSize = new global::Foxglove.Vector2();
            }
            input.ReadMessage(CellSize);
            break;
          }
          case 53: {
            RowStride = input.ReadFixed32();
            break;
          }
          case 61: {
            CellStride = input.ReadFixed32();
            break;
          }
          case 66: {
            fields_.AddEntriesFrom(input, _repeated_fields_codec);
            break;
          }
          case 74: {
            Data = input.ReadBytes();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (timestamp_ == null) {
              Timestamp = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(Timestamp);
            break;
          }
          case 18: {
            FrameId = input.ReadString();
            break;
          }
          case 26: {
            if (pose_ == null) {
              Pose = new global::Foxglove.Pose();
            }
            input.ReadMessage(Pose);
            break;
          }
          case 37: {
            ColumnCount = input.ReadFixed32();
            break;
          }
          case 42: {
            if (cellSize_ == null) {
              CellSize = new global::Foxglove.Vector2();
            }
            input.ReadMessage(CellSize);
            break;
          }
          case 53: {
            RowStride = input.ReadFixed32();
            break;
          }
          case 61: {
            CellStride = input.ReadFixed32();
            break;
          }
          case 66: {
            fields_.AddEntriesFrom(ref input, _repeated_fields_codec);
            break;
          }
          case 74: {
            Data = input.ReadBytes();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
