// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: foxglove/LocationFix.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Foxglove {

  /// <summary>Holder for reflection information generated from foxglove/LocationFix.proto</summary>
  public static partial class LocationFixReflection {

    #region Descriptor
    /// <summary>File descriptor for foxglove/LocationFix.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static LocationFixReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Chpmb3hnbG92ZS9Mb2NhdGlvbkZpeC5wcm90bxIIZm94Z2xvdmUaFGZveGds",
            "b3ZlL0NvbG9yLnByb3RvGhtmb3hnbG92ZS9LZXlWYWx1ZVBhaXIucHJvdG8a",
            "FmZveGdsb3ZlL1ZlY3RvcjMucHJvdG8aH2dvb2dsZS9wcm90b2J1Zi90aW1l",
            "c3RhbXAucHJvdG8i/AMKC0xvY2F0aW9uRml4Ei0KCXRpbWVzdGFtcBgGIAEo",
            "CzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASEAoIZnJhbWVfaWQYByAB",
            "KAkSEAoIbGF0aXR1ZGUYASABKAESEQoJbG9uZ2l0dWRlGAIgASgBEhAKCGFs",
            "dGl0dWRlGAMgASgBEhsKE3Bvc2l0aW9uX2NvdmFyaWFuY2UYBCADKAESTgoY",
            "cG9zaXRpb25fY292YXJpYW5jZV90eXBlGAUgASgOMiwuZm94Z2xvdmUuTG9j",
            "YXRpb25GaXguUG9zaXRpb25Db3ZhcmlhbmNlVHlwZRIUCgdoZWFkaW5nGAog",
            "ASgBSACIAQESKAoIdmVsb2NpdHkYCyABKAsyES5mb3hnbG92ZS5WZWN0b3Iz",
            "SAGIAQESIwoFY29sb3IYCCABKAsyDy5mb3hnbG92ZS5Db2xvckgCiAEBEigK",
            "CG1ldGFkYXRhGAkgAygLMhYuZm94Z2xvdmUuS2V5VmFsdWVQYWlyIlYKFlBv",
            "c2l0aW9uQ292YXJpYW5jZVR5cGUSCwoHVU5LTk9XThAAEhAKDEFQUFJPWElN",
            "QVRFRBABEhIKDkRJQUdPTkFMX0tOT1dOEAISCQoFS05PV04QA0IKCghfaGVh",
            "ZGluZ0ILCglfdmVsb2NpdHlCCAoGX2NvbG9yYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Foxglove.ColorReflection.Descriptor, global::Foxglove.KeyValuePairReflection.Descriptor, global::Foxglove.Vector3Reflection.Descriptor, global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Foxglove.LocationFix), global::Foxglove.LocationFix.Parser, new[]{ "Timestamp", "FrameId", "Latitude", "Longitude", "Altitude", "PositionCovariance", "PositionCovarianceType", "Heading", "Velocity", "Color", "Metadata" }, new[]{ "Heading", "Velocity", "Color" }, new[]{ typeof(global::Foxglove.LocationFix.Types.PositionCovarianceType) }, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// A navigation satellite fix for any Global Navigation Satellite System
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class LocationFix : pb::IMessage<LocationFix>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<LocationFix> _parser = new pb::MessageParser<LocationFix>(() => new LocationFix());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<LocationFix> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Foxglove.LocationFixReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LocationFix() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LocationFix(LocationFix other) : this() {
      _hasBits0 = other._hasBits0;
      timestamp_ = other.timestamp_ != null ? other.timestamp_.Clone() : null;
      frameId_ = other.frameId_;
      latitude_ = other.latitude_;
      longitude_ = other.longitude_;
      altitude_ = other.altitude_;
      positionCovariance_ = other.positionCovariance_.Clone();
      positionCovarianceType_ = other.positionCovarianceType_;
      heading_ = other.heading_;
      velocity_ = other.velocity_ != null ? other.velocity_.Clone() : null;
      color_ = other.color_ != null ? other.color_.Clone() : null;
      metadata_ = other.metadata_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LocationFix Clone() {
      return new LocationFix(this);
    }

    /// <summary>Field number for the "timestamp" field.</summary>
    public const int TimestampFieldNumber = 6;
    private global::Google.Protobuf.WellKnownTypes.Timestamp timestamp_;
    /// <summary>
    /// Timestamp of the message
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp Timestamp {
      get { return timestamp_; }
      set {
        timestamp_ = value;
      }
    }

    /// <summary>Field number for the "frame_id" field.</summary>
    public const int FrameIdFieldNumber = 7;
    private string frameId_ = "";
    /// <summary>
    /// Frame for the sensor. Latitude and longitude readings are at the origin of the frame.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string FrameId {
      get { return frameId_; }
      set {
        frameId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "latitude" field.</summary>
    public const int LatitudeFieldNumber = 1;
    private double latitude_;
    /// <summary>
    /// Latitude in degrees
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double Latitude {
      get { return latitude_; }
      set {
        latitude_ = value;
      }
    }

    /// <summary>Field number for the "longitude" field.</summary>
    public const int LongitudeFieldNumber = 2;
    private double longitude_;
    /// <summary>
    /// Longitude in degrees
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double Longitude {
      get { return longitude_; }
      set {
        longitude_ = value;
      }
    }

    /// <summary>Field number for the "altitude" field.</summary>
    public const int AltitudeFieldNumber = 3;
    private double altitude_;
    /// <summary>
    /// Altitude in meters
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double Altitude {
      get { return altitude_; }
      set {
        altitude_ = value;
      }
    }

    /// <summary>Field number for the "position_covariance" field.</summary>
    public const int PositionCovarianceFieldNumber = 4;
    private static readonly pb::FieldCodec<double> _repeated_positionCovariance_codec
        = pb::FieldCodec.ForDouble(34);
    private readonly pbc::RepeatedField<double> positionCovariance_ = new pbc::RepeatedField<double>();
    /// <summary>
    /// Position covariance (m^2) defined relative to a tangential plane through the reported position. The components are East, North, and Up (ENU), in row-major order.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<double> PositionCovariance {
      get { return positionCovariance_; }
    }

    /// <summary>Field number for the "position_covariance_type" field.</summary>
    public const int PositionCovarianceTypeFieldNumber = 5;
    private global::Foxglove.LocationFix.Types.PositionCovarianceType positionCovarianceType_ = global::Foxglove.LocationFix.Types.PositionCovarianceType.Unknown;
    /// <summary>
    /// If `position_covariance` is available, `position_covariance_type` must be set to indicate the type of covariance.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Foxglove.LocationFix.Types.PositionCovarianceType PositionCovarianceType {
      get { return positionCovarianceType_; }
      set {
        positionCovarianceType_ = value;
      }
    }

    /// <summary>Field number for the "heading" field.</summary>
    public const int HeadingFieldNumber = 10;
    private readonly static double HeadingDefaultValue = 0D;

    private double heading_;
    /// <summary>
    /// Heading (yaw angle), in radians, measured clockwise from north
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double Heading {
      get { if ((_hasBits0 & 1) != 0) { return heading_; } else { return HeadingDefaultValue; } }
      set {
        _hasBits0 |= 1;
        heading_ = value;
      }
    }
    /// <summary>Gets whether the "heading" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasHeading {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "heading" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearHeading() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "velocity" field.</summary>
    public const int VelocityFieldNumber = 11;
    private global::Foxglove.Vector3 velocity_;
    /// <summary>
    /// Velocity in local East-North-Up (ENU) frame in m/s
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Foxglove.Vector3 Velocity {
      get { return velocity_; }
      set {
        velocity_ = value;
      }
    }

    /// <summary>Field number for the "color" field.</summary>
    public const int ColorFieldNumber = 8;
    private global::Foxglove.Color color_;
    /// <summary>
    /// Color used to visualize the location
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Foxglove.Color Color {
      get { return color_; }
      set {
        color_ = value;
      }
    }

    /// <summary>Field number for the "metadata" field.</summary>
    public const int MetadataFieldNumber = 9;
    private static readonly pb::FieldCodec<global::Foxglove.KeyValuePair> _repeated_metadata_codec
        = pb::FieldCodec.ForMessage(74, global::Foxglove.KeyValuePair.Parser);
    private readonly pbc::RepeatedField<global::Foxglove.KeyValuePair> metadata_ = new pbc::RepeatedField<global::Foxglove.KeyValuePair>();
    /// <summary>
    /// Additional user-provided metadata associated with the location fix. Keys must be unique.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Foxglove.KeyValuePair> Metadata {
      get { return metadata_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as LocationFix);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(LocationFix other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Timestamp, other.Timestamp)) return false;
      if (FrameId != other.FrameId) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Latitude, other.Latitude)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Longitude, other.Longitude)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Altitude, other.Altitude)) return false;
      if(!positionCovariance_.Equals(other.positionCovariance_)) return false;
      if (PositionCovarianceType != other.PositionCovarianceType) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Heading, other.Heading)) return false;
      if (!object.Equals(Velocity, other.Velocity)) return false;
      if (!object.Equals(Color, other.Color)) return false;
      if(!metadata_.Equals(other.metadata_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (timestamp_ != null) hash ^= Timestamp.GetHashCode();
      if (FrameId.Length != 0) hash ^= FrameId.GetHashCode();
      if (Latitude != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Latitude);
      if (Longitude != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Longitude);
      if (Altitude != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Altitude);
      hash ^= positionCovariance_.GetHashCode();
      if (PositionCovarianceType != global::Foxglove.LocationFix.Types.PositionCovarianceType.Unknown) hash ^= PositionCovarianceType.GetHashCode();
      if (HasHeading) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Heading);
      if (velocity_ != null) hash ^= Velocity.GetHashCode();
      if (color_ != null) hash ^= Color.GetHashCode();
      hash ^= metadata_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Latitude != 0D) {
        output.WriteRawTag(9);
        output.WriteDouble(Latitude);
      }
      if (Longitude != 0D) {
        output.WriteRawTag(17);
        output.WriteDouble(Longitude);
      }
      if (Altitude != 0D) {
        output.WriteRawTag(25);
        output.WriteDouble(Altitude);
      }
      positionCovariance_.WriteTo(output, _repeated_positionCovariance_codec);
      if (PositionCovarianceType != global::Foxglove.LocationFix.Types.PositionCovarianceType.Unknown) {
        output.WriteRawTag(40);
        output.WriteEnum((int) PositionCovarianceType);
      }
      if (timestamp_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(Timestamp);
      }
      if (FrameId.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(FrameId);
      }
      if (color_ != null) {
        output.WriteRawTag(66);
        output.WriteMessage(Color);
      }
      metadata_.WriteTo(output, _repeated_metadata_codec);
      if (HasHeading) {
        output.WriteRawTag(81);
        output.WriteDouble(Heading);
      }
      if (velocity_ != null) {
        output.WriteRawTag(90);
        output.WriteMessage(Velocity);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Latitude != 0D) {
        output.WriteRawTag(9);
        output.WriteDouble(Latitude);
      }
      if (Longitude != 0D) {
        output.WriteRawTag(17);
        output.WriteDouble(Longitude);
      }
      if (Altitude != 0D) {
        output.WriteRawTag(25);
        output.WriteDouble(Altitude);
      }
      positionCovariance_.WriteTo(ref output, _repeated_positionCovariance_codec);
      if (PositionCovarianceType != global::Foxglove.LocationFix.Types.PositionCovarianceType.Unknown) {
        output.WriteRawTag(40);
        output.WriteEnum((int) PositionCovarianceType);
      }
      if (timestamp_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(Timestamp);
      }
      if (FrameId.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(FrameId);
      }
      if (color_ != null) {
        output.WriteRawTag(66);
        output.WriteMessage(Color);
      }
      metadata_.WriteTo(ref output, _repeated_metadata_codec);
      if (HasHeading) {
        output.WriteRawTag(81);
        output.WriteDouble(Heading);
      }
      if (velocity_ != null) {
        output.WriteRawTag(90);
        output.WriteMessage(Velocity);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (timestamp_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Timestamp);
      }
      if (FrameId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(FrameId);
      }
      if (Latitude != 0D) {
        size += 1 + 8;
      }
      if (Longitude != 0D) {
        size += 1 + 8;
      }
      if (Altitude != 0D) {
        size += 1 + 8;
      }
      size += positionCovariance_.CalculateSize(_repeated_positionCovariance_codec);
      if (PositionCovarianceType != global::Foxglove.LocationFix.Types.PositionCovarianceType.Unknown) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) PositionCovarianceType);
      }
      if (HasHeading) {
        size += 1 + 8;
      }
      if (velocity_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Velocity);
      }
      if (color_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Color);
      }
      size += metadata_.CalculateSize(_repeated_metadata_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(LocationFix other) {
      if (other == null) {
        return;
      }
      if (other.timestamp_ != null) {
        if (timestamp_ == null) {
          Timestamp = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        Timestamp.MergeFrom(other.Timestamp);
      }
      if (other.FrameId.Length != 0) {
        FrameId = other.FrameId;
      }
      if (other.Latitude != 0D) {
        Latitude = other.Latitude;
      }
      if (other.Longitude != 0D) {
        Longitude = other.Longitude;
      }
      if (other.Altitude != 0D) {
        Altitude = other.Altitude;
      }
      positionCovariance_.Add(other.positionCovariance_);
      if (other.PositionCovarianceType != global::Foxglove.LocationFix.Types.PositionCovarianceType.Unknown) {
        PositionCovarianceType = other.PositionCovarianceType;
      }
      if (other.HasHeading) {
        Heading = other.Heading;
      }
      if (other.velocity_ != null) {
        if (velocity_ == null) {
          Velocity = new global::Foxglove.Vector3();
        }
        Velocity.MergeFrom(other.Velocity);
      }
      if (other.color_ != null) {
        if (color_ == null) {
          Color = new global::Foxglove.Color();
        }
        Color.MergeFrom(other.Color);
      }
      metadata_.Add(other.metadata_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 9: {
            Latitude = input.ReadDouble();
            break;
          }
          case 17: {
            Longitude = input.ReadDouble();
            break;
          }
          case 25: {
            Altitude = input.ReadDouble();
            break;
          }
          case 34:
          case 33: {
            positionCovariance_.AddEntriesFrom(input, _repeated_positionCovariance_codec);
            break;
          }
          case 40: {
            PositionCovarianceType = (global::Foxglove.LocationFix.Types.PositionCovarianceType) input.ReadEnum();
            break;
          }
          case 50: {
            if (timestamp_ == null) {
              Timestamp = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(Timestamp);
            break;
          }
          case 58: {
            FrameId = input.ReadString();
            break;
          }
          case 66: {
            if (color_ == null) {
              Color = new global::Foxglove.Color();
            }
            input.ReadMessage(Color);
            break;
          }
          case 74: {
            metadata_.AddEntriesFrom(input, _repeated_metadata_codec);
            break;
          }
          case 81: {
            Heading = input.ReadDouble();
            break;
          }
          case 90: {
            if (velocity_ == null) {
              Velocity = new global::Foxglove.Vector3();
            }
            input.ReadMessage(Velocity);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 9: {
            Latitude = input.ReadDouble();
            break;
          }
          case 17: {
            Longitude = input.ReadDouble();
            break;
          }
          case 25: {
            Altitude = input.ReadDouble();
            break;
          }
          case 34:
          case 33: {
            positionCovariance_.AddEntriesFrom(ref input, _repeated_positionCovariance_codec);
            break;
          }
          case 40: {
            PositionCovarianceType = (global::Foxglove.LocationFix.Types.PositionCovarianceType) input.ReadEnum();
            break;
          }
          case 50: {
            if (timestamp_ == null) {
              Timestamp = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(Timestamp);
            break;
          }
          case 58: {
            FrameId = input.ReadString();
            break;
          }
          case 66: {
            if (color_ == null) {
              Color = new global::Foxglove.Color();
            }
            input.ReadMessage(Color);
            break;
          }
          case 74: {
            metadata_.AddEntriesFrom(ref input, _repeated_metadata_codec);
            break;
          }
          case 81: {
            Heading = input.ReadDouble();
            break;
          }
          case 90: {
            if (velocity_ == null) {
              Velocity = new global::Foxglove.Vector3();
            }
            input.ReadMessage(Velocity);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the LocationFix message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      /// <summary>
      /// Type of position covariance
      /// </summary>
      public enum PositionCovarianceType {
        /// <summary>
        /// Unknown position covariance type
        /// </summary>
        [pbr::OriginalName("UNKNOWN")] Unknown = 0,
        /// <summary>
        /// Position covariance is approximated
        /// </summary>
        [pbr::OriginalName("APPROXIMATED")] Approximated = 1,
        /// <summary>
        /// Position covariance is per-axis, so put it along the diagonal
        /// </summary>
        [pbr::OriginalName("DIAGONAL_KNOWN")] DiagonalKnown = 2,
        /// <summary>
        /// Position covariance of the fix is known
        /// </summary>
        [pbr::OriginalName("KNOWN")] Known = 3,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
