// Copyright (c) 2026 Jianbin Liu and Unity2Foxglove contributors.
// SPDX-License-Identifier: Apache-2.0
//
// Module: Editor/Shared/FoxServiceSourceEmitter
// Purpose: Shared emitter for generated declarative Foxglove service wrappers.

using System;
using System.Collections.Generic;
using System.Text;

namespace Unity.FoxgloveSDK.Editor
{
    /// <summary>
    /// Emits partial classes implementing <c>IFoxgloveServiceSource</c>.
    /// </summary>
    public static class FoxServiceSourceEmitter
    {
        public sealed class ServiceMethod
        {
            public ServiceMethod(
                string methodName,
                string serviceName,
                string serviceType,
                string description,
                string requestSchemaName,
                string responseSchemaName,
                string requestSchema,
                string responseSchema,
                string requestTypeName,
                string responseTypeName,
                bool hasRequest,
                bool hasResponse)
            {
                MethodName = methodName ?? string.Empty;
                ServiceName = serviceName ?? string.Empty;
                ServiceType = serviceType ?? string.Empty;
                Description = description ?? string.Empty;
                RequestSchemaName = requestSchemaName ?? string.Empty;
                ResponseSchemaName = responseSchemaName ?? string.Empty;
                RequestSchema = requestSchema ?? string.Empty;
                ResponseSchema = responseSchema ?? string.Empty;
                RequestTypeName = requestTypeName ?? string.Empty;
                ResponseTypeName = responseTypeName ?? string.Empty;
                HasRequest = hasRequest;
                HasResponse = hasResponse;
            }

            public string MethodName { get; }
            public string ServiceName { get; }
            public string ServiceType { get; }
            public string Description { get; }
            public string RequestSchemaName { get; }
            public string ResponseSchemaName { get; }
            public string RequestSchema { get; }
            public string ResponseSchema { get; }
            public string RequestTypeName { get; }
            public string ResponseTypeName { get; }
            public bool HasRequest { get; }
            public bool HasResponse { get; }
        }

        public static string GeneratedSourceName(string ns, string className)
        {
            var identity = string.IsNullOrEmpty(ns) ? className : ns + "." + className;
            return IdentifierUtils.SanitizeFileStem(identity) + "_FoxService.g.cs";
        }

        public static string EmitClass(string ns, string className, IReadOnlyList<ServiceMethod> methods)
        {
            ValidateQualifiedIdentifierOrEmpty(ns, nameof(ns));
            ValidateIdentifier(className, nameof(className));

            if (methods == null || methods.Count == 0)
                throw new ArgumentException("At least one service method is required.", nameof(methods));

            for (var i = 0; i < methods.Count; i++)
                ValidateMethod(methods[i], i);

            var pad = string.IsNullOrEmpty(ns) ? string.Empty : "    ";
            var sb = new StringBuilder();
            var escapedNamespace = IdentifierUtils.EscapeQualifiedName(ns);
            var escapedClassName = IdentifierUtils.EscapeIdentifier(className);
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("// Copyright (c) 2026 Jianbin Liu and Unity2Foxglove contributors.");
            sb.AppendLine("// SPDX-License-Identifier: Apache-2.0");
            sb.AppendLine("// Generated by the Unity2Foxglove [FoxService] source emitter.");
            sb.AppendLine("#pragma warning disable");
            sb.AppendLine();

            if (!string.IsNullOrEmpty(escapedNamespace))
            {
                sb.AppendLine("namespace " + escapedNamespace);
                sb.AppendLine("{");
            }

            sb.AppendLine(pad + "partial class " + escapedClassName + " : global::Unity.FoxgloveSDK.Components.IFoxgloveServiceSource");
            sb.AppendLine(pad + "{");
            sb.AppendLine(pad + "    private volatile global::System.Collections.Generic.IReadOnlyList<global::Unity.FoxgloveSDK.Components.FoxgloveGeneratedServiceDescriptor> __foxgloveServices;");
            sb.AppendLine(pad + "    private readonly object __foxgloveServicesLock = new object();");
            sb.AppendLine();
            sb.AppendLine(pad + "    global::System.Collections.Generic.IReadOnlyList<global::Unity.FoxgloveSDK.Components.FoxgloveGeneratedServiceDescriptor> global::Unity.FoxgloveSDK.Components.IFoxgloveServiceSource.FoxgloveServices");
            sb.AppendLine(pad + "    {");
            sb.AppendLine(pad + "        get");
            sb.AppendLine(pad + "        {");
            sb.AppendLine(pad + "            if (__foxgloveServices != null)");
            sb.AppendLine(pad + "                return __foxgloveServices;");
            sb.AppendLine(pad + "            lock (__foxgloveServicesLock)");
            sb.AppendLine(pad + "            {");
            sb.AppendLine(pad + "                return __foxgloveServices ?? (__foxgloveServices = new global::Unity.FoxgloveSDK.Components.FoxgloveGeneratedServiceDescriptor[]");
            sb.AppendLine(pad + "        {");
            for (var i = 0; i < methods.Count; i++)
            {
                var method = methods[i];
                sb.AppendLine(pad + "            new global::Unity.FoxgloveSDK.Components.FoxgloveGeneratedServiceDescriptor(\""
                              + Lit(method.ServiceName) + "\", \""
                              + Lit(method.ServiceType) + "\", \""
                              + Lit(method.Description) + "\", \""
                              + Lit(method.RequestSchemaName) + "\", \""
                              + Lit(method.ResponseSchemaName) + "\", \""
                              + Lit(method.RequestSchema) + "\", \""
                              + Lit(method.ResponseSchema) + "\", __FoxService_"
                              + IdentifierUtils.SanitizeIdentifier(method.MethodName) + ")" + (i + 1 == methods.Count ? string.Empty : ","));
            }
            sb.AppendLine(pad + "        });");
            sb.AppendLine(pad + "            }");
            sb.AppendLine(pad + "        }");
            sb.AppendLine(pad + "    }");
            sb.AppendLine();

            foreach (var method in methods)
                EmitWrapper(sb, method, pad);

            sb.AppendLine(pad + "}");
            if (!string.IsNullOrEmpty(ns))
                sb.AppendLine("}");

            return sb.ToString();
        }

        private static void EmitWrapper(StringBuilder sb, ServiceMethod method, string pad)
        {
            var safeName = IdentifierUtils.SanitizeIdentifier(method.MethodName);
            var requestTypeName = QualifyTypeName(method.RequestTypeName);
            sb.AppendLine(pad + "    [global::UnityEngine.Scripting.Preserve]");
            sb.AppendLine(pad + "    private global::Newtonsoft.Json.Linq.JToken __FoxService_" + safeName + "(global::Newtonsoft.Json.Linq.JToken requestToken)");
            sb.AppendLine(pad + "    {");

            if (method.HasRequest)
            {
                sb.AppendLine(pad + "        var request = requestToken == null");
                sb.AppendLine(pad + "            ? default(" + requestTypeName + ")");
                sb.AppendLine(pad + "            : requestToken.ToObject<" + requestTypeName + ">();");
            }

            if (method.HasResponse)
            {
                sb.Append(pad + "        var response = ");
                sb.Append(IdentifierUtils.EscapeIdentifier(method.MethodName));
                sb.Append(method.HasRequest ? "(request);" : "();");
                sb.AppendLine();
                sb.AppendLine(pad + "        return response == null ? global::Newtonsoft.Json.Linq.JValue.CreateNull() : global::Newtonsoft.Json.Linq.JToken.FromObject(response);");
            }
            else
            {
                sb.Append(pad + "        ");
                sb.Append(IdentifierUtils.EscapeIdentifier(method.MethodName));
                sb.Append(method.HasRequest ? "(request);" : "();");
                sb.AppendLine();
                sb.AppendLine(pad + "        return new global::Newtonsoft.Json.Linq.JObject();");
            }

            sb.AppendLine(pad + "    }");
            sb.AppendLine();
        }

        private static string Lit(string value)
            => StringLiteralEmitter.CSharpStringLiteral(value);

        private static void ValidateMethod(ServiceMethod method, int index)
        {
            if (method == null)
                throw new ArgumentException("Service method " + index + " is null.", nameof(method));

            ValidateIdentifier(method.MethodName, "methods[" + index + "].MethodName");
        }

        private static void ValidateQualifiedIdentifierOrEmpty(string value, string paramName)
        {
            if (string.IsNullOrEmpty(value))
                return;

            var parts = value.Split('.');
            for (var i = 0; i < parts.Length; i++)
                ValidateIdentifier(parts[i], paramName);
        }

        private static void ValidateIdentifier(string value, string paramName)
        {
            var text = (value ?? string.Empty).Trim();
            if (text.StartsWith("@", StringComparison.Ordinal))
                text = text.Substring(1);
            if (text.Length == 0 || !IdentifierUtils.IsIdentifierStart(text[0]))
                throw new ArgumentException("Generated service identifier is invalid: " + value, paramName);
            for (var i = 1; i < text.Length; i++)
            {
                if (!IdentifierUtils.IsIdentifierPart(text[i]))
                    throw new ArgumentException("Generated service identifier is invalid: " + value, paramName);
            }
        }

        private static string QualifyTypeName(string typeName)
        {
            var text = (typeName ?? string.Empty).Trim();
            text = IdentifierUtils.EscapeTypeName(text);
            if (text.Length == 0)
                return text;
            if (IsBuiltInAlias(text) || text.StartsWith("global::", StringComparison.Ordinal))
                return text;
            if (text.EndsWith("[]", StringComparison.Ordinal))
                return QualifyTypeName(text.Substring(0, text.Length - 2)) + "[]";
            if (text.EndsWith("?", StringComparison.Ordinal))
                return QualifyTypeName(text.Substring(0, text.Length - 1)) + "?";

            var genericStart = FindTopLevel(text, '<');
            if (genericStart >= 0 && text.EndsWith(">", StringComparison.Ordinal))
            {
                var baseName = QualifyTypeName(text.Substring(0, genericStart));
                var args = text.Substring(genericStart + 1, text.Length - genericStart - 2);
                return baseName + "<" + string.Join(", ", SplitGenericArguments(args).ConvertAll(QualifyTypeName)) + ">";
            }

            return text.IndexOf(".", StringComparison.Ordinal) >= 0 ? "global::" + text : text;
        }

        private static bool IsBuiltInAlias(string typeName)
        {
            switch (typeName)
            {
                case "bool":
                case "byte":
                case "sbyte":
                case "short":
                case "ushort":
                case "int":
                case "uint":
                case "long":
                case "ulong":
                case "float":
                case "double":
                case "decimal":
                case "string":
                case "object":
                case "char":
                case "void":
                case "dynamic":
                case "nint":
                case "nuint":
                    return true;
                default:
                    return false;
            }
        }

        private static int FindTopLevel(string value, char needle)
        {
            var depth = 0;
            for (var i = 0; i < value.Length; i++)
            {
                var ch = value[i];
                if (ch == '<') depth++;
                if (ch == '>') depth--;
                if (ch == needle && depth == 1)
                    return i;
            }
            return -1;
        }

        private static List<string> SplitGenericArguments(string value)
        {
            var result = new List<string>();
            var depth = 0;
            var start = 0;
            for (var i = 0; i < value.Length; i++)
            {
                var ch = value[i];
                if (ch == '<') depth++;
                if (ch == '>') depth--;
                if (ch == ',' && depth == 0)
                {
                    result.Add(value.Substring(start, i - start).Trim());
                    start = i + 1;
                }
            }
            result.Add(value.Substring(start).Trim());
            return result;
        }
    }
}
