// Copyright (c) 2026 Jianbin Liu and Unity2Foxglove contributors.
// SPDX-License-Identifier: Apache-2.0
//
// Module: Editor/Manager
// Purpose: Physical-generation definition registry for optional transport packages.

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Unity.FoxgloveSDK.Editor
{
    public readonly struct FoxRunTransportEmitterContext
    {
        public FoxRunTransportEmitterContext(
            FoxRunGenerationModel model,
            FoxRunGenerationType type)
        {
            Model = model ?? throw new ArgumentNullException(nameof(model));
            Type = type ?? throw new ArgumentNullException(nameof(type));
        }

        public FoxRunGenerationModel Model { get; }
        public FoxRunGenerationType Type { get; }
    }

    public interface IFoxRunTransportEmitterContribution
    {
        string ProviderId { get; }
        string HintNameSuffix { get; }

        void Emit(in FoxRunTransportEmitterContext context, StringBuilder output);
    }

    /// <summary>
    /// Editor-domain definition registry. Contributions are immutable emitter
    /// definitions and never contain runtime Managers, Providers, or sockets.
    /// </summary>
    public static class FoxRunTransportEmitterContributionRegistry
    {
        private static readonly object Gate = new object();
        private static readonly Dictionary<string, IFoxRunTransportEmitterContribution>
            Contributions =
                new Dictionary<string, IFoxRunTransportEmitterContribution>(
                    StringComparer.Ordinal);

        public static void Register(IFoxRunTransportEmitterContribution contribution)
        {
            if (contribution == null)
                throw new ArgumentNullException(nameof(contribution));
            _ = new Components.FoxRunTransportId(contribution.ProviderId);
            if (string.IsNullOrWhiteSpace(contribution.HintNameSuffix))
                throw new ArgumentException("Emitter hint suffix cannot be empty.", nameof(contribution));

            var key = contribution.ProviderId + "\n" + contribution.HintNameSuffix;
            lock (Gate)
            {
                if (Contributions.TryGetValue(key, out var existing)
                    && !ReferenceEquals(existing, contribution)
                    && existing.GetType() != contribution.GetType())
                {
                    throw new InvalidOperationException(
                        "Duplicate FoxRun transport emitter contribution '" + key + "'.");
                }

                Contributions[key] = contribution;
            }
        }

        public static IReadOnlyList<IFoxRunTransportEmitterContribution> Capture()
        {
            lock (Gate)
            {
                return Contributions
                    .OrderBy(pair => pair.Key, StringComparer.Ordinal)
                    .Select(pair => pair.Value)
                    .ToArray();
            }
        }
    }

    /// <summary>
    /// Shared deterministic physical-file wrapper used by Unity generation
    /// and by package-combination parity tests.
    /// </summary>
    public static class FoxRunTransportContributionSource
    {
        public static string EmitSourceFile(
            FoxRunGenerationModel model,
            FoxRunGenerationType type,
            IFoxRunTransportEmitterContribution contribution)
        {
            if (model == null)
                throw new ArgumentNullException(nameof(model));
            if (type == null)
                throw new ArgumentNullException(nameof(type));
            if (contribution == null)
                throw new ArgumentNullException(nameof(contribution));

            _ = new Components.FoxRunTransportId(contribution.ProviderId);
            if (string.IsNullOrWhiteSpace(contribution.HintNameSuffix))
            {
                throw new ArgumentException(
                    "Emitter hint suffix cannot be empty.",
                    nameof(contribution));
            }

            var emitted = new StringBuilder();
            var context = new FoxRunTransportEmitterContext(model, type);
            contribution.Emit(in context, emitted);
            if (emitted.Length == 0)
                return string.Empty;

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("// Copyright (c) 2026 Jianbin Liu and Unity2Foxglove contributors.");
            sb.AppendLine("// SPDX-License-Identifier: Apache-2.0");
            sb.AppendLine("// " + FoxRunGeneratedSourceReconciler.GeneratedSourceSentinel);
            sb.AppendLine(
                "// Optional transport contribution: "
                + contribution.ProviderId);
            sb.AppendLine("#if !UNITY_EDITOR");
            sb.Append(emitted);
            if (emitted[emitted.Length - 1] != '\n')
                sb.AppendLine();
            sb.AppendLine("#endif");
            return sb.ToString();
        }

        public static string SourceName(
            string ns,
            string className,
            IFoxRunTransportEmitterContribution contribution)
        {
            if (contribution == null)
                throw new ArgumentNullException(nameof(contribution));

            var identity = string.IsNullOrEmpty(ns)
                ? className
                : ns + "." + className;
            return IdentifierUtils.SanitizeFileStem(identity)
                   + "_"
                   + IdentifierUtils.SanitizeFileStem(
                       contribution.ProviderId)
                   + "_"
                   + IdentifierUtils.SanitizeFileStem(
                       contribution.HintNameSuffix)
                   + "_FoxRun.g.cs";
        }
    }
}
