// Copyright (c) 2026 Jianbin Liu and Unity2Foxglove contributors.
// SPDX-License-Identifier: Apache-2.0
//
// Module: Editor/Shared/FoxRunDescriptor
// Purpose: Reconciles physical FoxRun fallback source files written for Player builds.

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;

namespace Unity.FoxgloveSDK.Editor
{
    public static class FoxRunGeneratedSourceReconciler
    {
        public const string GeneratedSourceSentinel = "Generated as a physical fallback for Player/IL2CPP builds.";
        public const string GeneratedSourcePattern = "*_FoxRun.g.cs";

        public static IReadOnlyList<string> ReconcileGeneratedSourceFiles(
            string outputDirectory,
            IReadOnlyCollection<string> currentFileNames)
        {
            if (string.IsNullOrEmpty(outputDirectory) || !Directory.Exists(outputDirectory))
                return Array.Empty<string>();

            var current = new HashSet<string>(
                currentFileNames ?? Array.Empty<string>(),
                StringComparer.OrdinalIgnoreCase);
            var deleted = new List<string>();

            foreach (var path in Directory.GetFiles(outputDirectory, GeneratedSourcePattern, SearchOption.TopDirectoryOnly))
            {
                var fileName = Path.GetFileName(path);
                if (current.Contains(fileName) || !IsOwnedGeneratedSourceFile(path))
                    continue;

                File.Delete(path);
                DeleteSidecarMeta(path);
                deleted.Add(fileName);
            }

            return deleted;
        }

        public static bool IsOwnedGeneratedSourceFile(string path)
        {
            if (string.IsNullOrEmpty(path) || !File.Exists(path))
                return false;

            try
            {
                var source = File.ReadAllText(path);
                return source.Contains("// <auto-generated/>", StringComparison.Ordinal)
                       && source.Contains(GeneratedSourceSentinel, StringComparison.Ordinal);
            }
            catch (IOException)
            {
                return false;
            }
            catch (UnauthorizedAccessException)
            {
                return false;
            }
        }

        private static void DeleteSidecarMeta(string sourcePath)
        {
            var metaPath = sourcePath + ".meta";
            if (!File.Exists(metaPath))
                return;

            try
            {
                File.Delete(metaPath);
            }
            catch (IOException)
            {
            }
            catch (UnauthorizedAccessException)
            {
            }
        }
    }
}
