// <auto-generated/>
// Copyright (c) 2026 Jianbin Liu and Unity2Foxglove contributors.
// SPDX-License-Identifier: Apache-2.0
// Generated by the Unity2Foxglove [FoxRun] source emitter.
#pragma warning disable
using System;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Scripting;
using Unity.FoxgloveSDK.Components;

namespace Unity.FoxgloveSDK.Tests.Fixtures
{
    [Preserve]
    partial class FoxRunGenerationModelFixture : IFoxgloveLogSource, IFoxgloveTopicContractSource, IFoxgloveTopicBusSource, IFoxgloveTopicObserverSource, IFoxgloveTopicSinkSource, IFoxglovePublishCaptureSource, IFoxglovePublishRecordingSource, IFoxRunWebSocketCaptureSource, IFoxglovePublishOriginSource, IFoxgloveLogPolicySource
    {
        int IFoxgloveLogSource.FoxgloveLog_TopicCount => 7;

        FoxgloveLogTopicInfo IFoxgloveLogSource.FoxgloveLog_GetTopic(int index)
        {
            switch (index)
            {
                case 0: return new FoxgloveLogTopicInfo("/debug/array", 0f, FoxRunPolicy.Change, 0f, (FoxRunFlow)1, publishTransportIds: null, subscribeTransportId: null, declaredEncoding: (FoxRunEncoding)0, hasExplicitEncoding: false, deliveryPolicy: new FoxRunDeliveryPolicy(FoxRunDeliveryReliability.ProviderDefault, FoxRunDeliveryDurability.ProviderDefault, FoxRunDeliveryHistory.ProviderDefault, 0), hasExplicitDeliveryPolicy: false, hasExplicitHz: false);
                case 1: return new FoxgloveLogTopicInfo("/debug/extra", 0f, FoxRunPolicy.FixedRate, 0f, (FoxRunFlow)1, publishTransportIds: null, subscribeTransportId: null, declaredEncoding: (FoxRunEncoding)0, hasExplicitEncoding: false, deliveryPolicy: new FoxRunDeliveryPolicy(FoxRunDeliveryReliability.ProviderDefault, FoxRunDeliveryDurability.ProviderDefault, FoxRunDeliveryHistory.ProviderDefault, 0), hasExplicitDeliveryPolicy: false, hasExplicitHz: true);
                case 2: return new FoxgloveLogTopicInfo("/debug/list", 0f, FoxRunPolicy.Change, 0f, (FoxRunFlow)1, publishTransportIds: null, subscribeTransportId: null, declaredEncoding: (FoxRunEncoding)0, hasExplicitEncoding: false, deliveryPolicy: new FoxRunDeliveryPolicy(FoxRunDeliveryReliability.ProviderDefault, FoxRunDeliveryDurability.ProviderDefault, FoxRunDeliveryHistory.ProviderDefault, 0), hasExplicitDeliveryPolicy: false, hasExplicitHz: false);
                case 3: return new FoxgloveLogTopicInfo("/debug/nullable", 0f, FoxRunPolicy.Change, 0f, (FoxRunFlow)1, publishTransportIds: null, subscribeTransportId: null, declaredEncoding: (FoxRunEncoding)0, hasExplicitEncoding: false, deliveryPolicy: new FoxRunDeliveryPolicy(FoxRunDeliveryReliability.ProviderDefault, FoxRunDeliveryDurability.ProviderDefault, FoxRunDeliveryHistory.ProviderDefault, 0), hasExplicitDeliveryPolicy: false, hasExplicitHz: false);
                case 4: return new FoxgloveLogTopicInfo("/debug/trigger", 0f, FoxRunPolicy.Trigger, 0f, (FoxRunFlow)1, publishTransportIds: null, subscribeTransportId: null, declaredEncoding: (FoxRunEncoding)0, hasExplicitEncoding: false, deliveryPolicy: new FoxRunDeliveryPolicy(FoxRunDeliveryReliability.ProviderDefault, FoxRunDeliveryDurability.ProviderDefault, FoxRunDeliveryHistory.ProviderDefault, 0), hasExplicitDeliveryPolicy: false, hasExplicitHz: false);
                case 5: return new FoxgloveLogTopicInfo("/debug/value", 5f, FoxRunPolicy.Change, 0.01f, (FoxRunFlow)1, publishTransportIds: null, subscribeTransportId: null, declaredEncoding: (FoxRunEncoding)0, hasExplicitEncoding: false, deliveryPolicy: new FoxRunDeliveryPolicy(FoxRunDeliveryReliability.ProviderDefault, FoxRunDeliveryDurability.ProviderDefault, FoxRunDeliveryHistory.ProviderDefault, 0), hasExplicitDeliveryPolicy: false, hasExplicitHz: true);
                case 6: return new FoxgloveLogTopicInfo("/debug/vector", 0f, FoxRunPolicy.Change, 0.001f, (FoxRunFlow)1, publishTransportIds: null, subscribeTransportId: null, declaredEncoding: (FoxRunEncoding)0, hasExplicitEncoding: false, deliveryPolicy: new FoxRunDeliveryPolicy(FoxRunDeliveryReliability.ProviderDefault, FoxRunDeliveryDurability.ProviderDefault, FoxRunDeliveryHistory.ProviderDefault, 0), hasExplicitDeliveryPolicy: false, hasExplicitHz: false);
                default: return default;
            }
        }

        private static readonly FoxTopicContract __foxRunContract_0 = new FoxTopicContract("/debug/array", "", "json", "v2|topic=12#/debug/array|encoding=4#json|schema=0#|fields=1|field|json=7#samples|member=8#_samples|canonical=7#float32|shape=247#S|kind=3|type=0#|canonical=0#|collection=1|nullable=0|constructible=1|valueType=0|fields=0|enumValues=0|element=S|kind=0|type=7#float32|canonical=7#float32|collection=0|nullable=0|constructible=1|valueType=1|fields=0|enumValues=0|element=N|end|end|end", "57aacde4029c0cc8861f163852c8c9d366eacf4a221f45f9fc5fef8f2c400086", FoxTopicVisibility.Exported, FoxTopicWriterPolicy.SingleWriter);
        private static readonly FoxTopicContract __foxRunContract_1 = new FoxTopicContract("/debug/extra", "", "json", "v2|topic=12#/debug/extra|encoding=4#json|schema=0#|fields=1|field|json=5#extra|member=6#_extra|canonical=6#string|shape=129#S|kind=0|type=6#string|canonical=6#string|collection=0|nullable=0|constructible=1|valueType=0|fields=0|enumValues=0|element=N|end|end", "8a7b121bd413e594b0e1ad5753416056a4228f81f76e6d10d69ef3db64220820", FoxTopicVisibility.Exported, FoxTopicWriterPolicy.SingleWriter);
        private static readonly FoxTopicContract __foxRunContract_2 = new FoxTopicContract("/debug/list", "", "json", "v2|topic=11#/debug/list|encoding=4#json|schema=0#|fields=1|field|json=10#sampleList|member=11#_sampleList|canonical=7#float32|shape=247#S|kind=3|type=0#|canonical=0#|collection=2|nullable=0|constructible=1|valueType=0|fields=0|enumValues=0|element=S|kind=0|type=7#float32|canonical=7#float32|collection=0|nullable=0|constructible=1|valueType=1|fields=0|enumValues=0|element=N|end|end|end", "87de9ce25523919ec9c8b74fd8d058ab33aaed0884a81b22c7e8d96898d3b960", FoxTopicVisibility.Exported, FoxTopicWriterPolicy.SingleWriter);
        private static readonly FoxTopicContract __foxRunContract_3 = new FoxTopicContract("/debug/nullable", "", "json", "v2|topic=15#/debug/nullable|encoding=4#json|schema=0#|fields=1|field|json=13#optionalCount|member=14#_optionalCount|canonical=5#int32|shape=127#S|kind=0|type=5#int32|canonical=5#int32|collection=0|nullable=1|constructible=1|valueType=1|fields=0|enumValues=0|element=N|end|end", "86d27a004a146efb799011b2e479ae1dcb718f25b369d9f9f32faf4d93266290", FoxTopicVisibility.Exported, FoxTopicWriterPolicy.SingleWriter);
        private static readonly FoxTopicContract __foxRunContract_4 = new FoxTopicContract("/debug/trigger", "", "json", "v2|topic=14#/debug/trigger|encoding=4#json|schema=0#|fields=1|field|json=7#trigger|member=8#_trigger|canonical=5#int32|shape=127#S|kind=0|type=5#int32|canonical=5#int32|collection=0|nullable=0|constructible=1|valueType=1|fields=0|enumValues=0|element=N|end|end", "c6f190ea27d7c4822491e2079f63c7d6c361e3c1fa832ac3b14bf1a4bb7dab98", FoxTopicVisibility.Exported, FoxTopicWriterPolicy.SingleWriter);
        private static readonly FoxTopicContract __foxRunContract_5 = new FoxTopicContract("/debug/value", "", "json", "v2|topic=12#/debug/value|encoding=4#json|schema=0#|fields=2|field|json=5#value|member=6#_value|canonical=7#float32|shape=131#S|kind=0|type=7#float32|canonical=7#float32|collection=0|nullable=0|constructible=1|valueType=1|fields=0|enumValues=0|element=N|end|field|json=11#valueMirror|member=12#_valueMirror|canonical=7#float32|shape=131#S|kind=0|type=7#float32|canonical=7#float32|collection=0|nullable=0|constructible=1|valueType=1|fields=0|enumValues=0|element=N|end|end", "636b8858805e0683f8039ac86f41ecc680763626513104bda387a23a2a86e1b5", FoxTopicVisibility.Exported, FoxTopicWriterPolicy.SingleWriter);
        private static readonly FoxTopicContract __foxRunContract_6 = new FoxTopicContract("/debug/vector", "", "json", "v2|topic=13#/debug/vector|encoding=4#json|schema=0#|fields=1|field|json=8#position|member=9#_position|canonical=21#unity.vector3.float32|shape=812#S|kind=1|type=19#UnityEngine.Vector3|canonical=0#|collection=0|nullable=0|constructible=1|valueType=1|fields=3|field|json=1#x|member=1#x|repeated=0|repeatedCollection=0|assignable=1|fieldNullable=0|shape=S|kind=0|type=7#float32|canonical=7#float32|collection=0|nullable=0|constructible=1|valueType=1|fields=0|enumValues=0|element=N|end|field|json=1#y|member=1#y|repeated=0|repeatedCollection=0|assignable=1|fieldNullable=0|shape=S|kind=0|type=7#float32|canonical=7#float32|collection=0|nullable=0|constructible=1|valueType=1|fields=0|enumValues=0|element=N|end|field|json=1#z|member=1#z|repeated=0|repeatedCollection=0|assignable=1|fieldNullable=0|shape=S|kind=0|type=7#float32|canonical=7#float32|collection=0|nullable=0|constructible=1|valueType=1|fields=0|enumValues=0|element=N|end|enumValues=0|element=N|end|end", "3d0eede5337ec250ae2b7840ac0c93e1d56a280f4aa0c7039f3a03f262f3c151", FoxTopicVisibility.Exported, FoxTopicWriterPolicy.SingleWriter);

        string IFoxgloveTopicContractSource.FoxgloveLog_Origin => __foxRunOrigin;

        FoxTopicContract IFoxgloveTopicContractSource.FoxgloveLog_GetContract(int index)
        {
            switch (index)
            {
                case 0: return __foxRunContract_0;
                case 1: return __foxRunContract_1;
                case 2: return __foxRunContract_2;
                case 3: return __foxRunContract_3;
                case 4: return __foxRunContract_4;
                case 5: return __foxRunContract_5;
                case 6: return __foxRunContract_6;
                default: return null;
            }
        }

        private readonly string __foxRunOrigin = "unity2foxglove-" + global::System.Guid.NewGuid().ToString("N");
        private bool __foxRunCaptureActive_0;
        private bool __foxRunRecordMessagePack_0;
        private FoxRunEncoding __foxRunCaptureEncoding_0;
        private float[] __foxRunCapture_0_0;
        private bool __foxRunCaptureActive_1;
        private bool __foxRunRecordMessagePack_1;
        private FoxRunEncoding __foxRunCaptureEncoding_1;
        private string __foxRunCapture_1_0;
        private bool __foxRunCaptureActive_2;
        private bool __foxRunRecordMessagePack_2;
        private FoxRunEncoding __foxRunCaptureEncoding_2;
        private global::System.Collections.Generic.List<float> __foxRunCapture_2_0;
        private bool __foxRunCaptureActive_3;
        private bool __foxRunRecordMessagePack_3;
        private FoxRunEncoding __foxRunCaptureEncoding_3;
        private int? __foxRunCapture_3_0;
        private bool __foxRunCaptureActive_4;
        private bool __foxRunRecordMessagePack_4;
        private FoxRunEncoding __foxRunCaptureEncoding_4;
        private int __foxRunCapture_4_0;
        private bool __foxRunCaptureActive_5;
        private bool __foxRunRecordMessagePack_5;
        private FoxRunEncoding __foxRunCaptureEncoding_5;
        private float __foxRunCapture_5_0;
        private float __foxRunCapture_5_1;
        private bool __foxRunCaptureActive_6;
        private bool __foxRunRecordMessagePack_6;
        private FoxRunEncoding __foxRunCaptureEncoding_6;
        private ulong __foxRunSequence_6;
        private ulong __foxRunCaptureSequence_6;
        private global::UnityEngine.Vector3 __foxRunCapture_6_0;

        bool IFoxglovePublishCaptureSource.FoxgloveLog_BeginCapture(int topicIndex)
        {
            switch (topicIndex)
            {
                case 0:
                    if (__foxRunCaptureActive_0) return false;
                    try
                    {
                        __foxRunCapture_0_0 = this._samples;
                        if (__foxRunCaptureEncoding_0 == FoxRunEncoding.MessagePack || __foxRunRecordMessagePack_0)
                        {
                            var __payload_0 = __BuildFoxRunMessagePack_0();
                            __foxRunLastMessagePack_0 = __payload_0;
                        }
                        __foxRunCaptureActive_0 = true;
                        return true;
                    }
                    catch
                    {
                        __foxRunCapture_0_0 = default;
                        __foxRunLastMessagePack_0 = null;
                        __foxRunRecordMessagePack_0 = false;
                        __foxRunCaptureEncoding_0 = (FoxRunEncoding)0;
                        __foxRunCaptureActive_0 = false;
                        throw;
                    }
                case 1:
                    if (__foxRunCaptureActive_1) return false;
                    try
                    {
                        __foxRunCapture_1_0 = this._extra;
                        if (__foxRunCaptureEncoding_1 == FoxRunEncoding.MessagePack || __foxRunRecordMessagePack_1)
                        {
                            var __payload_1 = __BuildFoxRunMessagePack_1();
                            __foxRunLastMessagePack_1 = __payload_1;
                        }
                        __foxRunCaptureActive_1 = true;
                        return true;
                    }
                    catch
                    {
                        __foxRunCapture_1_0 = default;
                        __foxRunLastMessagePack_1 = null;
                        __foxRunRecordMessagePack_1 = false;
                        __foxRunCaptureEncoding_1 = (FoxRunEncoding)0;
                        __foxRunCaptureActive_1 = false;
                        throw;
                    }
                case 2:
                    if (__foxRunCaptureActive_2) return false;
                    try
                    {
                        __foxRunCapture_2_0 = this._sampleList;
                        if (__foxRunCaptureEncoding_2 == FoxRunEncoding.MessagePack || __foxRunRecordMessagePack_2)
                        {
                            var __payload_2 = __BuildFoxRunMessagePack_2();
                            __foxRunLastMessagePack_2 = __payload_2;
                        }
                        __foxRunCaptureActive_2 = true;
                        return true;
                    }
                    catch
                    {
                        __foxRunCapture_2_0 = default;
                        __foxRunLastMessagePack_2 = null;
                        __foxRunRecordMessagePack_2 = false;
                        __foxRunCaptureEncoding_2 = (FoxRunEncoding)0;
                        __foxRunCaptureActive_2 = false;
                        throw;
                    }
                case 3:
                    if (__foxRunCaptureActive_3) return false;
                    try
                    {
                        __foxRunCapture_3_0 = this._optionalCount;
                        if (__foxRunCaptureEncoding_3 == FoxRunEncoding.MessagePack || __foxRunRecordMessagePack_3)
                        {
                            var __payload_3 = __BuildFoxRunMessagePack_3();
                            __foxRunLastMessagePack_3 = __payload_3;
                        }
                        __foxRunCaptureActive_3 = true;
                        return true;
                    }
                    catch
                    {
                        __foxRunCapture_3_0 = default;
                        __foxRunLastMessagePack_3 = null;
                        __foxRunRecordMessagePack_3 = false;
                        __foxRunCaptureEncoding_3 = (FoxRunEncoding)0;
                        __foxRunCaptureActive_3 = false;
                        throw;
                    }
                case 4:
                    if (__foxRunCaptureActive_4) return false;
                    try
                    {
                        __foxRunCapture_4_0 = this._trigger;
                        if (__foxRunCaptureEncoding_4 == FoxRunEncoding.MessagePack || __foxRunRecordMessagePack_4)
                        {
                            var __payload_4 = __BuildFoxRunMessagePack_4();
                            __foxRunLastMessagePack_4 = __payload_4;
                        }
                        __foxRunCaptureActive_4 = true;
                        return true;
                    }
                    catch
                    {
                        __foxRunCapture_4_0 = default;
                        __foxRunLastMessagePack_4 = null;
                        __foxRunRecordMessagePack_4 = false;
                        __foxRunCaptureEncoding_4 = (FoxRunEncoding)0;
                        __foxRunCaptureActive_4 = false;
                        throw;
                    }
                case 5:
                    if (__foxRunCaptureActive_5) return false;
                    try
                    {
                        __foxRunCapture_5_0 = this._value;
                        __foxRunCapture_5_1 = this._valueMirror;
                        if (__foxRunCaptureEncoding_5 == FoxRunEncoding.MessagePack || __foxRunRecordMessagePack_5)
                        {
                            var __payload_5 = __BuildFoxRunMessagePack_5();
                            __foxRunLastMessagePack_5 = __payload_5;
                        }
                        __foxRunCaptureActive_5 = true;
                        return true;
                    }
                    catch
                    {
                        __foxRunCapture_5_0 = default;
                        __foxRunCapture_5_1 = default;
                        __foxRunLastMessagePack_5 = null;
                        __foxRunRecordMessagePack_5 = false;
                        __foxRunCaptureEncoding_5 = (FoxRunEncoding)0;
                        __foxRunCaptureActive_5 = false;
                        throw;
                    }
                case 6:
                    if (__foxRunCaptureActive_6) return false;
                    if (__foxRunSequence_6 == ulong.MaxValue) return false;
                    try
                    {
                        __foxRunCapture_6_0 = this._position;
                        __foxRunCaptureSequence_6 = ++__foxRunSequence_6;
                        if (__foxRunCaptureEncoding_6 == FoxRunEncoding.MessagePack || __foxRunRecordMessagePack_6)
                        {
                            var __payload_6 = __BuildFoxRunMessagePack_6();
                            __foxRunLastMessagePack_6 = __payload_6;
                        }
                        __foxRunCaptureActive_6 = true;
                        return true;
                    }
                    catch
                    {
                        __foxRunCapture_6_0 = default;
                        __foxRunCaptureSequence_6 = 0;
                        __foxRunLastMessagePack_6 = null;
                        __foxRunRecordMessagePack_6 = false;
                        __foxRunCaptureEncoding_6 = (FoxRunEncoding)0;
                        __foxRunCaptureActive_6 = false;
                        throw;
                    }
                default: return false;
            }
        }

        void IFoxglovePublishCaptureSource.FoxgloveLog_EndCapture(int topicIndex)
        {
            switch (topicIndex)
            {
                case 0:
                    __foxRunCapture_0_0 = default;
                    __foxRunCaptureActive_0 = false;
                    __foxRunLastMessagePack_0 = null;
                    __foxRunRecordMessagePack_0 = false;
                    __foxRunCaptureEncoding_0 = (FoxRunEncoding)0;
                    break;
                case 1:
                    __foxRunCapture_1_0 = default;
                    __foxRunCaptureActive_1 = false;
                    __foxRunLastMessagePack_1 = null;
                    __foxRunRecordMessagePack_1 = false;
                    __foxRunCaptureEncoding_1 = (FoxRunEncoding)0;
                    break;
                case 2:
                    __foxRunCapture_2_0 = default;
                    __foxRunCaptureActive_2 = false;
                    __foxRunLastMessagePack_2 = null;
                    __foxRunRecordMessagePack_2 = false;
                    __foxRunCaptureEncoding_2 = (FoxRunEncoding)0;
                    break;
                case 3:
                    __foxRunCapture_3_0 = default;
                    __foxRunCaptureActive_3 = false;
                    __foxRunLastMessagePack_3 = null;
                    __foxRunRecordMessagePack_3 = false;
                    __foxRunCaptureEncoding_3 = (FoxRunEncoding)0;
                    break;
                case 4:
                    __foxRunCapture_4_0 = default;
                    __foxRunCaptureActive_4 = false;
                    __foxRunLastMessagePack_4 = null;
                    __foxRunRecordMessagePack_4 = false;
                    __foxRunCaptureEncoding_4 = (FoxRunEncoding)0;
                    break;
                case 5:
                    __foxRunCapture_5_0 = default;
                    __foxRunCapture_5_1 = default;
                    __foxRunCaptureActive_5 = false;
                    __foxRunLastMessagePack_5 = null;
                    __foxRunRecordMessagePack_5 = false;
                    __foxRunCaptureEncoding_5 = (FoxRunEncoding)0;
                    break;
                case 6:
                    __foxRunCapture_6_0 = default;
                    __foxRunCaptureSequence_6 = 0;
                    __foxRunCaptureActive_6 = false;
                    __foxRunLastMessagePack_6 = null;
                    __foxRunRecordMessagePack_6 = false;
                    __foxRunCaptureEncoding_6 = (FoxRunEncoding)0;
                    break;
            }
        }

        bool IFoxglovePublishOriginSource.FoxgloveLog_CanPublishOrigin(int topicIndex, bool explicitTrigger)
        {
            if (explicitTrigger) return true;
            switch (topicIndex)
            {
                case 0: return true;
                case 1: return true;
                case 2: return true;
                case 3: return true;
                case 4: return true;
                case 5: return true;
                case 6: return true;
                default: return false;
            }
        }

        void IFoxRunWebSocketCaptureSource.FoxgloveLog_SetWebSocketEncoding(int topicIndex, FoxRunEncoding encoding)
        {
            switch (topicIndex)
            {
                case 0: __foxRunCaptureEncoding_0 = encoding; break;
                case 1: __foxRunCaptureEncoding_1 = encoding; break;
                case 2: __foxRunCaptureEncoding_2 = encoding; break;
                case 3: __foxRunCaptureEncoding_3 = encoding; break;
                case 4: __foxRunCaptureEncoding_4 = encoding; break;
                case 5: __foxRunCaptureEncoding_5 = encoding; break;
                case 6: __foxRunCaptureEncoding_6 = encoding; break;
            }
        }

        bool IFoxglovePublishRecordingSource.FoxgloveLog_IsRecordingReady(
            int topicIndex, FoxgloveManager mgr, out string reason)
        {
            reason = string.Empty;
            if (mgr == null || mgr.SuppressLivePublishersForReplay) { reason = "MCAP recording is unavailable."; return false; }
            switch (topicIndex)
            {
                case 0:
                    __foxRunRecordMessagePack_0 = mgr.TryPrepareFoxRunMessagePackRecording("/debug/array", out _, out reason);
                    return __foxRunRecordMessagePack_0;
                case 1:
                    __foxRunRecordMessagePack_1 = mgr.TryPrepareFoxRunMessagePackRecording("/debug/extra", out _, out reason);
                    return __foxRunRecordMessagePack_1;
                case 2:
                    __foxRunRecordMessagePack_2 = mgr.TryPrepareFoxRunMessagePackRecording("/debug/list", out _, out reason);
                    return __foxRunRecordMessagePack_2;
                case 3:
                    __foxRunRecordMessagePack_3 = mgr.TryPrepareFoxRunMessagePackRecording("/debug/nullable", out _, out reason);
                    return __foxRunRecordMessagePack_3;
                case 4:
                    __foxRunRecordMessagePack_4 = mgr.TryPrepareFoxRunMessagePackRecording("/debug/trigger", out _, out reason);
                    return __foxRunRecordMessagePack_4;
                case 5:
                    __foxRunRecordMessagePack_5 = mgr.TryPrepareFoxRunMessagePackRecording("/debug/value", out _, out reason);
                    return __foxRunRecordMessagePack_5;
                case 6:
                    __foxRunRecordMessagePack_6 = mgr.TryPrepareFoxRunMessagePackRecording("/debug/vector", out _, out reason);
                    return __foxRunRecordMessagePack_6;
                default: return false;
            }
        }

        bool IFoxglovePublishRecordingSource.FoxgloveLog_RecordCaptured(
            int topicIndex, FoxgloveManager mgr, ulong nowNs, out string reason)
        {
            reason = string.Empty;
            if (mgr == null) return false;
            switch (topicIndex)
            {
                case 0:
                    if (!__foxRunRecordMessagePack_0) { reason = "MessagePack recording was not prepared for this capture."; return false; }
                    return mgr.TryPublishFoxRunMessagePackRecording("/debug/array", __foxRunLastMessagePack_0, nowNs, out reason);
                case 1:
                    if (!__foxRunRecordMessagePack_1) { reason = "MessagePack recording was not prepared for this capture."; return false; }
                    return mgr.TryPublishFoxRunMessagePackRecording("/debug/extra", __foxRunLastMessagePack_1, nowNs, out reason);
                case 2:
                    if (!__foxRunRecordMessagePack_2) { reason = "MessagePack recording was not prepared for this capture."; return false; }
                    return mgr.TryPublishFoxRunMessagePackRecording("/debug/list", __foxRunLastMessagePack_2, nowNs, out reason);
                case 3:
                    if (!__foxRunRecordMessagePack_3) { reason = "MessagePack recording was not prepared for this capture."; return false; }
                    return mgr.TryPublishFoxRunMessagePackRecording("/debug/nullable", __foxRunLastMessagePack_3, nowNs, out reason);
                case 4:
                    if (!__foxRunRecordMessagePack_4) { reason = "MessagePack recording was not prepared for this capture."; return false; }
                    return mgr.TryPublishFoxRunMessagePackRecording("/debug/trigger", __foxRunLastMessagePack_4, nowNs, out reason);
                case 5:
                    if (!__foxRunRecordMessagePack_5) { reason = "MessagePack recording was not prepared for this capture."; return false; }
                    return mgr.TryPublishFoxRunMessagePackRecording("/debug/value", __foxRunLastMessagePack_5, nowNs, out reason);
                case 6:
                    if (!__foxRunRecordMessagePack_6) { reason = "MessagePack recording was not prepared for this capture."; return false; }
                    return mgr.TryPublishFoxRunMessagePackRecording("/debug/vector", __foxRunLastMessagePack_6, nowNs, out reason);
                default: return false;
            }
        }
        [Preserve]
        void IFoxgloveLogSource.FoxgloveLog_Publish(int topicIndex, FoxgloveManager mgr, ulong nowNs)
        {
            switch (topicIndex)
            {
                case 0:
                    if (__foxRunCaptureEncoding_0 == FoxRunEncoding.Protobuf)
                        mgr.PublishProto("/debug/array", "unity2foxglove.foxrun.Unity_FoxgloveSDK_Tests_Fixtures_FoxRunGenerationModelFixture_ec5506f3", __BuildFoxRunProtobuf_0(), nowNs);
                    else if (__foxRunCaptureEncoding_0 == FoxRunEncoding.MessagePack)
                    {
                        var __payload_0 = __foxRunLastMessagePack_0 ?? throw new global::System.InvalidOperationException("Frozen MessagePack capture is unavailable.");
                        mgr.PublishFoxRunMessagePackBytes("/debug/array", __payload_0, nowNs);
                    }
                    else if (__foxRunCaptureEncoding_0 == FoxRunEncoding.JSON)
                        mgr.PublishJson("/debug/array", "", new Dictionary<string, object> { ["samples"] = __foxRunCapture_0_0 }, nowNs);
                    else
                        throw new global::System.InvalidOperationException("Frozen FoxRun publish encoding is unsupported.");
                    break;
                case 1:
                    if (__foxRunCaptureEncoding_1 == FoxRunEncoding.Protobuf)
                        mgr.PublishProto("/debug/extra", "unity2foxglove.foxrun.Unity_FoxgloveSDK_Tests_Fixtures_FoxRunGenerationModelFixture_24e6e6b0", __BuildFoxRunProtobuf_1(), nowNs);
                    else if (__foxRunCaptureEncoding_1 == FoxRunEncoding.MessagePack)
                    {
                        var __payload_1 = __foxRunLastMessagePack_1 ?? throw new global::System.InvalidOperationException("Frozen MessagePack capture is unavailable.");
                        mgr.PublishFoxRunMessagePackBytes("/debug/extra", __payload_1, nowNs);
                    }
                    else if (__foxRunCaptureEncoding_1 == FoxRunEncoding.JSON)
                        mgr.PublishJson("/debug/extra", "", new Dictionary<string, object> { ["extra"] = __foxRunCapture_1_0 }, nowNs);
                    else
                        throw new global::System.InvalidOperationException("Frozen FoxRun publish encoding is unsupported.");
                    break;
                case 2:
                    if (__foxRunCaptureEncoding_2 == FoxRunEncoding.Protobuf)
                        mgr.PublishProto("/debug/list", "unity2foxglove.foxrun.Unity_FoxgloveSDK_Tests_Fixtures_FoxRunGenerationModelFixture_38cbea4e", __BuildFoxRunProtobuf_2(), nowNs);
                    else if (__foxRunCaptureEncoding_2 == FoxRunEncoding.MessagePack)
                    {
                        var __payload_2 = __foxRunLastMessagePack_2 ?? throw new global::System.InvalidOperationException("Frozen MessagePack capture is unavailable.");
                        mgr.PublishFoxRunMessagePackBytes("/debug/list", __payload_2, nowNs);
                    }
                    else if (__foxRunCaptureEncoding_2 == FoxRunEncoding.JSON)
                        mgr.PublishJson("/debug/list", "", new Dictionary<string, object> { ["sampleList"] = __foxRunCapture_2_0 }, nowNs);
                    else
                        throw new global::System.InvalidOperationException("Frozen FoxRun publish encoding is unsupported.");
                    break;
                case 3:
                    if (__foxRunCaptureEncoding_3 == FoxRunEncoding.Protobuf)
                        mgr.PublishProto("/debug/nullable", "unity2foxglove.foxrun.Unity_FoxgloveSDK_Tests_Fixtures_FoxRunGenerationModelFixture_432b270f", __BuildFoxRunProtobuf_3(), nowNs);
                    else if (__foxRunCaptureEncoding_3 == FoxRunEncoding.MessagePack)
                    {
                        var __payload_3 = __foxRunLastMessagePack_3 ?? throw new global::System.InvalidOperationException("Frozen MessagePack capture is unavailable.");
                        mgr.PublishFoxRunMessagePackBytes("/debug/nullable", __payload_3, nowNs);
                    }
                    else if (__foxRunCaptureEncoding_3 == FoxRunEncoding.JSON)
                        mgr.PublishJson("/debug/nullable", "", new Dictionary<string, object> { ["optionalCount"] = __foxRunCapture_3_0 }, nowNs);
                    else
                        throw new global::System.InvalidOperationException("Frozen FoxRun publish encoding is unsupported.");
                    break;
                case 4:
                    if (__foxRunCaptureEncoding_4 == FoxRunEncoding.Protobuf)
                        mgr.PublishProto("/debug/trigger", "unity2foxglove.foxrun.Unity_FoxgloveSDK_Tests_Fixtures_FoxRunGenerationModelFixture_307d8952", __BuildFoxRunProtobuf_4(), nowNs);
                    else if (__foxRunCaptureEncoding_4 == FoxRunEncoding.MessagePack)
                    {
                        var __payload_4 = __foxRunLastMessagePack_4 ?? throw new global::System.InvalidOperationException("Frozen MessagePack capture is unavailable.");
                        mgr.PublishFoxRunMessagePackBytes("/debug/trigger", __payload_4, nowNs);
                    }
                    else if (__foxRunCaptureEncoding_4 == FoxRunEncoding.JSON)
                        mgr.PublishJson("/debug/trigger", "", new Dictionary<string, object> { ["trigger"] = __foxRunCapture_4_0 }, nowNs);
                    else
                        throw new global::System.InvalidOperationException("Frozen FoxRun publish encoding is unsupported.");
                    break;
                case 5:
                    if (__foxRunCaptureEncoding_5 == FoxRunEncoding.Protobuf)
                        mgr.PublishProto("/debug/value", "unity2foxglove.foxrun.Unity_FoxgloveSDK_Tests_Fixtures_FoxRunGenerationModelFixture_7d41f57b", __BuildFoxRunProtobuf_5(), nowNs);
                    else if (__foxRunCaptureEncoding_5 == FoxRunEncoding.MessagePack)
                    {
                        var __payload_5 = __foxRunLastMessagePack_5 ?? throw new global::System.InvalidOperationException("Frozen MessagePack capture is unavailable.");
                        mgr.PublishFoxRunMessagePackBytes("/debug/value", __payload_5, nowNs);
                    }
                    else if (__foxRunCaptureEncoding_5 == FoxRunEncoding.JSON)
                        mgr.PublishJson("/debug/value", "", new Dictionary<string, object> { ["value"] = __foxRunCapture_5_0, ["valueMirror"] = __foxRunCapture_5_1 }, nowNs);
                    else
                        throw new global::System.InvalidOperationException("Frozen FoxRun publish encoding is unsupported.");
                    break;
                case 6:
                    if (__foxRunCaptureEncoding_6 == FoxRunEncoding.Protobuf)
                        mgr.PublishProto("/debug/vector", "unity2foxglove.foxrun.Unity_FoxgloveSDK_Tests_Fixtures_FoxRunGenerationModelFixture_efb474f9", __BuildFoxRunProtobuf_6(), nowNs);
                    else if (__foxRunCaptureEncoding_6 == FoxRunEncoding.MessagePack)
                    {
                        var __payload_6 = __foxRunLastMessagePack_6 ?? throw new global::System.InvalidOperationException("Frozen MessagePack capture is unavailable.");
                        mgr.PublishFoxRunMessagePackBytes("/debug/vector", __payload_6, nowNs);
                    }
                    else if (__foxRunCaptureEncoding_6 == FoxRunEncoding.JSON)
                        mgr.PublishJson("/debug/vector", "", new Dictionary<string, object> { ["position"] = new Dictionary<string, object> { ["x"] = __foxRunCapture_6_0.x, ["y"] = __foxRunCapture_6_0.y, ["z"] = __foxRunCapture_6_0.z } }, nowNs);
                    else
                        throw new global::System.InvalidOperationException("Frozen FoxRun publish encoding is unsupported.");
                    break;
            }
        }

        private byte[] __BuildFoxRunJson_0()
        {
            var __json = new global::System.Text.StringBuilder(128);
            __WriteFoxRunJson_0(__json);
            return global::System.Text.Encoding.UTF8.GetBytes(__json.ToString());
        }

        private void __WriteFoxRunJson_0(global::System.Text.StringBuilder __json)
        {
            __json.Append('{');
            __json.Append("\"samples\":");
            if (__foxRunCapture_0_0 == null)
            {
                __json.Append("null");
            }
            else
            {
                __json.Append('[');
                for (int __foxRunIndex_0 = 0; __foxRunIndex_0 < __foxRunCapture_0_0.Length; __foxRunIndex_0++)
                {
                    if (__foxRunIndex_0 > 0) __json.Append(',');
                    if (float.IsNaN(__foxRunCapture_0_0[__foxRunIndex_0]) || float.IsInfinity(__foxRunCapture_0_0[__foxRunIndex_0])) __json.Append("null"); else __json.Append(__foxRunCapture_0_0[__foxRunIndex_0].ToString("R", global::System.Globalization.CultureInfo.InvariantCulture));
                }
                __json.Append(']');
            }
            __json.Append('}');
        }

        private byte[] __BuildFoxRunJson_1()
        {
            var __json = new global::System.Text.StringBuilder(128);
            __WriteFoxRunJson_1(__json);
            return global::System.Text.Encoding.UTF8.GetBytes(__json.ToString());
        }

        private void __WriteFoxRunJson_1(global::System.Text.StringBuilder __json)
        {
            __json.Append('{');
            __json.Append("\"extra\":");
            __AppendFoxRunJsonString(__json, __foxRunCapture_1_0);
            __json.Append('}');
        }

        private byte[] __BuildFoxRunJson_2()
        {
            var __json = new global::System.Text.StringBuilder(128);
            __WriteFoxRunJson_2(__json);
            return global::System.Text.Encoding.UTF8.GetBytes(__json.ToString());
        }

        private void __WriteFoxRunJson_2(global::System.Text.StringBuilder __json)
        {
            __json.Append('{');
            __json.Append("\"sampleList\":");
            if (__foxRunCapture_2_0 == null)
            {
                __json.Append("null");
            }
            else
            {
                __json.Append('[');
                for (int __foxRunIndex_0 = 0; __foxRunIndex_0 < __foxRunCapture_2_0.Count; __foxRunIndex_0++)
                {
                    if (__foxRunIndex_0 > 0) __json.Append(',');
                    if (float.IsNaN(__foxRunCapture_2_0[__foxRunIndex_0]) || float.IsInfinity(__foxRunCapture_2_0[__foxRunIndex_0])) __json.Append("null"); else __json.Append(__foxRunCapture_2_0[__foxRunIndex_0].ToString("R", global::System.Globalization.CultureInfo.InvariantCulture));
                }
                __json.Append(']');
            }
            __json.Append('}');
        }

        private byte[] __BuildFoxRunJson_3()
        {
            var __json = new global::System.Text.StringBuilder(128);
            __WriteFoxRunJson_3(__json);
            return global::System.Text.Encoding.UTF8.GetBytes(__json.ToString());
        }

        private void __WriteFoxRunJson_3(global::System.Text.StringBuilder __json)
        {
            __json.Append('{');
            __json.Append("\"optionalCount\":");
            if (__foxRunCapture_3_0 == null) __json.Append("null"); else __json.Append(__foxRunCapture_3_0.Value.ToString(global::System.Globalization.CultureInfo.InvariantCulture));
            __json.Append('}');
        }

        private byte[] __BuildFoxRunJson_4()
        {
            var __json = new global::System.Text.StringBuilder(128);
            __WriteFoxRunJson_4(__json);
            return global::System.Text.Encoding.UTF8.GetBytes(__json.ToString());
        }

        private void __WriteFoxRunJson_4(global::System.Text.StringBuilder __json)
        {
            __json.Append('{');
            __json.Append("\"trigger\":");
            __json.Append(__foxRunCapture_4_0.ToString(global::System.Globalization.CultureInfo.InvariantCulture));
            __json.Append('}');
        }

        private byte[] __BuildFoxRunJson_5()
        {
            var __json = new global::System.Text.StringBuilder(128);
            __WriteFoxRunJson_5(__json);
            return global::System.Text.Encoding.UTF8.GetBytes(__json.ToString());
        }

        private void __WriteFoxRunJson_5(global::System.Text.StringBuilder __json)
        {
            __json.Append('{');
            __json.Append("\"value\":");
            if (float.IsNaN(__foxRunCapture_5_0) || float.IsInfinity(__foxRunCapture_5_0)) __json.Append("null"); else __json.Append(__foxRunCapture_5_0.ToString("R", global::System.Globalization.CultureInfo.InvariantCulture));
            __json.Append(",\"valueMirror\":");
            if (float.IsNaN(__foxRunCapture_5_1) || float.IsInfinity(__foxRunCapture_5_1)) __json.Append("null"); else __json.Append(__foxRunCapture_5_1.ToString("R", global::System.Globalization.CultureInfo.InvariantCulture));
            __json.Append('}');
        }

        private byte[] __BuildFoxRunJson_6()
        {
            var __json = new global::System.Text.StringBuilder(128);
            __WriteFoxRunJson_6(__json);
            return global::System.Text.Encoding.UTF8.GetBytes(__json.ToString());
        }

        private void __WriteFoxRunJson_6(global::System.Text.StringBuilder __json)
        {
            __json.Append('{');
            __json.Append("\"position\":");
            __json.Append('{');
            __json.Append("\"x\":");
            if (float.IsNaN(__foxRunCapture_6_0.x) || float.IsInfinity(__foxRunCapture_6_0.x)) __json.Append("null"); else __json.Append(__foxRunCapture_6_0.x.ToString("R", global::System.Globalization.CultureInfo.InvariantCulture));
            __json.Append(",\"y\":");
            if (float.IsNaN(__foxRunCapture_6_0.y) || float.IsInfinity(__foxRunCapture_6_0.y)) __json.Append("null"); else __json.Append(__foxRunCapture_6_0.y.ToString("R", global::System.Globalization.CultureInfo.InvariantCulture));
            __json.Append(",\"z\":");
            if (float.IsNaN(__foxRunCapture_6_0.z) || float.IsInfinity(__foxRunCapture_6_0.z)) __json.Append("null"); else __json.Append(__foxRunCapture_6_0.z.ToString("R", global::System.Globalization.CultureInfo.InvariantCulture));
            __json.Append('}');
            __json.Append('}');
        }

        private static void __AppendFoxRunJsonString(global::System.Text.StringBuilder __json, string value)
        {
            if (value == null)
            {
                __json.Append("null");
                return;
            }
            __json.Append('\"');
            for (int __i = 0; __i < value.Length; __i++)
            {
                var __c = value[__i];
                switch (__c)
                {
                    case '\"': __json.Append("\\\""); break;
                    case '\\': __json.Append("\\\\"); break;
                    case '\b': __json.Append("\\b"); break;
                    case '\f': __json.Append("\\f"); break;
                    case '\n': __json.Append("\\n"); break;
                    case '\r': __json.Append("\\r"); break;
                    case '\t': __json.Append("\\t"); break;
                    default:
                        if (__c < ' ' || global::System.Char.IsSurrogate(__c))
                            __json.Append("\\u").Append(((int)__c).ToString("x4", global::System.Globalization.CultureInfo.InvariantCulture));
                        else
                            __json.Append(__c);
                        break;
                }
            }
            __json.Append('\"');
        }

        private byte[] __BuildFoxRunProtobuf_0()
        {
            var __payload = new global::System.Collections.Generic.List<byte>(64);
            if (__foxRunCapture_0_0 != null)
            {
                foreach (var __item in __foxRunCapture_0_0)
                    FoxRunProtobufWire.WriteFloat(__payload, 186546222, __item);
            }
            return __payload.ToArray();
        }

        private byte[] __BuildFoxRunProtobuf_1()
        {
            var __payload = new global::System.Collections.Generic.List<byte>(64);
            FoxRunProtobufWire.WriteString(__payload, 461206746, __foxRunCapture_1_0);
            return __payload.ToArray();
        }

        private byte[] __BuildFoxRunProtobuf_2()
        {
            var __payload = new global::System.Collections.Generic.List<byte>(64);
            if (__foxRunCapture_2_0 != null)
            {
                foreach (var __item in __foxRunCapture_2_0)
                    FoxRunProtobufWire.WriteFloat(__payload, 514787135, __item);
            }
            return __payload.ToArray();
        }

        private byte[] __BuildFoxRunProtobuf_3()
        {
            var __payload = new global::System.Collections.Generic.List<byte>(64);
            if (__foxRunCapture_3_0.HasValue)
            {
                FoxRunProtobufWire.WriteInt32(__payload, 72755912, __foxRunCapture_3_0.Value);
            }
            return __payload.ToArray();
        }

        private byte[] __BuildFoxRunProtobuf_4()
        {
            var __payload = new global::System.Collections.Generic.List<byte>(64);
            FoxRunProtobufWire.WriteInt32(__payload, 392378020, __foxRunCapture_4_0);
            return __payload.ToArray();
        }

        private byte[] __BuildFoxRunProtobuf_5()
        {
            var __payload = new global::System.Collections.Generic.List<byte>(64);
            FoxRunProtobufWire.WriteFloat(__payload, 467028584, __foxRunCapture_5_0);
            FoxRunProtobufWire.WriteFloat(__payload, 363099991, __foxRunCapture_5_1);
            return __payload.ToArray();
        }

        private byte[] __BuildFoxRunProtobuf_6()
        {
            var __payload = new global::System.Collections.Generic.List<byte>(64);
            FoxRunProtobufWire.WriteVector3(__payload, 39083297, __foxRunCapture_6_0);
            return __payload.ToArray();
        }
        private byte[] __foxRunLastMessagePack_0;

        private byte[] __BuildFoxRunMessagePack_0()
        {
            using (var __writer = new global::Unity.FoxgloveSDK.Schemas.MsgPack.FoxgloveMsgPackWriter())
            {
                __writer.WriteMapHeader(1);
                __writer.WriteString("samples");
                if (__foxRunCapture_0_0 == null)
                {
                    __writer.WriteNil();
                }
                else
                {
                    var __count_0 = __foxRunCapture_0_0.Length;
                    __writer.WriteArrayHeader(__count_0);
                    for (var __index_0 = 0; __index_0 < __count_0; __index_0++)
                    {
                        __writer.WriteFloat(__foxRunCapture_0_0[__index_0]);
                    }
                }
                return __writer.ToArray();
            }
        }
        private byte[] __foxRunLastMessagePack_1;

        private byte[] __BuildFoxRunMessagePack_1()
        {
            using (var __writer = new global::Unity.FoxgloveSDK.Schemas.MsgPack.FoxgloveMsgPackWriter())
            {
                __writer.WriteMapHeader(1);
                __writer.WriteString("extra");
                __writer.WriteString(__foxRunCapture_1_0);
                return __writer.ToArray();
            }
        }
        private byte[] __foxRunLastMessagePack_2;

        private byte[] __BuildFoxRunMessagePack_2()
        {
            using (var __writer = new global::Unity.FoxgloveSDK.Schemas.MsgPack.FoxgloveMsgPackWriter())
            {
                __writer.WriteMapHeader(1);
                __writer.WriteString("sampleList");
                if (__foxRunCapture_2_0 == null)
                {
                    __writer.WriteNil();
                }
                else
                {
                    var __count_0 = __foxRunCapture_2_0.Count;
                    __writer.WriteArrayHeader(__count_0);
                    for (var __index_0 = 0; __index_0 < __count_0; __index_0++)
                    {
                        __writer.WriteFloat(__foxRunCapture_2_0[__index_0]);
                    }
                }
                return __writer.ToArray();
            }
        }
        private byte[] __foxRunLastMessagePack_3;

        private byte[] __BuildFoxRunMessagePack_3()
        {
            using (var __writer = new global::Unity.FoxgloveSDK.Schemas.MsgPack.FoxgloveMsgPackWriter())
            {
                __writer.WriteMapHeader(1);
                __writer.WriteString("optionalCount");
                if (!__foxRunCapture_3_0.HasValue)
                {
                    __writer.WriteNil();
                }
                else
                {
                    __writer.WriteInt32((int)__foxRunCapture_3_0.Value);
                }
                return __writer.ToArray();
            }
        }
        private byte[] __foxRunLastMessagePack_4;

        private byte[] __BuildFoxRunMessagePack_4()
        {
            using (var __writer = new global::Unity.FoxgloveSDK.Schemas.MsgPack.FoxgloveMsgPackWriter())
            {
                __writer.WriteMapHeader(1);
                __writer.WriteString("trigger");
                __writer.WriteInt32((int)__foxRunCapture_4_0);
                return __writer.ToArray();
            }
        }
        private byte[] __foxRunLastMessagePack_5;

        private byte[] __BuildFoxRunMessagePack_5()
        {
            using (var __writer = new global::Unity.FoxgloveSDK.Schemas.MsgPack.FoxgloveMsgPackWriter())
            {
                __writer.WriteMapHeader(2);
                __writer.WriteString("value");
                __writer.WriteFloat(__foxRunCapture_5_0);
                __writer.WriteString("valueMirror");
                __writer.WriteFloat(__foxRunCapture_5_1);
                return __writer.ToArray();
            }
        }
        private byte[] __foxRunLastMessagePack_6;

        private byte[] __BuildFoxRunMessagePack_6()
        {
            using (var __writer = new global::Unity.FoxgloveSDK.Schemas.MsgPack.FoxgloveMsgPackWriter())
            {
                __writer.WriteMapHeader(1);
                __writer.WriteString("position");
                __WriteFoxRunMessagePackObject_0(__writer, __foxRunCapture_6_0);
                return __writer.ToArray();
            }
        }

        private static void __WriteFoxRunMessagePackObject_0(
            global::Unity.FoxgloveSDK.Schemas.MsgPack.FoxgloveMsgPackWriter __writer,
            global::UnityEngine.Vector3 __value)
        {
            __writer.WriteMapHeader(3);
            __writer.WriteString("x");
            __writer.WriteFloat(__value.x);
            __writer.WriteString("y");
            __writer.WriteFloat(__value.y);
            __writer.WriteString("z");
            __writer.WriteFloat(__value.z);
        }

        [Preserve]
        bool IFoxgloveTopicObserverSource.FoxgloveLog_HasObservers(int topicIndex, FoxTopicBus bus)
        {
            if (bus == null)
                return false;
            switch (topicIndex)
            {
                case 0: return bus.HasObservers<byte[]>("/debug/array") || bus.HasObservers<Dictionary<string, object>>("/debug/array");
                case 1: return bus.HasObservers<byte[]>("/debug/extra") || bus.HasObservers<Dictionary<string, object>>("/debug/extra");
                case 2: return bus.HasObservers<byte[]>("/debug/list") || bus.HasObservers<Dictionary<string, object>>("/debug/list");
                case 3: return bus.HasObservers<byte[]>("/debug/nullable") || bus.HasObservers<Dictionary<string, object>>("/debug/nullable");
                case 4: return bus.HasObservers<byte[]>("/debug/trigger") || bus.HasObservers<Dictionary<string, object>>("/debug/trigger");
                case 5: return bus.HasObservers<byte[]>("/debug/value") || bus.HasObservers<Dictionary<string, object>>("/debug/value");
                case 6: return bus.HasObservers<byte[]>("/debug/vector") || bus.HasObservers<Dictionary<string, object>>("/debug/vector");
                default: return false;
            }
        }

        [Preserve]
        void IFoxgloveTopicObserverSource.FoxgloveLog_PublishCapturedToObservers(int topicIndex, FoxTopicBus bus, ulong nowNs)
        {
            if (bus == null)
                return;
            switch (topicIndex)
            {
                case 0:
                    if (__foxRunCaptureEncoding_0 == FoxRunEncoding.MessagePack)
                    {
                        var __foxRunObserverPayload_0 = __foxRunLastMessagePack_0;
                        var __foxRunObserverContract_0 = ((IFoxgloveTopicContractSource)this).FoxgloveLog_GetContract(0).ForWireEncoding(FoxRunEncoding.MessagePack);
                        bus.PublishToObservers<byte[]>(__foxRunObserverContract_0, nowNs, in __foxRunObserverPayload_0, __foxRunOrigin, 0UL);
                    }
                    else
                    {
                        var __foxRunObserverPayload_0 = new Dictionary<string, object> { ["samples"] = __foxRunCapture_0_0 };
                        bus.PublishToObservers<Dictionary<string, object>>(((IFoxgloveTopicContractSource)this).FoxgloveLog_GetContract(0), nowNs, in __foxRunObserverPayload_0, __foxRunOrigin, 0UL);
                    }
                    break;
                case 1:
                    if (__foxRunCaptureEncoding_1 == FoxRunEncoding.MessagePack)
                    {
                        var __foxRunObserverPayload_1 = __foxRunLastMessagePack_1;
                        var __foxRunObserverContract_1 = ((IFoxgloveTopicContractSource)this).FoxgloveLog_GetContract(1).ForWireEncoding(FoxRunEncoding.MessagePack);
                        bus.PublishToObservers<byte[]>(__foxRunObserverContract_1, nowNs, in __foxRunObserverPayload_1, __foxRunOrigin, 0UL);
                    }
                    else
                    {
                        var __foxRunObserverPayload_1 = new Dictionary<string, object> { ["extra"] = __foxRunCapture_1_0 };
                        bus.PublishToObservers<Dictionary<string, object>>(((IFoxgloveTopicContractSource)this).FoxgloveLog_GetContract(1), nowNs, in __foxRunObserverPayload_1, __foxRunOrigin, 0UL);
                    }
                    break;
                case 2:
                    if (__foxRunCaptureEncoding_2 == FoxRunEncoding.MessagePack)
                    {
                        var __foxRunObserverPayload_2 = __foxRunLastMessagePack_2;
                        var __foxRunObserverContract_2 = ((IFoxgloveTopicContractSource)this).FoxgloveLog_GetContract(2).ForWireEncoding(FoxRunEncoding.MessagePack);
                        bus.PublishToObservers<byte[]>(__foxRunObserverContract_2, nowNs, in __foxRunObserverPayload_2, __foxRunOrigin, 0UL);
                    }
                    else
                    {
                        var __foxRunObserverPayload_2 = new Dictionary<string, object> { ["sampleList"] = __foxRunCapture_2_0 };
                        bus.PublishToObservers<Dictionary<string, object>>(((IFoxgloveTopicContractSource)this).FoxgloveLog_GetContract(2), nowNs, in __foxRunObserverPayload_2, __foxRunOrigin, 0UL);
                    }
                    break;
                case 3:
                    if (__foxRunCaptureEncoding_3 == FoxRunEncoding.MessagePack)
                    {
                        var __foxRunObserverPayload_3 = __foxRunLastMessagePack_3;
                        var __foxRunObserverContract_3 = ((IFoxgloveTopicContractSource)this).FoxgloveLog_GetContract(3).ForWireEncoding(FoxRunEncoding.MessagePack);
                        bus.PublishToObservers<byte[]>(__foxRunObserverContract_3, nowNs, in __foxRunObserverPayload_3, __foxRunOrigin, 0UL);
                    }
                    else
                    {
                        var __foxRunObserverPayload_3 = new Dictionary<string, object> { ["optionalCount"] = __foxRunCapture_3_0 };
                        bus.PublishToObservers<Dictionary<string, object>>(((IFoxgloveTopicContractSource)this).FoxgloveLog_GetContract(3), nowNs, in __foxRunObserverPayload_3, __foxRunOrigin, 0UL);
                    }
                    break;
                case 4:
                    if (__foxRunCaptureEncoding_4 == FoxRunEncoding.MessagePack)
                    {
                        var __foxRunObserverPayload_4 = __foxRunLastMessagePack_4;
                        var __foxRunObserverContract_4 = ((IFoxgloveTopicContractSource)this).FoxgloveLog_GetContract(4).ForWireEncoding(FoxRunEncoding.MessagePack);
                        bus.PublishToObservers<byte[]>(__foxRunObserverContract_4, nowNs, in __foxRunObserverPayload_4, __foxRunOrigin, 0UL);
                    }
                    else
                    {
                        var __foxRunObserverPayload_4 = new Dictionary<string, object> { ["trigger"] = __foxRunCapture_4_0 };
                        bus.PublishToObservers<Dictionary<string, object>>(((IFoxgloveTopicContractSource)this).FoxgloveLog_GetContract(4), nowNs, in __foxRunObserverPayload_4, __foxRunOrigin, 0UL);
                    }
                    break;
                case 5:
                    if (__foxRunCaptureEncoding_5 == FoxRunEncoding.MessagePack)
                    {
                        var __foxRunObserverPayload_5 = __foxRunLastMessagePack_5;
                        var __foxRunObserverContract_5 = ((IFoxgloveTopicContractSource)this).FoxgloveLog_GetContract(5).ForWireEncoding(FoxRunEncoding.MessagePack);
                        bus.PublishToObservers<byte[]>(__foxRunObserverContract_5, nowNs, in __foxRunObserverPayload_5, __foxRunOrigin, 0UL);
                    }
                    else
                    {
                        var __foxRunObserverPayload_5 = new Dictionary<string, object> { ["value"] = __foxRunCapture_5_0, ["valueMirror"] = __foxRunCapture_5_1 };
                        bus.PublishToObservers<Dictionary<string, object>>(((IFoxgloveTopicContractSource)this).FoxgloveLog_GetContract(5), nowNs, in __foxRunObserverPayload_5, __foxRunOrigin, 0UL);
                    }
                    break;
                case 6:
                    if (__foxRunCaptureEncoding_6 == FoxRunEncoding.MessagePack)
                    {
                        var __foxRunObserverPayload_6 = __foxRunLastMessagePack_6;
                        var __foxRunObserverContract_6 = ((IFoxgloveTopicContractSource)this).FoxgloveLog_GetContract(6).ForWireEncoding(FoxRunEncoding.MessagePack);
                        bus.PublishToObservers<byte[]>(__foxRunObserverContract_6, nowNs, in __foxRunObserverPayload_6, __foxRunOrigin, 0UL);
                    }
                    else
                    {
                        var __foxRunObserverPayload_6 = new Dictionary<string, object> { ["position"] = new Dictionary<string, object> { ["x"] = __foxRunCapture_6_0.x, ["y"] = __foxRunCapture_6_0.y, ["z"] = __foxRunCapture_6_0.z } };
                        bus.PublishToObservers<Dictionary<string, object>>(((IFoxgloveTopicContractSource)this).FoxgloveLog_GetContract(6), nowNs, in __foxRunObserverPayload_6, __foxRunOrigin, 0UL);
                    }
                    break;
            }
        }

        [Preserve]
        void IFoxgloveTopicBusSource.FoxgloveLog_PublishToBus(int topicIndex, FoxTopicBus bus, ulong nowNs)
        {
            if (bus == null)
                return;
            switch (topicIndex)
            {
                case 0:
                    if (!bus.HasSubscribers("/debug/array")) break;
                    if (__foxRunCaptureEncoding_0 == FoxRunEncoding.MessagePack)
                    {
                        var __payload_0 = __foxRunLastMessagePack_0;
                        var __foxRunBusContract_0 = ((IFoxgloveTopicContractSource)this).FoxgloveLog_GetContract(0).ForWireEncoding(FoxRunEncoding.MessagePack);
                        bus.Publish(__foxRunBusContract_0, nowNs, in __payload_0, __foxRunOrigin);
                    }
                    else
                    {
                        bus.Publish(((IFoxgloveTopicContractSource)this).FoxgloveLog_GetContract(0), nowNs, new Dictionary<string, object> { ["samples"] = __foxRunCapture_0_0 }, __foxRunOrigin);
                    }
                    break;
                case 1:
                    if (!bus.HasSubscribers("/debug/extra")) break;
                    if (__foxRunCaptureEncoding_1 == FoxRunEncoding.MessagePack)
                    {
                        var __payload_1 = __foxRunLastMessagePack_1;
                        var __foxRunBusContract_1 = ((IFoxgloveTopicContractSource)this).FoxgloveLog_GetContract(1).ForWireEncoding(FoxRunEncoding.MessagePack);
                        bus.Publish(__foxRunBusContract_1, nowNs, in __payload_1, __foxRunOrigin);
                    }
                    else
                    {
                        bus.Publish(((IFoxgloveTopicContractSource)this).FoxgloveLog_GetContract(1), nowNs, new Dictionary<string, object> { ["extra"] = __foxRunCapture_1_0 }, __foxRunOrigin);
                    }
                    break;
                case 2:
                    if (!bus.HasSubscribers("/debug/list")) break;
                    if (__foxRunCaptureEncoding_2 == FoxRunEncoding.MessagePack)
                    {
                        var __payload_2 = __foxRunLastMessagePack_2;
                        var __foxRunBusContract_2 = ((IFoxgloveTopicContractSource)this).FoxgloveLog_GetContract(2).ForWireEncoding(FoxRunEncoding.MessagePack);
                        bus.Publish(__foxRunBusContract_2, nowNs, in __payload_2, __foxRunOrigin);
                    }
                    else
                    {
                        bus.Publish(((IFoxgloveTopicContractSource)this).FoxgloveLog_GetContract(2), nowNs, new Dictionary<string, object> { ["sampleList"] = __foxRunCapture_2_0 }, __foxRunOrigin);
                    }
                    break;
                case 3:
                    if (!bus.HasSubscribers("/debug/nullable")) break;
                    if (__foxRunCaptureEncoding_3 == FoxRunEncoding.MessagePack)
                    {
                        var __payload_3 = __foxRunLastMessagePack_3;
                        var __foxRunBusContract_3 = ((IFoxgloveTopicContractSource)this).FoxgloveLog_GetContract(3).ForWireEncoding(FoxRunEncoding.MessagePack);
                        bus.Publish(__foxRunBusContract_3, nowNs, in __payload_3, __foxRunOrigin);
                    }
                    else
                    {
                        bus.Publish(((IFoxgloveTopicContractSource)this).FoxgloveLog_GetContract(3), nowNs, new Dictionary<string, object> { ["optionalCount"] = __foxRunCapture_3_0 }, __foxRunOrigin);
                    }
                    break;
                case 4:
                    if (!bus.HasSubscribers("/debug/trigger")) break;
                    if (__foxRunCaptureEncoding_4 == FoxRunEncoding.MessagePack)
                    {
                        var __payload_4 = __foxRunLastMessagePack_4;
                        var __foxRunBusContract_4 = ((IFoxgloveTopicContractSource)this).FoxgloveLog_GetContract(4).ForWireEncoding(FoxRunEncoding.MessagePack);
                        bus.Publish(__foxRunBusContract_4, nowNs, in __payload_4, __foxRunOrigin);
                    }
                    else
                    {
                        bus.Publish(((IFoxgloveTopicContractSource)this).FoxgloveLog_GetContract(4), nowNs, new Dictionary<string, object> { ["trigger"] = __foxRunCapture_4_0 }, __foxRunOrigin);
                    }
                    break;
                case 5:
                    if (!bus.HasSubscribers("/debug/value")) break;
                    if (__foxRunCaptureEncoding_5 == FoxRunEncoding.MessagePack)
                    {
                        var __payload_5 = __foxRunLastMessagePack_5;
                        var __foxRunBusContract_5 = ((IFoxgloveTopicContractSource)this).FoxgloveLog_GetContract(5).ForWireEncoding(FoxRunEncoding.MessagePack);
                        bus.Publish(__foxRunBusContract_5, nowNs, in __payload_5, __foxRunOrigin);
                    }
                    else
                    {
                        bus.Publish(((IFoxgloveTopicContractSource)this).FoxgloveLog_GetContract(5), nowNs, new Dictionary<string, object> { ["value"] = __foxRunCapture_5_0, ["valueMirror"] = __foxRunCapture_5_1 }, __foxRunOrigin);
                    }
                    break;
                case 6:
                    if (!bus.HasSubscribers("/debug/vector")) break;
                    if (__foxRunCaptureEncoding_6 == FoxRunEncoding.MessagePack)
                    {
                        var __payload_6 = __foxRunLastMessagePack_6;
                        var __foxRunBusContract_6 = ((IFoxgloveTopicContractSource)this).FoxgloveLog_GetContract(6).ForWireEncoding(FoxRunEncoding.MessagePack);
                        bus.Publish(__foxRunBusContract_6, nowNs, in __payload_6, __foxRunOrigin);
                    }
                    else
                    {
                        bus.Publish(((IFoxgloveTopicContractSource)this).FoxgloveLog_GetContract(6), nowNs, new Dictionary<string, object> { ["position"] = new Dictionary<string, object> { ["x"] = __foxRunCapture_6_0.x, ["y"] = __foxRunCapture_6_0.y, ["z"] = __foxRunCapture_6_0.z } }, __foxRunOrigin);
                    }
                    break;
            }
        }

        [Preserve]
        void IFoxgloveTopicSinkSource.FoxgloveLog_PublishToSinks(int topicIndex, FoxTopicSinkRouter router, ulong nowNs)
        {
            if (router == null || !router.HasSinks)
                return;
            switch (topicIndex)
            {
                case 0:
                    if (__foxRunCaptureEncoding_0 == FoxRunEncoding.MessagePack)
                        router.PublishCompatible(((IFoxgloveTopicContractSource)this).FoxgloveLog_GetContract(0), FoxRunEncoding.MessagePack, nowNs, __foxRunLastMessagePack_0, __foxRunOrigin);
                    else
                    {
                        var __sink_0 = __BuildFoxRunJson_0();
                        router.PublishCompatible(((IFoxgloveTopicContractSource)this).FoxgloveLog_GetContract(0), FoxRunEncoding.JSON, nowNs, __sink_0, __foxRunOrigin);
                    }
                    break;
                case 1:
                    if (__foxRunCaptureEncoding_1 == FoxRunEncoding.MessagePack)
                        router.PublishCompatible(((IFoxgloveTopicContractSource)this).FoxgloveLog_GetContract(1), FoxRunEncoding.MessagePack, nowNs, __foxRunLastMessagePack_1, __foxRunOrigin);
                    else
                    {
                        var __sink_1 = __BuildFoxRunJson_1();
                        router.PublishCompatible(((IFoxgloveTopicContractSource)this).FoxgloveLog_GetContract(1), FoxRunEncoding.JSON, nowNs, __sink_1, __foxRunOrigin);
                    }
                    break;
                case 2:
                    if (__foxRunCaptureEncoding_2 == FoxRunEncoding.MessagePack)
                        router.PublishCompatible(((IFoxgloveTopicContractSource)this).FoxgloveLog_GetContract(2), FoxRunEncoding.MessagePack, nowNs, __foxRunLastMessagePack_2, __foxRunOrigin);
                    else
                    {
                        var __sink_2 = __BuildFoxRunJson_2();
                        router.PublishCompatible(((IFoxgloveTopicContractSource)this).FoxgloveLog_GetContract(2), FoxRunEncoding.JSON, nowNs, __sink_2, __foxRunOrigin);
                    }
                    break;
                case 3:
                    if (__foxRunCaptureEncoding_3 == FoxRunEncoding.MessagePack)
                        router.PublishCompatible(((IFoxgloveTopicContractSource)this).FoxgloveLog_GetContract(3), FoxRunEncoding.MessagePack, nowNs, __foxRunLastMessagePack_3, __foxRunOrigin);
                    else
                    {
                        var __sink_3 = __BuildFoxRunJson_3();
                        router.PublishCompatible(((IFoxgloveTopicContractSource)this).FoxgloveLog_GetContract(3), FoxRunEncoding.JSON, nowNs, __sink_3, __foxRunOrigin);
                    }
                    break;
                case 4:
                    if (__foxRunCaptureEncoding_4 == FoxRunEncoding.MessagePack)
                        router.PublishCompatible(((IFoxgloveTopicContractSource)this).FoxgloveLog_GetContract(4), FoxRunEncoding.MessagePack, nowNs, __foxRunLastMessagePack_4, __foxRunOrigin);
                    else
                    {
                        var __sink_4 = __BuildFoxRunJson_4();
                        router.PublishCompatible(((IFoxgloveTopicContractSource)this).FoxgloveLog_GetContract(4), FoxRunEncoding.JSON, nowNs, __sink_4, __foxRunOrigin);
                    }
                    break;
                case 5:
                    if (__foxRunCaptureEncoding_5 == FoxRunEncoding.MessagePack)
                        router.PublishCompatible(((IFoxgloveTopicContractSource)this).FoxgloveLog_GetContract(5), FoxRunEncoding.MessagePack, nowNs, __foxRunLastMessagePack_5, __foxRunOrigin);
                    else
                    {
                        var __sink_5 = __BuildFoxRunJson_5();
                        router.PublishCompatible(((IFoxgloveTopicContractSource)this).FoxgloveLog_GetContract(5), FoxRunEncoding.JSON, nowNs, __sink_5, __foxRunOrigin);
                    }
                    break;
                case 6:
                    if (__foxRunCaptureEncoding_6 == FoxRunEncoding.MessagePack)
                        router.PublishCompatible(((IFoxgloveTopicContractSource)this).FoxgloveLog_GetContract(6), FoxRunEncoding.MessagePack, nowNs, __foxRunLastMessagePack_6, __foxRunOrigin);
                    else
                    {
                        var __sink_6 = __BuildFoxRunJson_6();
                        router.PublishCompatible(((IFoxgloveTopicContractSource)this).FoxgloveLog_GetContract(6), FoxRunEncoding.JSON, nowNs, __sink_6, __foxRunOrigin);
                    }
                    break;
            }
        }

        public bool FoxRun_Publish_trigger()
        {
            var published = false;
            published |= FoxgloveLogHub.Trigger(this, 4);
            return published;
        }

        public bool FoxRun_PublishAll()
        {
            var published = false;
            published |= FoxgloveLogHub.Trigger(this, 4);
            return published;
        }
        private float[] __FoxRunRead_samples_ee5552edf7db96a9() => __foxRunCapture_0_0;

        private string __FoxRunRead_extra_d38bfc70d930f492() => __foxRunCapture_1_0;

        private System.Collections.Generic.List<float> __FoxRunRead_sampleList_3b2b8000796afd9a() => __foxRunCapture_2_0;

        private int? __FoxRunRead_optionalCount_4e5493976d91a131() => __foxRunCapture_3_0;

        private int __FoxRunRead_trigger_342c76e698075d00() => __foxRunCapture_4_0;

        private float __FoxRunRead_value_b2ddfbbed3a8dbb3() => __foxRunCapture_5_0;

        private float __FoxRunRead_valueMirror_a81a546626512ef6() => __foxRunCapture_5_1;

        private UnityEngine.Vector3 __FoxRunRead_position_fa1c12bd59505221() => __foxRunCapture_6_0;


        private bool __hasLast_0;
        private double __lastPublishSec_0;
        private float[] __last_0_0;
        private bool __hasLast_2;
        private double __lastPublishSec_2;
        private System.Collections.Generic.List<float> __last_2_0;
        private bool __hasLast_3;
        private double __lastPublishSec_3;
        private int? __last_3_0;
        private bool __hasLast_5;
        private double __lastPublishSec_5;
        private float __last_5_0;
        private float __last_5_1;
        private bool __hasLast_6;
        private double __lastPublishSec_6;
        private UnityEngine.Vector3 __last_6_0;

        bool IFoxgloveLogPolicySource.FoxgloveLog_ShouldPublish(int topicIndex, double nowSec)
        {
            bool changed;
            switch (topicIndex)
            {
                case 0:
                    changed = !__hasLast_0;
                    if (!changed) changed = !EqualityComparer<float[]>.Default.Equals(this._samples, __last_0_0);
                    return Unity.FoxgloveSDK.Util.FoxRunUpdatePolicy.ShouldPublish(FoxRunPolicy.Change, nowSec, __hasLast_0, changed, __lastPublishSec_0, 0f);
                case 1: return true;
                case 2:
                    changed = !__hasLast_2;
                    if (!changed) changed = !EqualityComparer<System.Collections.Generic.List<float>>.Default.Equals(this._sampleList, __last_2_0);
                    return Unity.FoxgloveSDK.Util.FoxRunUpdatePolicy.ShouldPublish(FoxRunPolicy.Change, nowSec, __hasLast_2, changed, __lastPublishSec_2, 0f);
                case 3:
                    changed = !__hasLast_3;
                    if (!changed) changed = !EqualityComparer<int?>.Default.Equals(this._optionalCount, __last_3_0);
                    return Unity.FoxgloveSDK.Util.FoxRunUpdatePolicy.ShouldPublish(FoxRunPolicy.Change, nowSec, __hasLast_3, changed, __lastPublishSec_3, 0f);
                case 4: return false;
                case 5:
                    changed = !__hasLast_5;
                    if (!changed) changed = global::Unity.FoxgloveSDK.Components.FoxRunChangeHelper.FloatChanged(this._value, __last_5_0, 0f);
                    if (!changed) changed = global::Unity.FoxgloveSDK.Components.FoxRunChangeHelper.FloatChanged(this._valueMirror, __last_5_1, 0.00999999978f);
                    return Unity.FoxgloveSDK.Util.FoxRunUpdatePolicy.ShouldPublish(FoxRunPolicy.Change, nowSec, __hasLast_5, changed, __lastPublishSec_5, 0.200000003f);
                case 6:
                    changed = !__hasLast_6;
                    if (!changed) changed = global::Unity.FoxgloveSDK.Components.FoxRunChangeHelper.FloatChanged(this._position.x, __last_6_0.x, 0.00100000005f) || global::Unity.FoxgloveSDK.Components.FoxRunChangeHelper.FloatChanged(this._position.y, __last_6_0.y, 0.00100000005f) || global::Unity.FoxgloveSDK.Components.FoxRunChangeHelper.FloatChanged(this._position.z, __last_6_0.z, 0.00100000005f);
                    return Unity.FoxgloveSDK.Util.FoxRunUpdatePolicy.ShouldPublish(FoxRunPolicy.Change, nowSec, __hasLast_6, changed, __lastPublishSec_6, 0f);
                default: return false;
            }
        }

        void IFoxgloveLogPolicySource.FoxgloveLog_MarkPublished(int topicIndex, double nowSec)
        {
            switch (topicIndex)
            {
                case 0:
                    __last_0_0 = this._samples;
                    __hasLast_0 = true;
                    __lastPublishSec_0 = nowSec;
                    break;
                case 2:
                    __last_2_0 = this._sampleList;
                    __hasLast_2 = true;
                    __lastPublishSec_2 = nowSec;
                    break;
                case 3:
                    __last_3_0 = this._optionalCount;
                    __hasLast_3 = true;
                    __lastPublishSec_3 = nowSec;
                    break;
                case 5:
                    __last_5_0 = this._value;
                    __last_5_1 = this._valueMirror;
                    __hasLast_5 = true;
                    __lastPublishSec_5 = nowSec;
                    break;
                case 6:
                    __last_6_0 = this._position;
                    __hasLast_6 = true;
                    __lastPublishSec_6 = nowSec;
                    break;
                default: break;
            }
        }
    }
}
