// Copyright (c) 2026 Jianbin Liu and Unity2Foxglove contributors.
// SPDX-License-Identifier: Apache-2.0
//
// Module: Runtime/Schemas/Proto/Publishers
// Purpose: Publishes foxglove.PointCloud messages from decoded frames or Unity transforms.

using System;
using System.Collections.Generic;
using Foxglove.Schemas;
using Foxglove.Schemas.PointCloud;
using UnityEngine;
using Unity.FoxgloveSDK.Schemas;
using Unity.FoxgloveSDK.Schemas.PointCloud;
using Unity.FoxgloveSDK.Schemas.Ros2Msg;
using Unity.FoxgloveSDK.Util;

namespace Unity.FoxgloveSDK.Components
{
    /// <summary>
    /// Publishes decoded point frames or child transforms as foxglove.PointCloud.
    /// Programmatic frames are intended for later Ouster/ROS input bridges.
    /// </summary>
    public class FoxglovePointCloudPublisher : FoxglovePublisherBase
    {
        private const int DracoFailureWarningIntervalFrames = 120;
        private const int MaxCompletedDracoEncodeResults = 8;
        private const int PointCloud2NativeFailureWarningIntervalFrames = 120;
        private const int MaxCompletedPointCloud2NativeResults = 8;
        private const int DracoWorkerStopWaitMs = 5000;
        private const int PointCloud2NativeWorkerStopWaitMs = 5000;

        [Header("Point Cloud Output")]
        [SerializeField] private PointCloudOutputMode _outputMode = PointCloudOutputMode.Draco;

        [Header("Point Cloud")]
        [SerializeField] private string _frameId = "unity_world";
        [SerializeField] private Transform[] _pointSources;
        [SerializeField] private bool _includeInactiveChildren;
        [SerializeField] private bool _useChildrenWhenSourcesEmpty = true;
        [SerializeField, Min(1)] private int _maxPoints = 4096;
        [SerializeField, Min(0)] private int _maxPackedBytes;
        [SerializeField] private PointCloudSamplingMode _samplingMode = PointCloudSamplingMode.FirstPoints;
        [SerializeField, Min(0f)] private float _voxelSizeMeters = 0.1f;
        [SerializeField] private bool _logQosDrops;
        [SerializeField] private bool _logPerformanceDiagnostics;
        [SerializeField] private bool _includeSyntheticIntensity;

        [Header("PointCloud2 Native TF")]
        [Tooltip("Publish a lightweight ROS2 TF anchor for PointCloud2 Native output so RViz can resolve the point-cloud frame without an extra helper component.")]
        [SerializeField] private bool _publishPointCloud2NativeTfAnchor = true;
        [Tooltip("Parent frame used when publishing the PointCloud2 Native TF anchor.")]
        [SerializeField] private string _pointCloud2NativeTfParentFrame = "map";
        [Tooltip("Child frame used when publishing the PointCloud2 Native TF anchor. Leave empty to follow Frame Id.")]
        [SerializeField] private string _pointCloud2NativeTfChildFrame;
        [Tooltip("TF anchor translation in ROS coordinates.")]
        [SerializeField] private Vector3 _pointCloud2NativeTfTranslation;
        [Tooltip("TF anchor rotation in ROS roll/pitch/yaw degrees.")]
        [SerializeField] private Vector3 _pointCloud2NativeTfRotationEuler;
        [SerializeField, HideInInspector] private bool _pointCloud2NativeTfAnchorInitialized;

        [Header("Draco")]
        [Tooltip("Optional cap for source-driven VirtualLidar native Draco snapshots. Set 0 to publish every completed source scan; main-loop protection belongs in the LiDAR raycast budget, not a fixed publisher rate.")]
        [SerializeField, Min(0f)] private float _nativeDracoMaxPublishRateHz;
        [Tooltip("When source-driven frames arrive through SetFrame/PublishFrame/VirtualLidar native Draco, suppress the transform fallback generated by this publisher's Update loop so sparse child-transform frames cannot overwrite real LiDAR clouds.")]
        [SerializeField] private bool _suppressTransformFallbackAfterSourceFrames = true;

        private readonly PointCloudPendingFrameSlot _pendingFrameSlot = new PointCloudPendingFrameSlot();
        private bool _warnedDracoFailure;
        private readonly PointCloudPublishState _publishState = new PointCloudPublishState();
        private readonly PointCloudQoSReducer _qosReducer = new PointCloudQoSReducer();
        private int _dracoFailureCount;
        private bool _warnedDracoBacklog;
        private bool _warnedDracoWorkerShutdown;
        private readonly BackgroundEncodePipeline<DracoEncodeRequest, DracoEncodeResult> _dracoEncodePipeline =
            new BackgroundEncodePipeline<DracoEncodeRequest, DracoEncodeResult>(
                "Foxglove Draco PointCloud Encode",
                MaxCompletedDracoEncodeResults,
                DracoWorkerStopWaitMs,
                PointCloudWorkerEncoders.EncodeDracoRequest);
        private readonly BackgroundEncodePipeline<PointCloud2NativeRequest, PointCloud2NativeResult> _pointCloud2NativePipeline =
            new BackgroundEncodePipeline<PointCloud2NativeRequest, PointCloud2NativeResult>(
                "Foxglove PointCloud2 Native Pack",
                MaxCompletedPointCloud2NativeResults,
                PointCloud2NativeWorkerStopWaitMs,
                PointCloudWorkerEncoders.EncodePointCloud2NativeRequest);
        private int _pointCloud2NativeFailureCount;
        private bool _warnedPointCloud2NativeFailure;
        private bool _warnedPointCloud2NativeBacklog;
        private bool _warnedPointCloud2NativeWorkerShutdown;
        private readonly PointCloudPublishDiagnostics _diagnostics = new PointCloudPublishDiagnostics();
        private ulong _lastNativeDracoPublishUnixNs;

        private PointCloudOutputProfile ActiveProfile => PointCloudOutputProfile.ForMode(_outputMode);
        protected override string SchemaName => SchemaNameOverride;
        protected virtual string SchemaNameOverride => ActiveProfile.SchemaName;
        protected virtual string DefaultTopic => ActiveProfile.DefaultTopic;
        /// <summary>True when VirtualLidar may use the low-allocation Draco queue.</summary>
        internal bool CanQueueVirtualLidarDracoFrame => _outputMode == PointCloudOutputMode.Draco;
        /// <summary>True when VirtualLidar may use the low-allocation PointCloud2 Native queue.</summary>
        internal bool CanQueueVirtualLidarPointCloud2NativeFrame => _outputMode == PointCloudOutputMode.PointCloud2Native;
        /// <summary>True when any VirtualLidar native queue is active for this mode.</summary>
        internal bool CanQueueVirtualLidarNativeFrame => CanQueueVirtualLidarDracoFrame || CanQueueVirtualLidarPointCloud2NativeFrame;
        /// <summary>Whether the selected output mode supports JSON payloads.</summary>
        public override bool SupportsJsonEncoding => ActiveProfile.SupportsJson;

        /// <summary>
        /// Raised on the Unity main thread after the PointCloud2 native worker has
        /// prepared packed data. Optional DDS adapters can publish the frame without
        /// doing per-point work on the main thread.
        /// </summary>
        public event Action<PointCloud2NativeFrame> PointCloud2NativeFrameReady;

        /// <summary>Whether the selected output mode supports protobuf payloads.</summary>
        public override bool SupportsProtobufEncoding => ActiveProfile.SupportsProtobuf;

        /// <summary>Whether this publisher can emit ROS2 CDR payloads for compatible modes.</summary>
        public override bool SupportsRos2Encoding => true;
        protected override bool IsExpectedEncodingFallback(PublisherEncodingResolution resolution)
            => IsPointCloud2NativeOutput && resolution.Effective == PublisherEffectiveEncoding.Ros2;

        /// <summary>Current user-selected point-cloud output mode.</summary>
        public PointCloudOutputMode OutputMode => _outputMode;

        /// <summary>True when this publisher is configured for standard PointCloud2 native output.</summary>
        public bool IsPointCloud2NativeOutput => _outputMode == PointCloudOutputMode.PointCloud2Native;

        /// <summary>Resolved publisher topic for optional native ROS2 PointCloud2 adapters.</summary>
        public string PointCloud2NativeTopic => string.IsNullOrWhiteSpace(_topic) ? DefaultTopic : _topic;

        /// <summary>Resolved frame id for optional native ROS2 PointCloud2 adapters.</summary>
        public string PointCloudFrameId => SanitizeNonEmptyFrameId(_frameId, "unity_world");

        /// <summary>True when PointCloud2 Native output should also publish a TF anchor.</summary>
        public bool PublishPointCloud2NativeTfAnchor => IsPointCloud2NativeOutput && _publishPointCloud2NativeTfAnchor;

        /// <summary>Resolved parent frame for the optional PointCloud2 Native TF anchor.</summary>
        public string PointCloud2NativeTfParentFrame => SanitizeNonEmptyFrameId(_pointCloud2NativeTfParentFrame, "map");

        /// <summary>Resolved child frame for the optional PointCloud2 Native TF anchor.</summary>
        public string PointCloud2NativeTfChildFrame => SanitizeNonEmptyFrameId(_pointCloud2NativeTfChildFrame, PointCloudFrameId);

        /// <summary>Translation for the optional PointCloud2 Native TF anchor.</summary>
        public Vector3 PointCloud2NativeTfTranslation => _pointCloud2NativeTfTranslation;

        /// <summary>Rotation for the optional PointCloud2 Native TF anchor.</summary>
        public Quaternion PointCloud2NativeTfRotation => PointCloud2NativeTfRotationRos;

        /// <summary>Rotation for the optional PointCloud2 Native TF anchor from ROS roll/pitch/yaw degrees.</summary>
        public Quaternion PointCloud2NativeTfRotationRos
        {
            get
            {
                var q = RosTransformMath.RollPitchYawDegreesToQuaternion(
                    _pointCloud2NativeTfRotationEuler.x,
                    _pointCloud2NativeTfRotationEuler.y,
                    _pointCloud2NativeTfRotationEuler.z);
                return new Quaternion(q.X, q.Y, q.Z, q.W);
            }
        }

        protected override string Ros2SchemaName
        {
            get
            {
                switch (_outputMode)
                {
                    case PointCloudOutputMode.Draco:
                        return Ros2PublisherSchemaNames.CompressedPointCloud;
                    case PointCloudOutputMode.PointCloud2Native:
                        return Ros2PublisherSchemaNames.SensorPointCloud2;
                    case PointCloudOutputMode.Raw:
                    default:
                        return Ros2PublisherSchemaNames.PointCloud;
                }
            }
        }

        protected virtual void Awake()
        {
            EnsurePointCloud2NativeTfAnchorInitialized();
            if (string.IsNullOrEmpty(_topic)) _topic = DefaultTopic;
        }

        private void OnValidate()
        {
            EnsurePointCloud2NativeTfAnchorInitialized();
        }

        private void EnsurePointCloud2NativeTfAnchorInitialized()
        {
            if (_pointCloud2NativeTfAnchorInitialized)
                return;

            _publishPointCloud2NativeTfAnchor = true;
            _pointCloud2NativeTfAnchorInitialized = true;
        }

        private static string SanitizeNonEmptyFrameId(string raw, string fallback)
        {
            var value = string.IsNullOrWhiteSpace(raw) ? fallback : raw.Trim();
            return SanitizeFrameId(value, fallback);
        }

        protected override void Reset()
        {
            base.Reset();
            EnsurePointCloud2NativeTfAnchorInitialized();
            _samplingMode = PointCloudSamplingMode.UniformStride;
        }

        protected override void OnDisable()
        {
            _lastNativeDracoPublishUnixNs = 0UL;
            _publishState.ResetSourceDriven();
            _publishState.ClearPreparedDemand();
            StopDracoEncodeWorker(clearCompleted: true);
            StopPointCloud2NativeWorker(clearCompleted: true);
            base.OnDisable();
        }

        private void OnDestroy()
        {
            StopDracoEncodeWorker(clearCompleted: true);
            StopPointCloud2NativeWorker(clearCompleted: true);
        }

        /// <summary>
        /// Queue a decoded frame for the next publish tick.
        /// This is a last-value-wins buffer: a new frame replaces stale pending data.
        /// </summary>
        public void SetFrame(PointCloudFrame frame)
        {
            if (frame != null)
                MarkSourceDrivenPointCloud();

            var droppedPendingFrame = _pendingFrameSlot.SetFrame(frame, _logQosDrops, out var warning);

            if (!string.IsNullOrEmpty(warning))
                Debug.LogWarning(warning);

            if (droppedPendingFrame)
                _diagnostics.RecordDrop(_logPerformanceDiagnostics);
        }

        /// <summary>
        /// Publish a decoded frame immediately, bypassing the regular Update cadence.
        /// </summary>
        /// <remarks>
        /// Use the supplied timestamp to keep LiDAR timing aligned with IMU/TF inputs.
        /// </remarks>
        public void PublishFrame(PointCloudFrame frame, ulong logTimeNs)
        {
            if (frame != null)
                MarkSourceDrivenPointCloud();

            ResolveManager();
            if (_manager == null || frame == null) return;
            var publishWebSocket = ShouldPreparePublishPayload();
            var publishBridge = ShouldPrepareRos2BridgePayload();
            var publishNativeFrame = ShouldPreparePointCloud2NativeFrame();
            if (!publishWebSocket && !publishBridge && !publishNativeFrame) return;

            var prepared = PrepareFrameForQoS(frame, logTimeNs);
            if (prepared == null || prepared.GetPointCount() == 0) return;
            SetPreparedPublishDemand(publishWebSocket, publishBridge);
            try
            {
                PublishPreparedFrame(prepared, logTimeNs);
                _diagnostics.LogIfReady(_logPerformanceDiagnostics, LogPointCloudDiagnosticMessage);
            }
            finally
            {
                ClearPreparedPublishDemand();
            }
        }

        /// <summary>
        /// Queues a source VirtualLidar snapshot into the Draco worker when the
        /// selected mode is compatible.
        /// </summary>
        internal bool TryQueueVirtualLidarDracoFrame(
            VirtualLidarPointData[] points,
            int pointCount,
            ulong unixNs,
            string frameId,
            bool emitAbsoluteTimeNs)
        {
            if (!CanQueueVirtualLidarDracoFrame)
                return false;

            if (points != null && pointCount > 0)
                MarkSourceDrivenPointCloud();

            ResolveManager();
            if (_manager == null || _manager.Runtime?.ReplayEnabled == true)
                return true;

            var publishWebSocket = ShouldPreparePublishPayload();
            var publishBridge = ShouldPrepareRos2BridgePayload();
            if (!publishWebSocket && !publishBridge)
                return true;

            if (!ShouldQueueVirtualLidarDracoFrame(unixNs))
                return true;

            QueueVirtualLidarDracoEncode(
                points,
                pointCount,
                unixNs,
                frameId,
                emitAbsoluteTimeNs,
                publishWebSocket,
                publishBridge,
                EffectiveEncoding);
            return true;
        }

        /// <summary>
        /// Queues a source VirtualLidar snapshot into the PointCloud2 Native
        /// worker when the selected mode is compatible.
        /// </summary>
        internal bool TryQueueVirtualLidarPointCloud2NativeFrame(
            VirtualLidarPointData[] points,
            int pointCount,
            ulong unixNs,
            string frameId,
            bool emitAbsoluteTimeNs)
        {
            if (!CanQueueVirtualLidarPointCloud2NativeFrame)
                return false;

            if (points != null && pointCount > 0)
                MarkSourceDrivenPointCloud();

            ResolveManager();
            if (_manager == null || _manager.Runtime?.ReplayEnabled == true)
                return true;

            var publishWebSocket = ShouldPreparePublishPayload();
            var publishBridge = ShouldPrepareRos2BridgePayload();
            var publishNativeFrame = ShouldPreparePointCloud2NativeFrame();
            if (!publishWebSocket && !publishBridge && !publishNativeFrame)
                return true;

            QueueVirtualLidarPointCloud2Native(
                points,
                pointCount,
                unixNs,
                frameId,
                emitAbsoluteTimeNs,
                publishWebSocket,
                publishBridge,
                publishNativeFrame,
                EffectiveEncoding);
            return true;
        }

        private bool ShouldQueueVirtualLidarDracoFrame(ulong unixNs)
        {
            var rateHz = _nativeDracoMaxPublishRateHz;
            if (rateHz <= 0f)
                return true;

            var intervalNs = (ulong)Math.Max(1d, Math.Round(1_000_000_000d / rateHz));
            var timestampNs = unixNs == 0UL ? FoxgloveTimeUtil.NowUnixTimeNs() : unixNs;

            if (_lastNativeDracoPublishUnixNs != 0UL
                && timestampNs >= _lastNativeDracoPublishUnixNs
                && timestampNs - _lastNativeDracoPublishUnixNs < intervalNs)
            {
                _diagnostics.RecordDrop(_logPerformanceDiagnostics);
                return false;
            }

            _lastNativeDracoPublishUnixNs = timestampNs;
            return true;
        }

        protected virtual void Update()
        {
            if (_manager == null) return;
            if (_manager.Runtime?.ReplayEnabled == true) return;
            DrainCompletedDracoEncode();
            DrainCompletedPointCloud2Native();
            if (!_publishOnEnable) return;
            if (!ShouldPublishNow()) return;
            var publishWebSocket = ShouldPreparePublishPayload();
            var publishBridge = ShouldPrepareRos2BridgePayload();
            var publishNativeFrame = ShouldPreparePointCloud2NativeFrame();
            if (!publishWebSocket && !publishBridge && !publishNativeFrame) return;

            var unixNs = CurrentLogTimeNs;
            var pendingFrame = _pendingFrameSlot.Take();

            // A source frame that carries its own timestamp (e.g. VirtualLidar's physics-time
            // scan start) drives the log time too, so payload time == log time (matching the
            // IMU path) and SLAM consumers see one consistent clock instead of a wall-clock vs
            // physics-clock skew that drifts under frame-rate stalls.
            if (pendingFrame != null && pendingFrame.UnixNs != 0)
                unixNs = pendingFrame.UnixNs;

            if (pendingFrame == null && ShouldSuppressTransformFallback())
            {
                if (_logQosDrops && _publishState.ShouldLogTransformFallbackSuppressedWarning())
                {
                    Debug.LogWarning("[Foxglove] PointCloud transform fallback suppressed after source-driven frames; real LiDAR/source frames will own this topic.");
                }
                return;
            }

            var frame = pendingFrame != null
                ? PrepareFrameForQoS(pendingFrame, unixNs)
                : PrepareFrameForQoS(PointCloudTransformFrameBuilder.Build(
                    unixNs,
                    SanitizeFrameId(_frameId, "unity_world"),
                    transform,
                    _pointSources,
                    _useChildrenWhenSourcesEmpty,
                    _includeInactiveChildren,
                    _includeSyntheticIntensity,
                    _maxPoints,
                    Manager != null ? Manager.ActiveCoordinateMode : CoordinateMode.LeftHand),
                    unixNs);
            _pendingFrameSlot.ResetReplacementWarning();
            if (frame == null || frame.GetPointCount() == 0) return;

            SetPreparedPublishDemand(publishWebSocket, publishBridge);
            try
            {
                PublishPreparedFrame(frame, unixNs);
                _diagnostics.LogIfReady(_logPerformanceDiagnostics, LogPointCloudDiagnosticMessage);
            }
            finally
            {
                ClearPreparedPublishDemand();
            }
        }

        protected virtual void PublishPreparedFrame(PointCloudFrame frame, ulong unixNs)
        {
            _diagnostics.RecordPrepared(_logPerformanceDiagnostics, frame);

            if (_outputMode == PointCloudOutputMode.Draco)
            {
                PublishDracoFrame(frame, unixNs);
                return;
            }

            if (_outputMode == PointCloudOutputMode.PointCloud2Native)
            {
                PublishPointCloud2NativeFrame(frame, unixNs);
                return;
            }

            PublishRawFrame(frame, unixNs);
        }

        private void PublishRawFrame(PointCloudFrame frame, ulong unixNs)
        {
            if (!TryGetPreparedPublishDemand(out var publishWebSocket, out var publishBridge))
            {
                publishWebSocket = ShouldPreparePublishPayload();
                publishBridge = ShouldPrepareRos2BridgePayload();
            }
            byte[] ros2Payload = null;

            if (publishWebSocket && EffectiveEncoding == PublisherEffectiveEncoding.Protobuf)
            {
                PublishProto(PointCloudMessageBuilder.SerializeProtobuf(frame), unixNs);
            }
            else if (publishWebSocket && EffectiveEncoding == PublisherEffectiveEncoding.Ros2)
            {
                ros2Payload = Ros2CdrPointCloudBuilder.Serialize(frame);
                PublishRos2(ros2Payload, unixNs);
            }
            else if (publishWebSocket)
            {
                Publish(PointCloudMessageBuilder.CreateJson(frame), unixNs);
            }

            if (publishBridge)
            {
                ros2Payload ??= Ros2CdrPointCloudBuilder.Serialize(frame);
                PublishRos2Bridge(ros2Payload, unixNs);
            }
        }

        private void PublishPointCloud2NativeFrame(PointCloudFrame frame, ulong unixNs)
        {
            if (!TryGetPreparedPublishDemand(out var publishWebSocket, out var publishBridge))
            {
                publishWebSocket = ShouldPreparePublishPayload();
                publishBridge = ShouldPrepareRos2BridgePayload();
            }

            byte[] ros2Payload = null;
            if (publishWebSocket && EffectiveEncoding == PublisherEffectiveEncoding.Ros2)
            {
                ros2Payload = Ros2CdrSensorPointCloud2Builder.Serialize(frame);
                PublishRos2(ros2Payload, unixNs);
            }

            if (publishBridge)
            {
                ros2Payload ??= Ros2CdrSensorPointCloud2Builder.Serialize(frame);
                PublishRos2Bridge(ros2Payload, unixNs);
            }

            if (ShouldPreparePointCloud2NativeFrame())
                PublishPreparedPointCloud2NativeFrame(frame, unixNs);
        }

        private bool ShouldPreparePointCloud2NativeFrame()
            => _outputMode == PointCloudOutputMode.PointCloud2Native
               && PointCloud2NativeFrameReady != null;

        private void PublishPreparedPointCloud2NativeFrame(PointCloudFrame frame, ulong unixNs)
        {
            var handler = PointCloud2NativeFrameReady;
            if (handler == null || frame == null)
                return;

            try
            {
                var packed = PointCloudPackedDataBuilder.Build(frame);
                var nativeFrame = new PointCloud2NativeFrame(
                    unixNs,
                    string.IsNullOrEmpty(frame.FrameId) ? _frameId : frame.FrameId,
                    height: 1U,
                    width: checked((uint)frame.GetPointCount()),
                    fields: packed.Fields,
                    pointStep: packed.PointStride,
                    data: packed.Data,
                    isDense: true);
                handler(nativeFrame);
            }
            catch (Exception ex)
            {
                Debug.LogWarning("[Foxglove] PointCloud2 native frame subscriber failed: " + ex.Message);
            }
        }

        private void PublishDracoFrame(PointCloudFrame frame, ulong unixNs)
        {
            if (frame == null || frame.GetPointCount() == 0)
                return;

            QueueDracoEncode(frame, unixNs);
        }

        private void QueueDracoEncode(PointCloudFrame frame, ulong unixNs)
        {
            if (!TryGetPreparedPublishDemand(out var publishWebSocket, out var publishBridge))
            {
                publishWebSocket = ShouldPreparePublishPayload();
                publishBridge = ShouldPrepareRos2BridgePayload();
            }

            // No main-thread clone. VirtualLidar allocates a fresh PointCloudFrame for every
            // scan (StartNewScan) and never mutates a frame after handing it to SetFrame, so
            // the background worker can read this frame directly. Cloning 262144 points on the
            // Update thread was the dominant per-frame main-thread spike that stalled the loop.
            var request = new DracoEncodeRequest(
                frame,
                unixNs,
                publishWebSocket,
                publishBridge,
                EffectiveEncoding,
                0d);
            EnqueueDracoEncodeRequest(request);
        }

        private void QueueVirtualLidarDracoEncode(
            VirtualLidarPointData[] points,
            int pointCount,
            ulong unixNs,
            string frameId,
            bool emitAbsoluteTimeNs,
            bool publishWebSocket,
            bool publishBridge,
            PublisherEffectiveEncoding webSocketEncoding)
        {
            if (points == null || pointCount <= 0)
                return;

            _diagnostics.RecordPrepared(_logPerformanceDiagnostics, pointCount);
            var request = new DracoEncodeRequest(
                points,
                pointCount,
                unixNs,
                string.IsNullOrEmpty(frameId) ? _frameId : frameId,
                emitAbsoluteTimeNs,
                publishWebSocket,
                publishBridge,
                webSocketEncoding,
                0d);
            EnqueueDracoEncodeRequest(request);
        }

        private void QueueVirtualLidarPointCloud2Native(
            VirtualLidarPointData[] points,
            int pointCount,
            ulong unixNs,
            string frameId,
            bool emitAbsoluteTimeNs,
            bool publishWebSocket,
            bool publishBridge,
            bool publishNativeFrame,
            PublisherEffectiveEncoding webSocketEncoding)
        {
            if (points == null || pointCount <= 0)
                return;

            _diagnostics.RecordPrepared(_logPerformanceDiagnostics, pointCount);
            var request = new PointCloud2NativeRequest(
                points,
                pointCount,
                unixNs,
                string.IsNullOrEmpty(frameId) ? _frameId : frameId,
                emitAbsoluteTimeNs,
                publishWebSocket,
                publishBridge,
                publishNativeFrame,
                webSocketEncoding);
            EnqueuePointCloud2NativeRequest(request);
        }

        /// <summary>
        /// Marks this publisher as source-driven so transform fallback frames do
        /// not overwrite real LiDAR output.
        /// </summary>
        internal void MarkSourceDrivenPointCloud()
        {
            _publishState.MarkSourceDriven();
        }

        private bool ShouldSuppressTransformFallback()
            => _publishState.ShouldSuppressTransformFallback(_suppressTransformFallbackAfterSourceFrames);

        private void EnqueueDracoEncodeRequest(DracoEncodeRequest request)
        {
            var queued = _dracoEncodePipeline.Enqueue(request, out var replacedPending, out var startError);
            if (replacedPending)
            {
                if (_logQosDrops && !_warnedDracoBacklog)
                {
                    Debug.LogWarning("[Foxglove] Draco point-cloud encode request replaced; stale pending encode dropped.");
                    _warnedDracoBacklog = true;
                }

                _diagnostics.RecordDrop(_logPerformanceDiagnostics);
            }

            if (!queued)
                LogDracoFailure("Unable to queue background Draco encode: " + startError);
        }

        private void EnqueuePointCloud2NativeRequest(PointCloud2NativeRequest request)
        {
            var queued = _pointCloud2NativePipeline.Enqueue(request, out var replacedPending, out var startError);
            if (replacedPending)
            {
                if (_logQosDrops && !_warnedPointCloud2NativeBacklog)
                {
                    Debug.LogWarning("[Foxglove] PointCloud2 native request replaced; stale pending payload dropped.");
                    _warnedPointCloud2NativeBacklog = true;
                }

                _diagnostics.RecordDrop(_logPerformanceDiagnostics);
            }

            if (!queued)
                LogPointCloud2NativeFailure("Unable to queue background PointCloud2 pack: " + startError);
        }

        private void DrainCompletedDracoEncode()
        {
            var results = _dracoEncodePipeline.Drain(out var droppedCompletedResults);
            if (droppedCompletedResults > 0 && _logQosDrops)
                Debug.LogWarning($"[Foxglove] Draco point-cloud encode results dropped before main-thread drain: {droppedCompletedResults}.");
            if (droppedCompletedResults > 0)
                _diagnostics.RecordDrop(_logPerformanceDiagnostics, droppedCompletedResults);

            if (results == null || results.Count == 0)
                return;

            foreach (var result in results)
            {
                if (!result.Success)
                {
                    LogDracoFailure((string.IsNullOrWhiteSpace(result.Error) ? "Native Draco encode failed." : result.Error) + " Draco mode publishes nothing.");
                    continue;
                }

                _warnedDracoFailure = false;
                _dracoFailureCount = 0;
                _warnedDracoBacklog = false;
                _diagnostics.RecordEncodeResult(_logPerformanceDiagnostics, result);
                PublishCompletedDracoPayload(result);
            }

            _diagnostics.LogIfReady(_logPerformanceDiagnostics, LogPointCloudDiagnosticMessage);
        }

        private void DrainCompletedPointCloud2Native()
        {
            var results = _pointCloud2NativePipeline.Drain(out var droppedCompletedResults);
            if (droppedCompletedResults > 0 && _logQosDrops)
                Debug.LogWarning($"[Foxglove] PointCloud2 native payloads dropped before main-thread drain: {droppedCompletedResults}.");
            if (droppedCompletedResults > 0)
                _diagnostics.RecordDrop(_logPerformanceDiagnostics, droppedCompletedResults);

            if (results == null || results.Count == 0)
                return;

            foreach (var result in results)
            {
                if (!result.Success)
                {
                    LogPointCloud2NativeFailure((string.IsNullOrWhiteSpace(result.Error) ? "Native PointCloud2 pack failed." : result.Error) + " PointCloud2Native mode publishes nothing.");
                    continue;
                }

                _warnedPointCloud2NativeFailure = false;
                _pointCloud2NativeFailureCount = 0;
                _warnedPointCloud2NativeBacklog = false;
                _diagnostics.RecordPointCloud2NativeResult(_logPerformanceDiagnostics, result);
                PublishCompletedPointCloud2NativePayload(result);
            }

            _diagnostics.LogIfReady(_logPerformanceDiagnostics, LogPointCloudDiagnosticMessage);
        }

        private void StopDracoEncodeWorker(bool clearCompleted)
        {
            if (_dracoEncodePipeline.Stop(clearCompleted, out var waitedForWorker))
            {
                if (waitedForWorker)
                    _warnedDracoWorkerShutdown = false;
                return;
            }

            if (!_warnedDracoWorkerShutdown)
            {
                Debug.LogWarning("[Foxglove] Draco point-cloud encode worker is still stopping; native encode will be ignored when it returns.");
                _warnedDracoWorkerShutdown = true;
            }
        }

        private void StopPointCloud2NativeWorker(bool clearCompleted)
        {
            if (_pointCloud2NativePipeline.Stop(clearCompleted, out var waitedForWorker))
            {
                if (waitedForWorker)
                    _warnedPointCloud2NativeWorkerShutdown = false;
                return;
            }

            if (!_warnedPointCloud2NativeWorkerShutdown)
            {
                Debug.LogWarning("[Foxglove] PointCloud2 native worker is still stopping; native payload will be ignored when it returns.");
                _warnedPointCloud2NativeWorkerShutdown = true;
            }
        }

        private void PublishCompletedDracoPayload(DracoEncodeResult result)
        {
            if (result.Request.PublishWebSocket && result.Request.WebSocketEncoding == PublisherEffectiveEncoding.Ros2)
            {
                PublishRos2(result.WebSocketPayload, result.Request.UnixNs);
            }
            else if (result.Request.PublishWebSocket)
            {
                PublishProto(result.WebSocketPayload, result.Request.UnixNs);
            }

            if (result.Request.PublishBridge)
                PublishRos2Bridge(result.BridgePayload, result.Request.UnixNs);
        }

        private void PublishCompletedPointCloud2NativePayload(PointCloud2NativeResult result)
        {
            if (result.Request.PublishWebSocket && result.Request.WebSocketEncoding == PublisherEffectiveEncoding.Ros2)
                PublishRos2(result.WebSocketPayload, result.Request.UnixNs);

            if (result.Request.PublishBridge)
                PublishRos2Bridge(result.BridgePayload, result.Request.UnixNs);

            if (result.Request.PublishNativeFrame && result.NativeFrame != null)
            {
                var handler = PointCloud2NativeFrameReady;
                if (handler == null)
                    return;

                try
                {
                    handler(result.NativeFrame);
                }
                catch (Exception ex)
                {
                    Debug.LogWarning("[Foxglove] PointCloud2 native frame subscriber failed: " + ex.Message);
                }
            }
        }

        private void SetPreparedPublishDemand(bool publishWebSocket, bool publishBridge)
        {
            _publishState.SetPreparedDemand(publishWebSocket, publishBridge);
        }

        private void ClearPreparedPublishDemand()
        {
            _publishState.ClearPreparedDemand();
        }

        private bool TryGetPreparedPublishDemand(out bool publishWebSocket, out bool publishBridge)
        {
            return _publishState.TryGetPreparedDemand(out publishWebSocket, out publishBridge);
        }

        private void LogDracoFailure(string message)
        {
            _dracoFailureCount++;
            if (_warnedDracoFailure && _dracoFailureCount % DracoFailureWarningIntervalFrames != 0)
                return;

            _warnedDracoFailure = true;
            Debug.LogWarning("[Foxglove] Draco point-cloud mode disabled: " + message);
        }

        private void LogPointCloud2NativeFailure(string message)
        {
            _pointCloud2NativeFailureCount++;
            if (_warnedPointCloud2NativeFailure && _pointCloud2NativeFailureCount % PointCloud2NativeFailureWarningIntervalFrames != 0)
                return;

            _warnedPointCloud2NativeFailure = true;
            Debug.LogWarning("[Foxglove] PointCloud2 native mode disabled: " + message);
        }

        private void LogPointCloudDiagnosticMessage(string format, object[] args)
        {
            Debug.LogFormat(
                LogType.Log,
                LogOption.NoStacktrace,
                this,
                format,
                args);
        }

        protected virtual PointCloudFrame PrepareFrameForQoS(PointCloudFrame frame, ulong unixNs)
        {
            return _qosReducer.PrepareFrameForQoS(
                frame,
                unixNs,
                string.IsNullOrWhiteSpace(_frameId) ? "unity_world" : _frameId,
                _maxPoints,
                _maxPackedBytes,
                _samplingMode,
                _voxelSizeMeters,
                _logQosDrops);
        }
    }
}
