// Copyright (c) 2026 Jianbin Liu and Unity2Foxglove contributors.
// SPDX-License-Identifier: Apache-2.0
//
// Module: Runtime/Schemas/Proto/Publishers
// Purpose: Publishes foxglove.PointCloud messages from decoded frames or Unity transforms.

using System;
using System.Collections.Generic;
using System.Threading;
using Foxglove.Schemas;
using Foxglove.Schemas.PointCloud;
using UnityEngine;
using Unity.FoxgloveSDK.Schemas;
using Unity.FoxgloveSDK.Schemas.PointCloud;
using Unity.FoxgloveSDK.Schemas.Ros2Msg;
using Unity.FoxgloveSDK.Util;
using Stopwatch = System.Diagnostics.Stopwatch;
using UVector3 = UnityEngine.Vector3;

namespace Unity.FoxgloveSDK.Components
{
    /// <summary>
    /// Publishes decoded point frames or child transforms as foxglove.PointCloud.
    /// Programmatic frames are intended for later Ouster/ROS input bridges.
    /// </summary>
    public class FoxglovePointCloudPublisher : FoxglovePublisherBase
    {
        private const int DracoFailureWarningIntervalFrames = 120;
        private const int MaxCompletedDracoEncodeResults = 8;
        private const int PointCloud2NativeFailureWarningIntervalFrames = 120;
        private const int MaxCompletedPointCloud2NativeResults = 8;
        private const int DracoWorkerStopWaitMs = 5000;
        private const int PointCloud2NativeWorkerStopWaitMs = 5000;
        private const int PointCloudDiagnosticsIntervalFrames = 60;

        [Header("Point Cloud Output")]
        [SerializeField] private PointCloudOutputMode _outputMode = PointCloudOutputMode.Draco;

        [Header("Point Cloud")]
        [SerializeField] private string _frameId = "unity_world";
        [SerializeField] private Transform[] _pointSources;
        [SerializeField] private bool _includeInactiveChildren;
        [SerializeField] private bool _useChildrenWhenSourcesEmpty = true;
        [SerializeField, Min(1)] private int _maxPoints = 4096;
        [SerializeField, Min(0)] private int _maxPackedBytes;
        [SerializeField] private PointCloudSamplingMode _samplingMode = PointCloudSamplingMode.FirstPoints;
        [SerializeField, Min(0f)] private float _voxelSizeMeters = 0.1f;
        [SerializeField] private bool _logQosDrops;
        [SerializeField] private bool _logPerformanceDiagnostics;
        [SerializeField] private bool _includeSyntheticIntensity;

        [Header("PointCloud2 Native TF")]
        [Tooltip("Publish a lightweight ROS2 TF anchor for PointCloud2 Native output so RViz can resolve the point-cloud frame without an extra helper component.")]
        [SerializeField] private bool _publishPointCloud2NativeTfAnchor = true;
        [Tooltip("Parent frame used when publishing the PointCloud2 Native TF anchor.")]
        [SerializeField] private string _pointCloud2NativeTfParentFrame = "map";
        [Tooltip("Child frame used when publishing the PointCloud2 Native TF anchor. Leave empty to follow Frame Id.")]
        [SerializeField] private string _pointCloud2NativeTfChildFrame;
        [Tooltip("TF anchor translation in ROS coordinates.")]
        [SerializeField] private Vector3 _pointCloud2NativeTfTranslation;
        [Tooltip("TF anchor rotation in ROS roll/pitch/yaw degrees.")]
        [SerializeField] private Vector3 _pointCloud2NativeTfRotationEuler;
        [SerializeField, HideInInspector] private bool _pointCloud2NativeTfAnchorInitialized;

        [Header("Draco")]
        [Tooltip("Optional cap for source-driven VirtualLidar native Draco snapshots. Set 0 to publish every completed source scan; main-loop protection belongs in the LiDAR raycast budget, not a fixed publisher rate.")]
        [SerializeField, Min(0f)] private float _nativeDracoMaxPublishRateHz;
        [Tooltip("When source-driven frames arrive through SetFrame/PublishFrame/VirtualLidar native Draco, suppress the transform fallback generated by this publisher's Update loop so sparse child-transform frames cannot overwrite real LiDAR clouds.")]
        [SerializeField] private bool _suppressTransformFallbackAfterSourceFrames = true;

        private PointCloudFrame _pendingFrame;
        private readonly object _pendingFrameGate = new object();
        private bool _warnedPointCloudBudget;
        private bool _warnedPendingDrop;
        private bool _warnedDracoFailure;
        private bool _hasPreparedPublishDemand;
        private bool _preparedPublishWebSocket;
        private bool _preparedPublishBridge;
        private int _dracoFailureCount;
        private bool _warnedDracoBacklog;
        private bool _warnedDracoWorkerShutdown;
        private readonly BackgroundWorkerLifecycle _dracoEncodeWorker = new BackgroundWorkerLifecycle();
        private readonly Queue<DracoEncodeResult> _completedDracoEncodes = new Queue<DracoEncodeResult>();
        private DracoEncodeRequest _pendingDracoEncode;
        private int _droppedCompletedDracoEncodeCount;
        private readonly BackgroundWorkerLifecycle _pointCloud2NativeWorker = new BackgroundWorkerLifecycle();
        private readonly Queue<PointCloud2NativeResult> _completedPointCloud2Native = new Queue<PointCloud2NativeResult>();
        private PointCloud2NativeRequest _pendingPointCloud2Native;
        private int _droppedCompletedPointCloud2NativeCount;
        private int _pointCloud2NativeFailureCount;
        private bool _warnedPointCloud2NativeFailure;
        private bool _warnedPointCloud2NativeBacklog;
        private bool _warnedPointCloud2NativeWorkerShutdown;
        private int _diagnosticFrames;
        private long _diagnosticPreparedPoints;
        private int _diagnosticDrops;
        private double _diagnosticCloneMsTotal;
        private double _diagnosticCloneMsMax;
        private double _diagnosticEncodeMsTotal;
        private double _diagnosticEncodeMsMax;
        private int _diagnosticEncodeResults;
        private ulong _lastNativeDracoPublishUnixNs;
        private bool _hasSourceDrivenFrames;
        private bool _warnedTransformFallbackSuppressed;

        private PointCloudOutputProfile ActiveProfile => PointCloudOutputProfile.ForMode(_outputMode);
        protected override string SchemaName => SchemaNameOverride;
        protected virtual string SchemaNameOverride => ActiveProfile.SchemaName;
        protected virtual string DefaultTopic => ActiveProfile.DefaultTopic;
        /// <summary>True when VirtualLidar may use the low-allocation Draco queue.</summary>
        internal bool CanQueueVirtualLidarDracoFrame => _outputMode == PointCloudOutputMode.Draco;
        /// <summary>True when VirtualLidar may use the low-allocation PointCloud2 Native queue.</summary>
        internal bool CanQueueVirtualLidarPointCloud2NativeFrame => _outputMode == PointCloudOutputMode.PointCloud2Native;
        /// <summary>True when any VirtualLidar native queue is active for this mode.</summary>
        internal bool CanQueueVirtualLidarNativeFrame => CanQueueVirtualLidarDracoFrame || CanQueueVirtualLidarPointCloud2NativeFrame;
        /// <summary>Whether the selected output mode supports JSON payloads.</summary>
        public override bool SupportsJsonEncoding => ActiveProfile.SupportsJson;

        /// <summary>
        /// Raised on the Unity main thread after the PointCloud2 native worker has
        /// prepared packed data. Optional DDS adapters can publish the frame without
        /// doing per-point work on the main thread.
        /// </summary>
        public event Action<PointCloud2NativeFrame> PointCloud2NativeFrameReady;

        /// <summary>Whether the selected output mode supports protobuf payloads.</summary>
        public override bool SupportsProtobufEncoding => ActiveProfile.SupportsProtobuf;

        /// <summary>Whether this publisher can emit ROS2 CDR payloads for compatible modes.</summary>
        public override bool SupportsRos2Encoding => true;
        protected override bool IsExpectedEncodingFallback(PublisherEncodingResolution resolution)
            => IsPointCloud2NativeOutput && resolution.Effective == PublisherEffectiveEncoding.Ros2;

        /// <summary>Current user-selected point-cloud output mode.</summary>
        public PointCloudOutputMode OutputMode => _outputMode;

        /// <summary>True when this publisher is configured for standard PointCloud2 native output.</summary>
        public bool IsPointCloud2NativeOutput => _outputMode == PointCloudOutputMode.PointCloud2Native;

        /// <summary>Resolved publisher topic for optional native ROS2 PointCloud2 adapters.</summary>
        public string PointCloud2NativeTopic => string.IsNullOrWhiteSpace(_topic) ? DefaultTopic : _topic;

        /// <summary>Resolved frame id for optional native ROS2 PointCloud2 adapters.</summary>
        public string PointCloudFrameId => SanitizeNonEmptyFrameId(_frameId, "unity_world");

        /// <summary>True when PointCloud2 Native output should also publish a TF anchor.</summary>
        public bool PublishPointCloud2NativeTfAnchor => IsPointCloud2NativeOutput && _publishPointCloud2NativeTfAnchor;

        /// <summary>Resolved parent frame for the optional PointCloud2 Native TF anchor.</summary>
        public string PointCloud2NativeTfParentFrame => SanitizeNonEmptyFrameId(_pointCloud2NativeTfParentFrame, "map");

        /// <summary>Resolved child frame for the optional PointCloud2 Native TF anchor.</summary>
        public string PointCloud2NativeTfChildFrame => SanitizeNonEmptyFrameId(_pointCloud2NativeTfChildFrame, PointCloudFrameId);

        /// <summary>Translation for the optional PointCloud2 Native TF anchor.</summary>
        public Vector3 PointCloud2NativeTfTranslation => _pointCloud2NativeTfTranslation;

        /// <summary>Rotation for the optional PointCloud2 Native TF anchor.</summary>
        public Quaternion PointCloud2NativeTfRotation => PointCloud2NativeTfRotationRos;

        /// <summary>Rotation for the optional PointCloud2 Native TF anchor from ROS roll/pitch/yaw degrees.</summary>
        public Quaternion PointCloud2NativeTfRotationRos => RosRollPitchYawDegreesToQuaternion(_pointCloud2NativeTfRotationEuler);

        protected override string Ros2SchemaName
        {
            get
            {
                switch (_outputMode)
                {
                    case PointCloudOutputMode.Draco:
                        return Ros2PublisherSchemaNames.CompressedPointCloud;
                    case PointCloudOutputMode.PointCloud2Native:
                        return Ros2PublisherSchemaNames.SensorPointCloud2;
                    case PointCloudOutputMode.Raw:
                    default:
                        return Ros2PublisherSchemaNames.PointCloud;
                }
            }
        }

        protected virtual void Awake()
        {
            EnsurePointCloud2NativeTfAnchorInitialized();
            if (string.IsNullOrEmpty(_topic)) _topic = DefaultTopic;
        }

        private void OnValidate()
        {
            EnsurePointCloud2NativeTfAnchorInitialized();
        }

        private void EnsurePointCloud2NativeTfAnchorInitialized()
        {
            if (_pointCloud2NativeTfAnchorInitialized)
                return;

            _publishPointCloud2NativeTfAnchor = true;
            _pointCloud2NativeTfAnchorInitialized = true;
        }

        private static string SanitizeNonEmptyFrameId(string raw, string fallback)
        {
            var value = string.IsNullOrWhiteSpace(raw) ? fallback : raw.Trim();
            return SanitizeFrameId(value, fallback);
        }

        private static Quaternion RosRollPitchYawDegreesToQuaternion(Vector3 rollPitchYawDegrees)
        {
            var roll = rollPitchYawDegrees.x * Math.PI / 180.0;
            var pitch = rollPitchYawDegrees.y * Math.PI / 180.0;
            var yaw = rollPitchYawDegrees.z * Math.PI / 180.0;

            var cr = Math.Cos(roll * 0.5);
            var sr = Math.Sin(roll * 0.5);
            var cp = Math.Cos(pitch * 0.5);
            var sp = Math.Sin(pitch * 0.5);
            var cy = Math.Cos(yaw * 0.5);
            var sy = Math.Sin(yaw * 0.5);

            return new Quaternion(
                (float)(sr * cp * cy - cr * sp * sy),
                (float)(cr * sp * cy + sr * cp * sy),
                (float)(cr * cp * sy - sr * sp * cy),
                (float)(cr * cp * cy + sr * sp * sy));
        }

        protected override void Reset()
        {
            base.Reset();
            EnsurePointCloud2NativeTfAnchorInitialized();
            _samplingMode = PointCloudSamplingMode.UniformStride;
        }

        protected override void OnDisable()
        {
            _lastNativeDracoPublishUnixNs = 0UL;
            _hasSourceDrivenFrames = false;
            _warnedTransformFallbackSuppressed = false;
            StopDracoEncodeWorker(clearCompleted: true);
            StopPointCloud2NativeWorker(clearCompleted: true);
            base.OnDisable();
        }

        private void OnDestroy()
        {
            StopDracoEncodeWorker(clearCompleted: true);
            StopPointCloud2NativeWorker(clearCompleted: true);
        }

        /// <summary>
        /// Queue a decoded frame for the next publish tick.
        /// This is a last-value-wins buffer: a new frame replaces stale pending data.
        /// </summary>
        public void SetFrame(PointCloudFrame frame)
        {
            if (frame != null)
                MarkSourceDrivenPointCloud();

            bool hadPendingFrame;
            lock (_pendingFrameGate)
            {
                hadPendingFrame = _pendingFrame != null;
                _pendingFrame = frame;
            }

            if (hadPendingFrame && frame != null && _logQosDrops && !_warnedPendingDrop)
            {
                Debug.LogWarning("[Foxglove] PointCloud pending frame replaced; stale pending frame dropped.");
                _warnedPendingDrop = true;
            }

            if (hadPendingFrame && frame != null)
                RecordPointCloudDrop();
        }

        /// <summary>
        /// Publish a decoded frame immediately, bypassing the regular Update cadence.
        /// </summary>
        /// <remarks>
        /// Use the supplied timestamp to keep LiDAR timing aligned with IMU/TF inputs.
        /// </remarks>
        public void PublishFrame(PointCloudFrame frame, ulong logTimeNs)
        {
            if (frame != null)
                MarkSourceDrivenPointCloud();

            ResolveManager();
            if (_manager == null || frame == null) return;
            var publishWebSocket = ShouldPreparePublishPayload();
            var publishBridge = ShouldPrepareRos2BridgePayload();
            var publishNativeFrame = ShouldPreparePointCloud2NativeFrame();
            if (!publishWebSocket && !publishBridge && !publishNativeFrame) return;

            var prepared = PrepareFrameForQoS(frame, logTimeNs);
            if (prepared == null || prepared.GetPointCount() == 0) return;
            SetPreparedPublishDemand(publishWebSocket, publishBridge);
            try
            {
                PublishPreparedFrame(prepared, logTimeNs);
                LogPointCloudDiagnosticsIfReady();
            }
            finally
            {
                ClearPreparedPublishDemand();
            }
        }

        /// <summary>
        /// Queues a source VirtualLidar snapshot into the Draco worker when the
        /// selected mode is compatible.
        /// </summary>
        internal bool TryQueueVirtualLidarDracoFrame(
            VirtualLidarPointData[] points,
            int pointCount,
            ulong unixNs,
            string frameId,
            bool emitAbsoluteTimeNs)
        {
            if (!CanQueueVirtualLidarDracoFrame)
                return false;

            if (points != null && pointCount > 0)
                MarkSourceDrivenPointCloud();

            ResolveManager();
            if (_manager == null || _manager.Runtime?.ReplayEnabled == true)
                return true;

            var publishWebSocket = ShouldPreparePublishPayload();
            var publishBridge = ShouldPrepareRos2BridgePayload();
            if (!publishWebSocket && !publishBridge)
                return true;

            if (!ShouldQueueVirtualLidarDracoFrame(unixNs))
                return true;

            QueueVirtualLidarDracoEncode(
                points,
                pointCount,
                unixNs,
                frameId,
                emitAbsoluteTimeNs,
                publishWebSocket,
                publishBridge,
                EffectiveEncoding);
            return true;
        }

        /// <summary>
        /// Queues a source VirtualLidar snapshot into the PointCloud2 Native
        /// worker when the selected mode is compatible.
        /// </summary>
        internal bool TryQueueVirtualLidarPointCloud2NativeFrame(
            VirtualLidarPointData[] points,
            int pointCount,
            ulong unixNs,
            string frameId,
            bool emitAbsoluteTimeNs)
        {
            if (!CanQueueVirtualLidarPointCloud2NativeFrame)
                return false;

            if (points != null && pointCount > 0)
                MarkSourceDrivenPointCloud();

            ResolveManager();
            if (_manager == null || _manager.Runtime?.ReplayEnabled == true)
                return true;

            var publishWebSocket = ShouldPreparePublishPayload();
            var publishBridge = ShouldPrepareRos2BridgePayload();
            var publishNativeFrame = ShouldPreparePointCloud2NativeFrame();
            if (!publishWebSocket && !publishBridge && !publishNativeFrame)
                return true;

            QueueVirtualLidarPointCloud2Native(
                points,
                pointCount,
                unixNs,
                frameId,
                emitAbsoluteTimeNs,
                publishWebSocket,
                publishBridge,
                publishNativeFrame,
                EffectiveEncoding);
            return true;
        }

        private bool ShouldQueueVirtualLidarDracoFrame(ulong unixNs)
        {
            var rateHz = _nativeDracoMaxPublishRateHz;
            if (rateHz <= 0f)
                return true;

            var intervalNs = (ulong)Math.Max(1d, Math.Round(1_000_000_000d / rateHz));
            var timestampNs = unixNs == 0UL ? FoxgloveTimeUtil.NowUnixTimeNs() : unixNs;

            if (_lastNativeDracoPublishUnixNs != 0UL
                && timestampNs >= _lastNativeDracoPublishUnixNs
                && timestampNs - _lastNativeDracoPublishUnixNs < intervalNs)
            {
                RecordPointCloudDrop();
                return false;
            }

            _lastNativeDracoPublishUnixNs = timestampNs;
            return true;
        }

        protected virtual void Update()
        {
            if (_manager == null) return;
            if (_manager.Runtime?.ReplayEnabled == true) return;
            DrainCompletedDracoEncode();
            DrainCompletedPointCloud2Native();
            if (!_publishOnEnable) return;
            if (!ShouldPublishNow()) return;
            var publishWebSocket = ShouldPreparePublishPayload();
            var publishBridge = ShouldPrepareRos2BridgePayload();
            var publishNativeFrame = ShouldPreparePointCloud2NativeFrame();
            if (!publishWebSocket && !publishBridge && !publishNativeFrame) return;

            var unixNs = CurrentLogTimeNs;
            PointCloudFrame pendingFrame;
            lock (_pendingFrameGate)
            {
                pendingFrame = _pendingFrame;
                _pendingFrame = null;
            }

            // A source frame that carries its own timestamp (e.g. VirtualLidar's physics-time
            // scan start) drives the log time too, so payload time == log time (matching the
            // IMU path) and SLAM consumers see one consistent clock instead of a wall-clock vs
            // physics-clock skew that drifts under frame-rate stalls.
            if (pendingFrame != null && pendingFrame.UnixNs != 0)
                unixNs = pendingFrame.UnixNs;

            if (pendingFrame == null && ShouldSuppressTransformFallback())
            {
                if (_logQosDrops && !_warnedTransformFallbackSuppressed)
                {
                    Debug.LogWarning("[Foxglove] PointCloud transform fallback suppressed after source-driven frames; real LiDAR/source frames will own this topic.");
                    _warnedTransformFallbackSuppressed = true;
                }
                return;
            }

            var frame = pendingFrame != null ? PrepareFrameForQoS(pendingFrame, unixNs) : PrepareFrameForQoS(CreateFrameFromTransforms(unixNs), unixNs);
            _warnedPendingDrop = false;
            if (frame == null || frame.GetPointCount() == 0) return;

            SetPreparedPublishDemand(publishWebSocket, publishBridge);
            try
            {
                PublishPreparedFrame(frame, unixNs);
                LogPointCloudDiagnosticsIfReady();
            }
            finally
            {
                ClearPreparedPublishDemand();
            }
        }

        protected virtual void PublishPreparedFrame(PointCloudFrame frame, ulong unixNs)
        {
            RecordPointCloudPrepared(frame);

            if (_outputMode == PointCloudOutputMode.Draco)
            {
                PublishDracoFrame(frame, unixNs);
                return;
            }

            if (_outputMode == PointCloudOutputMode.PointCloud2Native)
            {
                PublishPointCloud2NativeFrame(frame, unixNs);
                return;
            }

            PublishRawFrame(frame, unixNs);
        }

        private void PublishRawFrame(PointCloudFrame frame, ulong unixNs)
        {
            if (!TryGetPreparedPublishDemand(out var publishWebSocket, out var publishBridge))
            {
                publishWebSocket = ShouldPreparePublishPayload();
                publishBridge = ShouldPrepareRos2BridgePayload();
            }
            byte[] ros2Payload = null;

            if (publishWebSocket && EffectiveEncoding == PublisherEffectiveEncoding.Protobuf)
            {
                PublishProto(PointCloudMessageBuilder.SerializeProtobuf(frame), unixNs);
            }
            else if (publishWebSocket && EffectiveEncoding == PublisherEffectiveEncoding.Ros2)
            {
                ros2Payload = Ros2CdrPointCloudBuilder.Serialize(frame);
                PublishRos2(ros2Payload, unixNs);
            }
            else if (publishWebSocket)
            {
                Publish(PointCloudMessageBuilder.CreateJson(frame), unixNs);
            }

            if (publishBridge)
            {
                ros2Payload ??= Ros2CdrPointCloudBuilder.Serialize(frame);
                PublishRos2Bridge(ros2Payload, unixNs);
            }
        }

        private void PublishPointCloud2NativeFrame(PointCloudFrame frame, ulong unixNs)
        {
            if (!TryGetPreparedPublishDemand(out var publishWebSocket, out var publishBridge))
            {
                publishWebSocket = ShouldPreparePublishPayload();
                publishBridge = ShouldPrepareRos2BridgePayload();
            }

            byte[] ros2Payload = null;
            if (publishWebSocket && EffectiveEncoding == PublisherEffectiveEncoding.Ros2)
            {
                ros2Payload = Ros2CdrSensorPointCloud2Builder.Serialize(frame);
                PublishRos2(ros2Payload, unixNs);
            }

            if (publishBridge)
            {
                ros2Payload ??= Ros2CdrSensorPointCloud2Builder.Serialize(frame);
                PublishRos2Bridge(ros2Payload, unixNs);
            }

            if (ShouldPreparePointCloud2NativeFrame())
                PublishPreparedPointCloud2NativeFrame(frame, unixNs);
        }

        private bool ShouldPreparePointCloud2NativeFrame()
            => _outputMode == PointCloudOutputMode.PointCloud2Native
               && PointCloud2NativeFrameReady != null;

        private void PublishPreparedPointCloud2NativeFrame(PointCloudFrame frame, ulong unixNs)
        {
            var handler = PointCloud2NativeFrameReady;
            if (handler == null || frame == null)
                return;

            try
            {
                var packed = PointCloudPackedDataBuilder.Build(frame);
                var nativeFrame = new PointCloud2NativeFrame(
                    unixNs,
                    string.IsNullOrEmpty(frame.FrameId) ? _frameId : frame.FrameId,
                    height: 1U,
                    width: checked((uint)frame.GetPointCount()),
                    fields: packed.Fields,
                    pointStep: packed.PointStride,
                    data: packed.Data,
                    isDense: true);
                handler(nativeFrame);
            }
            catch (Exception ex)
            {
                Debug.LogWarning("[Foxglove] PointCloud2 native frame subscriber failed: " + ex.Message);
            }
        }

        private void PublishDracoFrame(PointCloudFrame frame, ulong unixNs)
        {
            if (frame == null || frame.GetPointCount() == 0)
                return;

            QueueDracoEncode(frame, unixNs);
        }

        private void QueueDracoEncode(PointCloudFrame frame, ulong unixNs)
        {
            if (!TryGetPreparedPublishDemand(out var publishWebSocket, out var publishBridge))
            {
                publishWebSocket = ShouldPreparePublishPayload();
                publishBridge = ShouldPrepareRos2BridgePayload();
            }

            // No main-thread clone. VirtualLidar allocates a fresh PointCloudFrame for every
            // scan (StartNewScan) and never mutates a frame after handing it to SetFrame, so
            // the background worker can read this frame directly. Cloning 262144 points on the
            // Update thread was the dominant per-frame main-thread spike that stalled the loop.
            var request = new DracoEncodeRequest(
                frame,
                unixNs,
                publishWebSocket,
                publishBridge,
                EffectiveEncoding,
                0d);
            EnqueueDracoEncodeRequest(request);
        }

        private void QueueVirtualLidarDracoEncode(
            VirtualLidarPointData[] points,
            int pointCount,
            ulong unixNs,
            string frameId,
            bool emitAbsoluteTimeNs,
            bool publishWebSocket,
            bool publishBridge,
            PublisherEffectiveEncoding webSocketEncoding)
        {
            if (points == null || pointCount <= 0)
                return;

            RecordPointCloudPrepared(pointCount);
            var request = new DracoEncodeRequest(
                points,
                pointCount,
                unixNs,
                string.IsNullOrEmpty(frameId) ? _frameId : frameId,
                emitAbsoluteTimeNs,
                publishWebSocket,
                publishBridge,
                webSocketEncoding,
                0d);
            EnqueueDracoEncodeRequest(request);
        }

        private void QueueVirtualLidarPointCloud2Native(
            VirtualLidarPointData[] points,
            int pointCount,
            ulong unixNs,
            string frameId,
            bool emitAbsoluteTimeNs,
            bool publishWebSocket,
            bool publishBridge,
            bool publishNativeFrame,
            PublisherEffectiveEncoding webSocketEncoding)
        {
            if (points == null || pointCount <= 0)
                return;

            RecordPointCloudPrepared(pointCount);
            var request = new PointCloud2NativeRequest(
                points,
                pointCount,
                unixNs,
                string.IsNullOrEmpty(frameId) ? _frameId : frameId,
                emitAbsoluteTimeNs,
                publishWebSocket,
                publishBridge,
                publishNativeFrame,
                webSocketEncoding);
            EnqueuePointCloud2NativeRequest(request);
        }

        /// <summary>
        /// Marks this publisher as source-driven so transform fallback frames do
        /// not overwrite real LiDAR output.
        /// </summary>
        internal void MarkSourceDrivenPointCloud()
        {
            _hasSourceDrivenFrames = true;
        }

        private bool ShouldSuppressTransformFallback()
            => _suppressTransformFallbackAfterSourceFrames && _hasSourceDrivenFrames;

        private void EnqueueDracoEncodeRequest(DracoEncodeRequest request)
        {
            var startWorker = false;
            var workerGeneration = 0;
            lock (_dracoEncodeWorker.Gate)
            {
                if (_pendingDracoEncode != null && _logQosDrops && !_warnedDracoBacklog)
                {
                    Debug.LogWarning("[Foxglove] Draco point-cloud encode request replaced; stale pending encode dropped.");
                    _warnedDracoBacklog = true;
                }

                if (_pendingDracoEncode != null)
                    RecordPointCloudDrop();

                workerGeneration = _dracoEncodeWorker.StartOrReuseLocked(out startWorker);
                request.Generation = workerGeneration;
                _pendingDracoEncode = request;
            }

            if (!startWorker)
                return;

            try
            {
                StartDracoEncodeWorker(workerGeneration);
            }
            catch (Exception ex)
            {
                lock (_dracoEncodeWorker.Gate)
                    _dracoEncodeWorker.MarkStartFailedIfCurrentLocked(workerGeneration);
                LogDracoFailure("Unable to queue background Draco encode: " + ex.Message);
            }
        }

        private void EnqueuePointCloud2NativeRequest(PointCloud2NativeRequest request)
        {
            var startWorker = false;
            var workerGeneration = 0;
            lock (_pointCloud2NativeWorker.Gate)
            {
                if (_pendingPointCloud2Native != null && _logQosDrops && !_warnedPointCloud2NativeBacklog)
                {
                    Debug.LogWarning("[Foxglove] PointCloud2 native request replaced; stale pending payload dropped.");
                    _warnedPointCloud2NativeBacklog = true;
                }

                if (_pendingPointCloud2Native != null)
                    RecordPointCloudDrop();

                workerGeneration = _pointCloud2NativeWorker.StartOrReuseLocked(out startWorker);
                request.Generation = workerGeneration;
                _pendingPointCloud2Native = request;
            }

            if (!startWorker)
                return;

            try
            {
                StartPointCloud2NativeWorker(workerGeneration);
            }
            catch (Exception ex)
            {
                lock (_pointCloud2NativeWorker.Gate)
                    _pointCloud2NativeWorker.MarkStartFailedIfCurrentLocked(workerGeneration);
                LogPointCloud2NativeFailure("Unable to queue background PointCloud2 pack: " + ex.Message);
            }
        }

        private void StartDracoEncodeWorker(int workerGeneration)
        {
            var worker = new System.Threading.Thread(RunDracoEncodeWorker)
            {
                IsBackground = true,
                Name = "Foxglove Draco PointCloud Encode",
                Priority = System.Threading.ThreadPriority.BelowNormal
            };
            worker.Start(workerGeneration);
        }

        private void StartPointCloud2NativeWorker(int workerGeneration)
        {
            var worker = new System.Threading.Thread(() => RunPointCloud2NativeWorker(workerGeneration))
            {
                IsBackground = true,
                Name = "Foxglove PointCloud2 Native Pack",
                Priority = System.Threading.ThreadPriority.BelowNormal
            };
            worker.Start();
        }

        private void RunDracoEncodeWorker(object state)
        {
            RunDracoEncodeWorker((int)state);
        }

        private void RunDracoEncodeWorker(int workerGeneration)
        {
            try
            {
                while (true)
                {
                    DracoEncodeRequest request;
                    lock (_dracoEncodeWorker.Gate)
                    {
                        if (_dracoEncodeWorker.ShouldStopLocked(workerGeneration))
                        {
                            _dracoEncodeWorker.MarkStoppedIfCurrentLocked(workerGeneration);
                            return;
                        }

                        request = _pendingDracoEncode;
                        _pendingDracoEncode = null;
                        if (request == null)
                        {
                            _dracoEncodeWorker.MarkStoppedIfCurrentLocked(workerGeneration);
                            return;
                        }
                    }

                    if (request.Generation != workerGeneration)
                        continue;

                    var result = EncodeDracoRequest(request);
                    lock (_dracoEncodeWorker.Gate)
                    {
                        if (_dracoEncodeWorker.ShouldStopLocked(workerGeneration)
                            || request.Generation != workerGeneration)
                            continue;

                        while (_completedDracoEncodes.Count >= MaxCompletedDracoEncodeResults)
                        {
                            _completedDracoEncodes.Dequeue();
                            _droppedCompletedDracoEncodeCount++;
                        }

                        _completedDracoEncodes.Enqueue(result);
                    }
                }
            }
            finally
            {
                var signalIdle = false;
                lock (_dracoEncodeWorker.Gate)
                    signalIdle = _dracoEncodeWorker.MarkStoppedIfCurrentLocked(workerGeneration);

                if (signalIdle)
                    _dracoEncodeWorker.Idle.Set();
            }
        }

        private void RunPointCloud2NativeWorker(int workerGeneration)
        {
            try
            {
                while (true)
                {
                    PointCloud2NativeRequest request;
                    lock (_pointCloud2NativeWorker.Gate)
                    {
                        if (_pointCloud2NativeWorker.ShouldStopLocked(workerGeneration))
                        {
                            _pointCloud2NativeWorker.MarkStoppedIfCurrentLocked(workerGeneration);
                            return;
                        }

                        request = _pendingPointCloud2Native;
                        _pendingPointCloud2Native = null;
                        if (request == null)
                        {
                            _pointCloud2NativeWorker.MarkStoppedIfCurrentLocked(workerGeneration);
                            return;
                        }
                    }

                    if (request.Generation != workerGeneration)
                        continue;

                    var result = EncodePointCloud2NativeRequest(request);
                    lock (_pointCloud2NativeWorker.Gate)
                    {
                        if (_pointCloud2NativeWorker.ShouldStopLocked(workerGeneration)
                            || request.Generation != workerGeneration)
                            continue;

                        while (_completedPointCloud2Native.Count >= MaxCompletedPointCloud2NativeResults)
                        {
                            _completedPointCloud2Native.Dequeue();
                            _droppedCompletedPointCloud2NativeCount++;
                        }

                        _completedPointCloud2Native.Enqueue(result);
                    }
                }
            }
            finally
            {
                var signalIdle = false;
                lock (_pointCloud2NativeWorker.Gate)
                    signalIdle = _pointCloud2NativeWorker.MarkStoppedIfCurrentLocked(workerGeneration);

                if (signalIdle)
                    _pointCloud2NativeWorker.Idle.Set();
            }
        }

        private static DracoEncodeResult EncodeDracoRequest(DracoEncodeRequest request)
        {
            var encodeStart = Stopwatch.GetTimestamp();
            var success = false;
            var error = "";
            byte[] dracoPayload = null;
            var metadataFrame = request.Frame;
            var validCount = 0;

            if (request.HasVirtualLidarSnapshot)
            {
                success = DracoPointCloudNativeEncoder.TryEncodeVirtualLidarPoints(
                    request.LidarPoints,
                    request.LidarPointCount,
                    out dracoPayload,
                    out error,
                    out validCount);
                metadataFrame = new PointCloudFrame
                {
                    UnixNs = request.UnixNs,
                    FrameId = request.FrameId,
                    ValidCount = validCount,
                    EmitAbsoluteTimeNs = request.EmitAbsoluteTimeNs
                };
            }
            else
            {
                success = DracoPointCloudNativeEncoder.TryEncode(request.Frame, out dracoPayload, out error);
            }

            byte[] webSocketPayload = null;
            byte[] bridgePayload = null;
            if (success)
            {
                try
                {
                    BuildDracoPublishPayloads(
                        request,
                        metadataFrame,
                        dracoPayload,
                        out webSocketPayload,
                        out bridgePayload);
                }
                catch (Exception ex)
                {
                    success = false;
                    error = "Unable to serialize compressed point-cloud payload off thread: " + ex.Message;
                }
            }

            return new DracoEncodeResult(
                request,
                metadataFrame,
                success,
                webSocketPayload,
                bridgePayload,
                error,
                (Stopwatch.GetTimestamp() - encodeStart) * 1000d / Stopwatch.Frequency);
        }

        private static PointCloud2NativeResult EncodePointCloud2NativeRequest(PointCloud2NativeRequest request)
        {
            var encodeStart = Stopwatch.GetTimestamp();
            var success = false;
            var error = "";
            byte[] webSocketPayload = null;
            byte[] bridgePayload = null;
            PointCloud2NativeFrame nativeFrame = null;
            var validCount = 0;
            var payloadBytes = 0;

            try
            {
                var packed = PointCloud2PackedDataBuilder.BuildVirtualLidarFullStride(
                    request.LidarPoints,
                    request.LidarPointCount,
                    request.EmitAbsoluteTimeNs);
                validCount = packed.PointStride == 0U ? 0 : checked((int)(packed.Data.Length / packed.PointStride));
                nativeFrame = BuildPointCloud2NativeFrame(request, packed, validCount);

                byte[] ros2Payload = null;
                if (request.PublishWebSocket && request.WebSocketEncoding == PublisherEffectiveEncoding.Ros2)
                {
                    ros2Payload = BuildPointCloud2NativePayload(nativeFrame);
                    webSocketPayload = ros2Payload;
                }

                if (request.PublishBridge)
                {
                    ros2Payload ??= BuildPointCloud2NativePayload(nativeFrame);
                    bridgePayload = ros2Payload;
                }

                payloadBytes = ros2Payload?.Length ?? nativeFrame.Data.Length;
                success = true;
            }
            catch (Exception ex)
            {
                error = "Unable to serialize native PointCloud2 payload off thread: " + ex.Message;
            }

            return new PointCloud2NativeResult(
                request,
                success,
                webSocketPayload,
                bridgePayload,
                nativeFrame,
                error,
                validCount,
                payloadBytes,
                (Stopwatch.GetTimestamp() - encodeStart) * 1000d / Stopwatch.Frequency);
        }

        private static PointCloud2NativeFrame BuildPointCloud2NativeFrame(
            PointCloud2NativeRequest request,
            PointCloudPackedData packed,
            int validCount)
        {
            return new PointCloud2NativeFrame(
                request.UnixNs,
                request.FrameId,
                height: 1U,
                width: checked((uint)validCount),
                fields: packed.Fields,
                pointStep: packed.PointStride,
                data: packed.Data,
                isDense: true);
        }

        private static byte[] BuildPointCloud2NativePayload(PointCloud2NativeFrame frame)
        {
            return Ros2CdrSensorPointCloud2Builder.Serialize(
                frame.UnixNs,
                frame.FrameId,
                frame.Height,
                frame.Width,
                frame.Fields,
                frame.PointStep,
                frame.Data,
                frame.IsDense);
        }

        private static void BuildDracoPublishPayloads(
            DracoEncodeRequest request,
            PointCloudFrame frame,
            byte[] dracoPayload,
            out byte[] webSocketPayload,
            out byte[] bridgePayload)
        {
            webSocketPayload = null;
            bridgePayload = null;
            byte[] ros2Payload = null;

            if (request.PublishWebSocket && request.WebSocketEncoding == PublisherEffectiveEncoding.Ros2)
            {
                ros2Payload = Ros2CdrCompressedPointCloudBuilder.Serialize(frame, dracoPayload);
                webSocketPayload = ros2Payload;
            }
            else if (request.PublishWebSocket)
            {
                webSocketPayload = CompressedPointCloudMessageBuilder.SerializeProtobuf(frame, dracoPayload);
            }

            if (request.PublishBridge)
            {
                ros2Payload ??= Ros2CdrCompressedPointCloudBuilder.Serialize(frame, dracoPayload);
                bridgePayload = ros2Payload;
            }
        }

        private void DrainCompletedDracoEncode()
        {
            List<DracoEncodeResult> results = null;
            int droppedCompletedResults;
            lock (_dracoEncodeWorker.Gate)
            {
                droppedCompletedResults = _droppedCompletedDracoEncodeCount;
                _droppedCompletedDracoEncodeCount = 0;
                if (_completedDracoEncodes.Count > 0)
                {
                    results = new List<DracoEncodeResult>(_completedDracoEncodes);
                    _completedDracoEncodes.Clear();
                }
            }

            if (droppedCompletedResults > 0 && _logQosDrops)
                Debug.LogWarning($"[Foxglove] Draco point-cloud encode results dropped before main-thread drain: {droppedCompletedResults}.");
            if (droppedCompletedResults > 0)
                RecordPointCloudDrop(droppedCompletedResults);

            if (results == null || results.Count == 0)
                return;

            foreach (var result in results)
            {
                if (!result.Success)
                {
                    LogDracoFailure((string.IsNullOrWhiteSpace(result.Error) ? "Native Draco encode failed." : result.Error) + " Draco mode publishes nothing.");
                    continue;
                }

                _warnedDracoFailure = false;
                _dracoFailureCount = 0;
                _warnedDracoBacklog = false;
                RecordPointCloudEncodeResult(result);
                PublishCompletedDracoPayload(result);
            }

            LogPointCloudDiagnosticsIfReady();
        }

        private void DrainCompletedPointCloud2Native()
        {
            List<PointCloud2NativeResult> results = null;
            int droppedCompletedResults;
            lock (_pointCloud2NativeWorker.Gate)
            {
                droppedCompletedResults = _droppedCompletedPointCloud2NativeCount;
                _droppedCompletedPointCloud2NativeCount = 0;
                if (_completedPointCloud2Native.Count > 0)
                {
                    results = new List<PointCloud2NativeResult>(_completedPointCloud2Native);
                    _completedPointCloud2Native.Clear();
                }
            }

            if (droppedCompletedResults > 0 && _logQosDrops)
                Debug.LogWarning($"[Foxglove] PointCloud2 native payloads dropped before main-thread drain: {droppedCompletedResults}.");
            if (droppedCompletedResults > 0)
                RecordPointCloudDrop(droppedCompletedResults);

            if (results == null || results.Count == 0)
                return;

            foreach (var result in results)
            {
                if (!result.Success)
                {
                    LogPointCloud2NativeFailure((string.IsNullOrWhiteSpace(result.Error) ? "Native PointCloud2 pack failed." : result.Error) + " PointCloud2Native mode publishes nothing.");
                    continue;
                }

                _warnedPointCloud2NativeFailure = false;
                _pointCloud2NativeFailureCount = 0;
                _warnedPointCloud2NativeBacklog = false;
                RecordPointCloud2NativeResult(result);
                PublishCompletedPointCloud2NativePayload(result);
            }

            LogPointCloudDiagnosticsIfReady();
        }

        private void StopDracoEncodeWorker(bool clearCompleted)
        {
            var shouldWait = false;
            lock (_dracoEncodeWorker.Gate)
            {
                _dracoEncodeWorker.RequestStopLocked();
                _pendingDracoEncode = null;
                shouldWait = _dracoEncodeWorker.IsRunning;
                if (clearCompleted)
                {
                    _completedDracoEncodes.Clear();
                    _droppedCompletedDracoEncodeCount = 0;
                }
            }

            if (!shouldWait)
                return;

            if (_dracoEncodeWorker.Idle.Wait(DracoWorkerStopWaitMs))
            {
                _warnedDracoWorkerShutdown = false;
                return;
            }

            if (!_warnedDracoWorkerShutdown)
            {
                Debug.LogWarning("[Foxglove] Draco point-cloud encode worker is still stopping; native encode will be ignored when it returns.");
                _warnedDracoWorkerShutdown = true;
            }

            lock (_dracoEncodeWorker.Gate)
                _dracoEncodeWorker.InvalidateTimedOutWorkerLocked();
        }

        private void StopPointCloud2NativeWorker(bool clearCompleted)
        {
            var shouldWait = false;
            lock (_pointCloud2NativeWorker.Gate)
            {
                _pointCloud2NativeWorker.RequestStopLocked();
                _pendingPointCloud2Native = null;
                shouldWait = _pointCloud2NativeWorker.IsRunning;
                if (clearCompleted)
                {
                    _completedPointCloud2Native.Clear();
                    _droppedCompletedPointCloud2NativeCount = 0;
                }
            }

            if (!shouldWait)
                return;

            if (_pointCloud2NativeWorker.Idle.Wait(PointCloud2NativeWorkerStopWaitMs))
            {
                _warnedPointCloud2NativeWorkerShutdown = false;
                return;
            }

            if (!_warnedPointCloud2NativeWorkerShutdown)
            {
                Debug.LogWarning("[Foxglove] PointCloud2 native worker is still stopping; native payload will be ignored when it returns.");
                _warnedPointCloud2NativeWorkerShutdown = true;
            }

            lock (_pointCloud2NativeWorker.Gate)
                _pointCloud2NativeWorker.InvalidateTimedOutWorkerLocked();
        }

        private void PublishCompletedDracoPayload(DracoEncodeResult result)
        {
            if (result.Request.PublishWebSocket && result.Request.WebSocketEncoding == PublisherEffectiveEncoding.Ros2)
            {
                PublishRos2(result.WebSocketPayload, result.Request.UnixNs);
            }
            else if (result.Request.PublishWebSocket)
            {
                PublishProto(result.WebSocketPayload, result.Request.UnixNs);
            }

            if (result.Request.PublishBridge)
                PublishRos2Bridge(result.BridgePayload, result.Request.UnixNs);
        }

        private void PublishCompletedPointCloud2NativePayload(PointCloud2NativeResult result)
        {
            if (result.Request.PublishWebSocket && result.Request.WebSocketEncoding == PublisherEffectiveEncoding.Ros2)
                PublishRos2(result.WebSocketPayload, result.Request.UnixNs);

            if (result.Request.PublishBridge)
                PublishRos2Bridge(result.BridgePayload, result.Request.UnixNs);

            if (result.Request.PublishNativeFrame && result.NativeFrame != null)
            {
                var handler = PointCloud2NativeFrameReady;
                if (handler == null)
                    return;

                try
                {
                    handler(result.NativeFrame);
                }
                catch (Exception ex)
                {
                    Debug.LogWarning("[Foxglove] PointCloud2 native frame subscriber failed: " + ex.Message);
                }
            }
        }

        private void SetPreparedPublishDemand(bool publishWebSocket, bool publishBridge)
        {
            _preparedPublishWebSocket = publishWebSocket;
            _preparedPublishBridge = publishBridge;
            _hasPreparedPublishDemand = true;
        }

        private void ClearPreparedPublishDemand()
        {
            _hasPreparedPublishDemand = false;
            _preparedPublishWebSocket = false;
            _preparedPublishBridge = false;
        }

        private bool TryGetPreparedPublishDemand(out bool publishWebSocket, out bool publishBridge)
        {
            publishWebSocket = _preparedPublishWebSocket;
            publishBridge = _preparedPublishBridge;
            return _hasPreparedPublishDemand;
        }

        private void LogDracoFailure(string message)
        {
            _dracoFailureCount++;
            if (_warnedDracoFailure && _dracoFailureCount % DracoFailureWarningIntervalFrames != 0)
                return;

            _warnedDracoFailure = true;
            Debug.LogWarning("[Foxglove] Draco point-cloud mode disabled: " + message);
        }

        private void LogPointCloud2NativeFailure(string message)
        {
            _pointCloud2NativeFailureCount++;
            if (_warnedPointCloud2NativeFailure && _pointCloud2NativeFailureCount % PointCloud2NativeFailureWarningIntervalFrames != 0)
                return;

            _warnedPointCloud2NativeFailure = true;
            Debug.LogWarning("[Foxglove] PointCloud2 native mode disabled: " + message);
        }

        /// <summary>
        /// Captures one background Draco encode request plus the publish routes that
        /// should receive its completed payload.
        /// </summary>
        private sealed class DracoEncodeRequest
        {
            public DracoEncodeRequest(
                PointCloudFrame frame,
                ulong unixNs,
                bool publishWebSocket,
                bool publishBridge,
                PublisherEffectiveEncoding webSocketEncoding,
                double cloneMs)
            {
                Frame = frame;
                UnixNs = unixNs;
                PublishWebSocket = publishWebSocket;
                PublishBridge = publishBridge;
                WebSocketEncoding = webSocketEncoding;
                CloneMs = cloneMs;
            }

            public DracoEncodeRequest(
                VirtualLidarPointData[] lidarPoints,
                int lidarPointCount,
                ulong unixNs,
                string frameId,
                bool emitAbsoluteTimeNs,
                bool publishWebSocket,
                bool publishBridge,
                PublisherEffectiveEncoding webSocketEncoding,
                double cloneMs)
            {
                LidarPoints = lidarPoints;
                LidarPointCount = lidarPointCount;
                UnixNs = unixNs;
                FrameId = frameId;
                EmitAbsoluteTimeNs = emitAbsoluteTimeNs;
                PublishWebSocket = publishWebSocket;
                PublishBridge = publishBridge;
                WebSocketEncoding = webSocketEncoding;
                CloneMs = cloneMs;
            }

            /// <summary>Decoded point cloud frame provided directly to the encoder.</summary>
            public PointCloudFrame Frame { get; }
            /// <summary>Native VirtualLidar snapshot used by the low-allocation Draco path.</summary>
            public VirtualLidarPointData[] LidarPoints { get; }
            /// <summary>Number of valid source slots in <see cref="LidarPoints"/>.</summary>
            public int LidarPointCount { get; }
            /// <summary>Whether this request bypasses the managed PointCloudFrame point list.</summary>
            public bool HasVirtualLidarSnapshot => LidarPoints != null;
            /// <summary>Optional frame id override for source-driven virtual LiDAR snapshots.</summary>
            public string FrameId { get; }
            /// <summary>When true, timestamp in output uses absolute nanoseconds for payload fields.</summary>
            public bool EmitAbsoluteTimeNs { get; }

            /// <summary>Timestamp associated with this payload/request, in nanoseconds.</summary>
            public ulong UnixNs { get; }
            /// <summary>Whether websocket output is expected for this request.</summary>
            public bool PublishWebSocket { get; }
            /// <summary>Whether ROS2 bridge output is expected for this request.</summary>
            public bool PublishBridge { get; }
            /// <summary>Effective encoding for the WebSocket payload, when requested.</summary>
            public PublisherEffectiveEncoding WebSocketEncoding { get; }
            /// <summary>Main-thread frame clone time before background Draco encode.</summary>
            public double CloneMs { get; }
            /// <summary>Worker generation that owns this encode request.</summary>
            public int Generation { get; set; }
        }

        /// <summary>
        /// Captures one background PointCloud2 pack request plus the publish routes
        /// that should receive its completed CDR payload.
        /// </summary>
        private sealed class PointCloud2NativeRequest
        {
            public PointCloud2NativeRequest(
                VirtualLidarPointData[] lidarPoints,
                int lidarPointCount,
                ulong unixNs,
                string frameId,
                bool emitAbsoluteTimeNs,
                bool publishWebSocket,
                bool publishBridge,
                bool publishNativeFrame,
                PublisherEffectiveEncoding webSocketEncoding)
            {
                LidarPoints = lidarPoints;
                LidarPointCount = lidarPointCount;
                UnixNs = unixNs;
                FrameId = frameId;
                EmitAbsoluteTimeNs = emitAbsoluteTimeNs;
                PublishWebSocket = publishWebSocket;
                PublishBridge = publishBridge;
                PublishNativeFrame = publishNativeFrame;
                WebSocketEncoding = webSocketEncoding;
            }

            /// <summary>Native VirtualLidar snapshot used by the PointCloud2 pack path.</summary>
            public VirtualLidarPointData[] LidarPoints { get; }
            /// <summary>Number of source slots in <see cref="LidarPoints"/> to scan.</summary>
            public int LidarPointCount { get; }
            /// <summary>Timestamp associated with this payload/request, in nanoseconds.</summary>
            public ulong UnixNs { get; }
            /// <summary>Frame id written into the PointCloud2 header.</summary>
            public string FrameId { get; }
            /// <summary>When true, point field <c>t</c> is emitted in nanoseconds from scan start.</summary>
            public bool EmitAbsoluteTimeNs { get; }
            /// <summary>Whether websocket output is expected for this request.</summary>
            public bool PublishWebSocket { get; }
            /// <summary>Whether ROS2 bridge output is expected for this request.</summary>
            public bool PublishBridge { get; }
            /// <summary>Whether a schema-neutral native frame event is expected.</summary>
            public bool PublishNativeFrame { get; }
            /// <summary>Effective encoding for the WebSocket payload, when requested.</summary>
            public PublisherEffectiveEncoding WebSocketEncoding { get; }
            /// <summary>Worker generation that owns this pack request.</summary>
            public int Generation { get; set; }
        }

        /// <summary>
        /// Completed background Draco encode result, including prepared websocket and
        /// ROS2 bridge payload bytes for main-thread publish.
        /// </summary>
        private sealed class DracoEncodeResult
        {
            public DracoEncodeResult(
                DracoEncodeRequest request,
                PointCloudFrame frame,
                bool success,
                byte[] webSocketPayload,
                byte[] bridgePayload,
                string error,
                double encodeMs)
            {
                Request = request;
                Frame = frame;
                Success = success;
                WebSocketPayload = webSocketPayload;
                BridgePayload = bridgePayload;
                Error = error;
                EncodeMs = encodeMs;
            }

            /// <summary>Encode request associated with this completion result.</summary>
            public DracoEncodeRequest Request { get; }
            /// <summary>Frame metadata used for diagnostics and fallback result handling.</summary>
            public PointCloudFrame Frame { get; }
            /// <summary>Whether encode and payload preparation completed successfully.</summary>
            public bool Success { get; }
            /// <summary>Websocket payload bytes produced for this completion.</summary>
            public byte[] WebSocketPayload { get; }
            /// <summary>ROS2 bridge payload bytes produced for this completion.</summary>
            public byte[] BridgePayload { get; }
            /// <summary>Error details when encode failed, or empty on success.</summary>
            public string Error { get; }
            /// <summary>Worker-thread native encode time.</summary>
            public double EncodeMs { get; }
        }

        /// <summary>
        /// Completed background PointCloud2 pack result with prepared CDR bytes for
        /// main-thread publish.
        /// </summary>
        private sealed class PointCloud2NativeResult
        {
            public PointCloud2NativeResult(
                PointCloud2NativeRequest request,
                bool success,
                byte[] webSocketPayload,
                byte[] bridgePayload,
                PointCloud2NativeFrame nativeFrame,
                string error,
                int validCount,
                int payloadBytes,
                double encodeMs)
            {
                Request = request;
                Success = success;
                WebSocketPayload = webSocketPayload;
                BridgePayload = bridgePayload;
                NativeFrame = nativeFrame;
                Error = error;
                ValidCount = validCount;
                PayloadBytes = payloadBytes;
                EncodeMs = encodeMs;
            }

            /// <summary>Pack request associated with this completion result.</summary>
            public PointCloud2NativeRequest Request { get; }
            /// <summary>Whether pack and payload preparation completed successfully.</summary>
            public bool Success { get; }
            /// <summary>Websocket ROS2 CDR payload bytes produced for this completion.</summary>
            public byte[] WebSocketPayload { get; }
            /// <summary>ROS2 bridge CDR payload bytes produced for this completion.</summary>
            public byte[] BridgePayload { get; }
            /// <summary>Schema-neutral PointCloud2 frame for optional DDS adapters.</summary>
            public PointCloud2NativeFrame NativeFrame { get; }
            /// <summary>Error details when packing failed, or empty on success.</summary>
            public string Error { get; }
            /// <summary>Number of compacted valid points in the CDR payload.</summary>
            public int ValidCount { get; }
            /// <summary>Serialized PointCloud2 payload bytes.</summary>
            public int PayloadBytes { get; }
            /// <summary>Worker-thread pack and CDR serialization time.</summary>
            public double EncodeMs { get; }
        }

        private long DiagnosticStart()
            => _logPerformanceDiagnostics ? Stopwatch.GetTimestamp() : 0L;

        private double DiagnosticElapsedMs(long startTicks)
            => startTicks == 0L
                ? 0d
                : (Stopwatch.GetTimestamp() - startTicks) * 1000d / Stopwatch.Frequency;

        private void RecordPointCloudPrepared(PointCloudFrame frame)
        {
            if (frame == null)
                return;

            RecordPointCloudPrepared(frame.GetPointCount());
        }

        private void RecordPointCloudPrepared(int pointCount)
        {
            if (!_logPerformanceDiagnostics)
                return;

            _diagnosticFrames++;
            _diagnosticPreparedPoints += Math.Max(0, pointCount);
        }

        private void RecordPointCloudDrop(int count = 1)
        {
            if (!_logPerformanceDiagnostics)
                return;

            _diagnosticDrops += Math.Max(1, count);
        }

        private void RecordPointCloudEncodeResult(DracoEncodeResult result)
        {
            if (!_logPerformanceDiagnostics || result == null)
                return;

            _diagnosticCloneMsTotal += result.Request.CloneMs;
            _diagnosticCloneMsMax = Math.Max(_diagnosticCloneMsMax, result.Request.CloneMs);
            _diagnosticEncodeMsTotal += result.EncodeMs;
            _diagnosticEncodeMsMax = Math.Max(_diagnosticEncodeMsMax, result.EncodeMs);
            _diagnosticEncodeResults++;
        }

        private void RecordPointCloud2NativeResult(PointCloud2NativeResult result)
        {
            if (!_logPerformanceDiagnostics || result == null)
                return;

            _diagnosticEncodeMsTotal += result.EncodeMs;
            _diagnosticEncodeMsMax = Math.Max(_diagnosticEncodeMsMax, result.EncodeMs);
            _diagnosticEncodeResults++;
        }

        private void LogPointCloudDiagnosticsIfReady()
        {
            if (!_logPerformanceDiagnostics || _diagnosticFrames < PointCloudDiagnosticsIntervalFrames)
                return;

            var frameDivisor = Math.Max(1, _diagnosticFrames);
            var encodeDivisor = Math.Max(1, _diagnosticEncodeResults);
            Debug.LogFormat(
                LogType.Log,
                LogOption.NoStacktrace,
                this,
                "[PointCloudDiag] prepared={0} points={1} avgPoints={2:F0} cloneMs avg={3:F2} max={4:F2} encodeMs avg={5:F2} max={6:F2} drop={7}",
                _diagnosticFrames,
                _diagnosticPreparedPoints,
                (double)_diagnosticPreparedPoints / frameDivisor,
                _diagnosticCloneMsTotal / encodeDivisor,
                _diagnosticCloneMsMax,
                _diagnosticEncodeMsTotal / encodeDivisor,
                _diagnosticEncodeMsMax,
                _diagnosticDrops);

            _diagnosticFrames = 0;
            _diagnosticPreparedPoints = 0;
            _diagnosticDrops = 0;
            _diagnosticCloneMsTotal = 0d;
            _diagnosticCloneMsMax = 0d;
            _diagnosticEncodeMsTotal = 0d;
            _diagnosticEncodeMsMax = 0d;
            _diagnosticEncodeResults = 0;
        }

        protected virtual PointCloudFrame PrepareFrameForQoS(PointCloudFrame frame, ulong unixNs)
        {
            if (frame == null)
                return null;

            var pointCount = frame.GetPointCount();
            var stride = PointCloudQoS.ComputePackedStride(frame);
            var pointBudget = PointCloudQoS.ComputeEffectivePointBudget(
                pointCount,
                _maxPoints,
                Math.Max(0, _maxPackedBytes),
                stride);

            if (pointBudget <= 0)
            {
                WarnPointCloudReduced(pointCount, pointBudget);
                return null;
            }

            var useVoxelGrid = _samplingMode == PointCloudSamplingMode.VoxelGrid && _voxelSizeMeters > 0f;
            var forceUniformFallback = _samplingMode == PointCloudSamplingMode.VoxelGrid && _voxelSizeMeters <= 0f;

            if (!useVoxelGrid && !forceUniformFallback && frame.UnixNs != 0 && !string.IsNullOrEmpty(frame.FrameId) && pointCount <= pointBudget)
            {
                _warnedPointCloudBudget = false;
                return frame;
            }

            var copy = new PointCloudFrame
            {
                UnixNs = frame.UnixNs == 0 ? unixNs : frame.UnixNs,
                FrameId = string.IsNullOrEmpty(frame.FrameId) ? _frameId : frame.FrameId
            };

            if (useVoxelGrid)
            {
                var voxelIndices = PointCloudQoS.BuildVoxelSampleIndices(frame, _voxelSizeMeters);
                if (voxelIndices.Length <= pointBudget)
                {
                    foreach (var index in voxelIndices)
                        copy.Points.Add(frame.Points[index]);
                }
                else
                {
                    var indices = PointCloudQoS.BuildUniformSampleIndices(voxelIndices.Length, pointBudget);
                    foreach (var index in indices)
                        copy.Points.Add(frame.Points[voxelIndices[index]]);
                }
            }
            else if (pointCount <= pointBudget && !forceUniformFallback)
            {
                for (var i = 0; i < pointCount; i++)
                    copy.Points.Add(frame.Points[i]);
            }
            else if (_samplingMode == PointCloudSamplingMode.FirstPoints)
            {
                var count = Math.Min(pointCount, pointBudget);
                for (var i = 0; i < count; i++)
                    copy.Points.Add(frame.Points[i]);
            }
            else
            {
                var indices = PointCloudQoS.BuildUniformSampleIndices(pointCount, pointBudget);
                foreach (var index in indices)
                    copy.Points.Add(frame.Points[index]);
            }

            if (pointCount > pointBudget)
                WarnPointCloudReduced(pointCount, pointBudget);
            else
            {
                _warnedPointCloudBudget = false;
            }

            copy.ValidCount = copy.Points.Count;

            return copy;
        }

        private void WarnPointCloudReduced(int originalPoints, int outputPoints)
        {
            if (!_logQosDrops) return;
            if (_warnedPointCloudBudget) return;

            Debug.LogWarning(
                $"[Foxglove] PointCloud frame reduced from {originalPoints} to {Math.Max(0, outputPoints)} points.");
            _warnedPointCloudBudget = true;
        }

        private PointCloudFrame CreateFrameFromTransforms(ulong unixNs)
        {
            var frame = new PointCloudFrame
            {
                UnixNs = unixNs,
                FrameId = SanitizeFrameId(_frameId, "unity_world")
            };

            var added = 0;
            if (_pointSources != null && _pointSources.Length > 0)
            {
                foreach (var source in _pointSources)
                    AddPoint(frame, source, ref added);
            }
            else if (_useChildrenWhenSourcesEmpty)
            {
                for (var i = 0; i < transform.childCount; i++)
                {
                    var child = transform.GetChild(i);
                    if (!_includeInactiveChildren && !child.gameObject.activeInHierarchy)
                        continue;
                    AddPoint(frame, child, ref added);
                }
            }

            return frame;
        }

        private void AddPoint(PointCloudFrame frame, Transform source, ref int added)
        {
            if (source == null || added >= Math.Max(1, _maxPoints)) return;

            UVector3 pos = Manager != null && Manager.ActiveCoordinateMode == CoordinateMode.RightHand
                ? CoordinateConverter.UnityToFoxglovePosition(source.position)
                : source.position;

            var point = new PointCloudPoint(pos.x, pos.y, pos.z);
            if (_includeSyntheticIntensity)
                point.Intensity = added;
            frame.Points.Add(point);
            added++;
        }
    }
}
