// Copyright (c) 2026 Jianbin Liu and Unity2Foxglove contributors.
// SPDX-License-Identifier: Apache-2.0
//
// Module: Editor/SourceGenerators
// Purpose: Emits generated source carrying the FoxRun descriptor JSON.

using System;
using System.Globalization;
using System.Text;

namespace Unity.FoxgloveSDK.SourceGenerators
{
    internal static class FoxRunDescriptorCarrierEmitter
    {
        public static string DescriptorCarrierSource(string descriptorJson)
        {
            var escaped = EscapeStringLiteral(descriptorJson);
            if (escaped.Length > 60000)
                return ChunkedDescriptorCarrierSource(escaped);

            return "// <auto-generated/>\n"
                   + "namespace Unity.FoxgloveSDK.Generated\n"
                   + "{\n"
                   + "    internal static class FoxRunGeneratedDescriptorInfo\n"
                   + "    {\n"
                   + "        public static readonly string DescriptorJson = \"" + escaped + "\";\n"
                   + "    }\n"
                   + "}\n";
        }

        public static string ChunkedDescriptorCarrierSource(string escapedDescriptorJson)
        {
            const int chunkSize = 16000;
            var chunkCount = (escapedDescriptorJson.Length + chunkSize - 1) / chunkSize;
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("namespace Unity.FoxgloveSDK.Generated");
            sb.AppendLine("{");
            sb.AppendLine("    internal static class FoxRunGeneratedDescriptorInfo");
            sb.AppendLine("    {");
            sb.Append("        public static readonly string DescriptorJson = string.Concat(");
            for (var i = 0; i < chunkCount; i++)
            {
                if (i > 0)
                    sb.Append(", ");
                sb.Append("DescriptorJsonPart").Append(i.ToString(CultureInfo.InvariantCulture));
            }
            sb.AppendLine(");");
            for (var i = 0; i < chunkCount; i++)
            {
                var start = i * chunkSize;
                var length = Math.Min(chunkSize, escapedDescriptorJson.Length - start);
                sb.Append("        private const string DescriptorJsonPart")
                    .Append(i.ToString(CultureInfo.InvariantCulture))
                    .Append(" = \"")
                    .Append(escapedDescriptorJson.Substring(start, length))
                    .AppendLine("\";");
            }
            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        public static string EscapeStringLiteral(string value)
        {
            if (string.IsNullOrEmpty(value))
                return string.Empty;

            var sb = new StringBuilder();
            foreach (var ch in value)
            {
                switch (ch)
                {
                    case '"': sb.Append("\\\""); break;
                    case '\\': sb.Append("\\\\"); break;
                    case '\b': sb.Append("\\b"); break;
                    case '\f': sb.Append("\\f"); break;
                    case '\n': sb.Append("\\n"); break;
                    case '\r': sb.Append("\\r"); break;
                    case '\t': sb.Append("\\t"); break;
                    default:
                        if (ch < 0x20 || char.IsHighSurrogate(ch) || char.IsLowSurrogate(ch))
                        {
                            sb.Append("\\u");
                            sb.Append(((int)ch).ToString("x4", CultureInfo.InvariantCulture));
                        }
                        else
                        {
                            sb.Append(ch);
                        }
                        break;
                }
            }
            return sb.ToString();
        }
    }
}
