// Copyright (c) 2026 Jianbin Liu and Unity2Foxglove contributors.
// SPDX-License-Identifier: Apache-2.0
//
// Module: Editor
// Purpose: Scans assemblies for [FoxRun] attributed fields and generates
// IFoxgloveLogSource implementation .cs files for FoxgloveLogHub.

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using Unity.FoxgloveSDK.Components;
using UnityEngine;

namespace Unity.FoxgloveSDK.Editor
{
    /// <summary>
    /// Generates real .g.cs files for [FoxRun] annotated classes.
    /// Used by IPreprocessBuildWithReport to produce IL2CPP-compatible source files.
    /// Shares code generation logic with FoxgloveLogSourceGenerator (Roslyn ISG).
    /// </summary>
    public static class FoxrunCodeGenerator
    {
        const string OutputDir = "Assets/Scripts/Generated/";

        /// <summary>
        /// Collect the types that GenerateSourceFiles would process, without writing files.
        /// Returns a list of (assemblyName, namespace, className) tuples for IL2CPP preservation.
        /// </summary>
        public static List<(string AsmName, string Ns, string ClassName)> CollectFoxRunTypes()
        {
            var types = new List<(string, string, string)>();
            foreach (var asm in AppDomain.CurrentDomain.GetAssemblies())
            {
                try
                {
                    foreach (var type in asm.GetTypes())
                    {
                        if (!type.IsClass || type.IsAbstract) continue;
                        if (!IsPartial(type)) continue;
                        if (!typeof(MonoBehaviour).IsAssignableFrom(type)) continue;
                        var members = ScanType(type);
                        if (members.Count == 0) continue;
                        types.Add((asm.GetName().Name, type.Namespace ?? "", type.Name));
                    }
                }
                catch (ReflectionTypeLoadException ex)
                {
                    throw new InvalidOperationException(
                        $"Failed to scan assembly '{asm.GetName().Name}' for [FoxRun] types.", ex);
                }
            }
            return types;
        }

        /// <summary>
        /// Generate an IL2CPP link.xml snippet that preserves FoxRun user types
        /// discovered by CollectFoxRunTypes. Returns the XML string.
        /// </summary>
        public static string EmitLinkXml(List<(string AsmName, string Ns, string ClassName)> types)
        {
            var sb = new StringBuilder();
            sb.AppendLine("<?xml version=\"1.0\" encoding=\"utf-8\"?>");
            sb.AppendLine("<!-- Generated by FoxrunBuildPreprocess - do not edit by hand. -->");
            sb.AppendLine("<linker>");
            var seen = new HashSet<string>();
            foreach (var (asm, ns, cn) in types)
            {
                var full = string.IsNullOrEmpty(ns) ? cn : $"{ns}.{cn}";
                if (!seen.Add($"{asm}:{full}")) continue;
                sb.AppendLine($"  <assembly fullname=\"{asm}\">");
                sb.AppendLine($"    <type fullname=\"{full}\" preserve=\"all\" />");
                sb.AppendLine($"  </assembly>");
            }
            sb.AppendLine("</linker>");
            return sb.ToString();
        }

        /// <summary>
        /// Scan all loaded assemblies for [FoxRun] fields/properties on partial classes,
        /// and generate _FoxRun.g.cs files under Assets/Scripts/Generated/.
        /// Returns the list of generated file paths.
        /// Files are only written if content differs from existing file (prevents recompile loop).
        /// </summary>
        public static List<string> GenerateSourceFiles()
        {
            var result = new List<string>();
            var byClass = new Dictionary<(string Ns, string ClassName), List<MemberData>>();

            foreach (var asm in AppDomain.CurrentDomain.GetAssemblies())
            {
                try
                {
                    foreach (var type in asm.GetTypes())
                    {
                        if (!type.IsClass || type.IsAbstract) continue;
                        if (!IsPartial(type)) continue;
                        if (!typeof(MonoBehaviour).IsAssignableFrom(type)) continue;

                        var members = ScanType(type);
                        if (members.Count == 0) continue;

                        var ns = type.Namespace ?? "";
                        var key = (ns, type.Name);
                        if (!byClass.TryGetValue(key, out var list))
                            byClass[key] = list = new List<MemberData>();
                        list.AddRange(members);
                    }
                }
                catch (ReflectionTypeLoadException)
                {
                    // Source fallback generation is best-effort because the Roslyn
                    // path already reports authoring errors in the Editor. The
                    // link.xml scan is fail-fast and catches preservation risk.
                }
            }

            if (byClass.Count == 0) return result;

            Directory.CreateDirectory(Path.Combine(Application.dataPath, "Scripts/Generated"));

            foreach (var kv in byClass)
            {
                var source = EmitSourceFile(kv.Value.ToArray());
                var fileName = $"{kv.Key.ClassName}_FoxRun.g.cs";
                var absolutePath = Path.Combine(Application.dataPath, "Scripts/Generated", fileName);

                bool shouldWrite = true;
                if (File.Exists(absolutePath))
                {
                    var existing = File.ReadAllText(absolutePath);
                    if (existing == source)
                        shouldWrite = false;
                }

                if (shouldWrite)
                {
                    File.WriteAllText(absolutePath, source, Encoding.UTF8);
                    Debug.Log($"[FoxrunCodeGenerator] Generated {fileName}");
                }

                result.Add(fileName);
            }

            return result;
        }

        /// <summary>
        /// Checks whether a type was declared <c>partial</c>.
        /// <para>Runtime detection is not possible because the CLR erases partial
        /// metadata. The build pipeline assumes every <c>MonoBehaviour</c> with
        /// <c>[FoxRun]</c> members was declared partial; the Roslyn ISG enforces this
        /// at Editor compile time via FOXRUN001.</para>
        /// </summary>
        static bool IsPartial(Type type)
        {
            // Partial classes in C# have no runtime metadata at the type level.
            // We detect by checking if the generated members (via ISG) would create
            // a partial extension. For the build step, we assume any MonoBehaviour
            // with [FoxRun] members was declared partial in source.
            // If the class was NOT partial, ISG would have emitted FOXRUN001 at Editor compile time,
            // so this is a safe assumption for Player builds.
            return true;
        }

        /// <summary>
        /// Reflects over all instance fields and properties (public and non-public,
        /// declared only) on the given type and collects <c>[FoxRun]</c> attributed
        /// members as <c>MemberData</c> entries.
        /// </summary>
        static List<MemberData> ScanType(Type type)
        {
            var result = new List<MemberData>();
            var flags = BindingFlags.Instance | BindingFlags.NonPublic | BindingFlags.Public | BindingFlags.DeclaredOnly;
            var ns = type.Namespace ?? "";
            var cn = type.Name;

            foreach (var fi in type.GetFields(flags))
            {
                var attrs = fi.GetCustomAttributes<FoxRunAttribute>();
                foreach (var a in attrs)
                {
                    result.Add(new MemberData(
                        fi.Name, fi.FieldType, ns, cn, a.Topic, a.RateHz, a.SchemaName ?? "",
                        (int)a.PublishMode, a.ChangeEpsilon, a.ForceIntervalSeconds));
                }
            }
            foreach (var pi in type.GetProperties(flags))
            {
                var attrs = pi.GetCustomAttributes<FoxRunAttribute>();
                foreach (var a in attrs)
                {
                    result.Add(new MemberData(
                        pi.Name, pi.PropertyType, ns, cn, a.Topic, a.RateHz, a.SchemaName ?? "",
                        (int)a.PublishMode, a.ChangeEpsilon, a.ForceIntervalSeconds));
                }
            }
            return result;
        }

        /// <summary>
        /// Generate a complete .g.cs source file string for a single class.
        /// Delegates to <c>FoxgloveSourceEmitter.EmitClass</c> for output
        /// consistency with the Roslyn ISG path.
        /// </summary>
        public static string EmitSourceFile(MemberData[] members)
        {
            var first = members[0];
            var args = members.Select(m =>
                new FoxgloveSourceEmitter.TopicMember(m.MemberName, m.RawTypeName, m.Topic, m.RateHz, m.SchemaName,
                    m.PublishMode, m.ChangeEpsilon, m.ForceIntervalSeconds))
                .ToList();

            var core = FoxgloveSourceEmitter.EmitClass(first.Ns, first.ClassName, args);

            // Wrap with a Player-only guard so Editor compilation uses the Roslyn
            // generated in-memory source and Player builds use the physical file.
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("// Copyright (c) 2026 Jianbin Liu and Unity2Foxglove contributors.");
            sb.AppendLine("// SPDX-License-Identifier: Apache-2.0");
            sb.AppendLine("// Generated as a physical fallback for Player/IL2CPP builds.");
            sb.AppendLine("// In the Unity Editor, the Roslyn analyzer already generates this partial type in memory.");
            sb.AppendLine("#if !UNITY_EDITOR");
            sb.Append(core);
            sb.AppendLine("#endif");
            return sb.ToString();
        }

        /// <summary>
        /// Immutable data record for one <c>[FoxRun]</c>-attributed member, used
        /// during reflection-based scanning and source file generation.
        /// </summary>
        public sealed class MemberData
        {
            /// <summary>Field or property name.</summary>
            public readonly string MemberName;
            /// <summary>Field or property type as full-qualified string.</summary>
            public readonly string RawTypeName;
            /// <summary>Topic string from the attribute.</summary>
            public readonly string Topic;
            /// <summary>Optional schema name.</summary>
            public readonly string SchemaName;
            /// <summary>Containing class name.</summary>
            public readonly string ClassName;
            /// <summary>Containing namespace (empty for global).</summary>
            public readonly string Ns;
            /// <summary>Publishing rate in Hz.</summary>
            public readonly float RateHz;
            /// <summary>Publish mode as int enum value.</summary>
            public readonly int PublishMode;
            /// <summary>Change epsilon.</summary>
            public readonly float ChangeEpsilon;
            /// <summary>Heartbeat interval seconds.</summary>
            public readonly float ForceIntervalSeconds;

            /// <summary>
            /// Constructs a <c>MemberData</c> from a reflection <c>Type</c> and
            /// namespace/class context.
            /// </summary>
            public MemberData(string name, Type type, string ns, string cn, string topic, float rate, string schema,
                int publishMode = 0, float changeEpsilon = 0f, float forceIntervalSeconds = 0f)
            {
                MemberName = name;
                RawTypeName = type.FullName ?? type.Name;
                Ns = ns;
                ClassName = cn;
                Topic = topic;
                RateHz = rate;
                SchemaName = schema;
                PublishMode = publishMode;
                ChangeEpsilon = changeEpsilon;
                ForceIntervalSeconds = forceIntervalSeconds;
            }

            /// <summary>
            /// Constructs a <c>MemberData</c> with a raw type string and no
            /// namespace/class context (used in tests or diagnostics).
            /// </summary>
            public MemberData(string name, string rawType, string topic, float rate, string schema,
                int publishMode = 0, float changeEpsilon = 0f, float forceIntervalSeconds = 0f)
            {
                MemberName = name;
                RawTypeName = rawType;
                Topic = topic;
                RateHz = rate;
                SchemaName = schema;
                Ns = "";
                ClassName = "";
                PublishMode = publishMode;
                ChangeEpsilon = changeEpsilon;
                ForceIntervalSeconds = forceIntervalSeconds;
            }
        }
    }
}
