// Copyright (c) 2026 Jianbin Liu and Unity2Foxglove contributors.
// SPDX-License-Identifier: Apache-2.0
//
// Module: Editor/Shared/FoxgloveSourceEmitter

using System.Text;

namespace Unity.FoxgloveSDK.Editor
{
    /// <summary>
    /// Emits the class declaration frame, using directives, and interface
    /// implementation boilerplate for a generated FoxRun partial class.
    /// </summary>
    internal static class ClassFrameEmitter
    {
        /// <summary>
        /// Emits the opening class declaration, using directives,
        /// <c>[Preserve]</c> attribute, and interface implementation line for
        /// a generated FoxRun partial class. Returns the indentation pad string
        /// for subsequent method bodies.
        /// </summary>
        internal static string EmitClassFrame(
            StringBuilder sb,
            string ns,
            string className,
            int topicCount,
            bool hasPolicy,
            bool hasConditions,
            bool hasProviderAccess,
            bool hasInput,
            bool hasOwnedInput,
            bool hasTransactionalInput,
            bool hasTransactionalOwnedInput,
            string pad)
        {
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("// Copyright (c) 2026 Jianbin Liu and Unity2Foxglove contributors.");
            sb.AppendLine("// SPDX-License-Identifier: Apache-2.0");
            sb.AppendLine("// Generated by the Unity2Foxglove [FoxRun] source emitter.");
            sb.AppendLine("#pragma warning disable");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine("using UnityEngine.Scripting;");
            sb.AppendLine("using Unity.FoxgloveSDK.Components;");
            sb.AppendLine();

            if (!string.IsNullOrEmpty(ns)) { sb.AppendLine($"namespace {ns}"); sb.AppendLine("{"); }

            sb.AppendLine($"{pad}[Preserve]");
            var interfaces = new System.Collections.Generic.List<string>();
            if (topicCount > 0)
            {
                interfaces.Add("IFoxgloveLogSource");
                interfaces.Add("IFoxgloveTopicContractSource");
                interfaces.Add("IFoxgloveTopicBusSource");
                interfaces.Add("IFoxgloveTopicBusDemandSource");
                interfaces.Add("IFoxgloveTopicObserverSource");
                interfaces.Add("IFoxgloveTopicSinkSource");
                interfaces.Add("IFoxglovePublishCaptureSource");
                interfaces.Add("IFoxglovePublishRecordingSource");
                interfaces.Add("IFoxRunWebSocketCaptureSource");
                interfaces.Add("IFoxglovePublishOriginSource");
                if (hasPolicy)
                    interfaces.Add("IFoxgloveLogPolicySource");
                if (hasConditions)
                    interfaces.Add("IFoxgloveLogConditionSource");
            }
            if (hasInput)
                interfaces.Add("IFoxgloveInputSource");
            if (hasOwnedInput)
                interfaces.Add("IFoxgloveOwnedInputSource");
            if (hasTransactionalInput)
                interfaces.Add("IFoxgloveTransactionalInputSource");
            if (hasTransactionalOwnedInput)
                interfaces.Add("IFoxgloveTransactionalOwnedInputSource");
            if (hasProviderAccess)
                interfaces.Add("IFoxRunGeneratedTransportSource");
            sb.Append($"{pad}partial class {className}");
            if (interfaces.Count > 0)
                sb.Append(" : " + string.Join(", ", interfaces));
            sb.Append('\n');
            sb.AppendLine($"{pad}{{");
            if (topicCount > 0)
            {
                sb.AppendLine($"{pad}    int IFoxgloveLogSource.FoxgloveLog_TopicCount => {topicCount};");
                sb.AppendLine();
            }

            return pad;
        }
    }
}
